// src/views/accommodations/AccommodationListPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RouterLink } from 'vue-router';
import { accommodationsSearch } from '@/services/accommodations';
import type { SucursalPublicDto } from '@/models';

const rows = ref<SucursalPublicDto[]>([]);
const total = ref(0);
const pageSize = ref(10);
const pageIndex = ref(0);
const loading = ref(false);
const destino = ref('');

const minDate = new Date();
const checkIn = ref<Date>(startDates().checkIn);
const checkOut = ref<Date>(startDates().checkOut);

const adultos = ref(2);
const ninos = ref(0);
const habitaciones = ref(1);
const adultosOptions = [1, 2, 3, 4, 5, 6, 7, 8];
const ninosOptions = [0, 1, 2, 3, 4, 5, 6];
const habitacionOptions = [1, 2, 3, 4, 5];

function startDates(): { checkIn: Date; checkOut: Date } {
  const hoy = new Date();
  hoy.setHours(0, 0, 0, 0);
  const manana = new Date(hoy);
  manana.setDate(manana.getDate() + 1);
  return { checkIn: hoy, checkOut: manana };
}

function toDateInput(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

function parseDateInput(s: string): Date {
  const [y, m, d] = s.split('-').map(Number);
  const x = new Date(y, m - 1, d);
  x.setHours(0, 0, 0, 0);
  return x;
}

function onCheckInStr(v: string): void {
  checkIn.value = parseDateInput(v);
  if (checkOut.value.getTime() <= checkIn.value.getTime()) {
    const next = new Date(checkIn.value);
    next.setDate(next.getDate() + 1);
    checkOut.value = next;
  }
}

function fechasResumen(): string {
  if (checkOut.value.getTime() <= checkIn.value.getTime()) {
    return 'Agrega fechas';
  }
  return `${formatFechaCorta(checkIn.value)} – ${formatFechaCorta(checkOut.value)}`;
}

function huespedesResumen(): string {
  const n = adultos.value + ninos.value;
  const p = n === 1 ? 'huésped' : 'huéspedes';
  const h = habitaciones.value === 1 ? '1 hab.' : `${habitaciones.value} hab.`;
  return `${n} ${p} · ${h}`;
}

function formatFechaCorta(d: Date): string {
  return d.toLocaleDateString('es', { day: 'numeric', month: 'short' });
}

function estrellas(n: number | null | undefined): string {
  if (n == null || n <= 0) return '';
  return '★'.repeat(Math.min(5, Math.round(n)));
}

function resumenTexto(r: SucursalPublicDto, max = 120): string {
  const t = (r.descripcionSucursal ?? '').trim();
  if (t.length <= max) return t;
  return t.slice(0, max).trimEnd() + '…';
}

function reservaQueryParams(): Record<string, string> {
  if (checkOut.value.getTime() <= checkIn.value.getTime()) {
    return {};
  }
  return {
    fechaInicio: toDateTimeLocal(checkIn.value, 15, 0),
    fechaFin: toDateTimeLocal(checkOut.value, 11, 0),
  };
}

function toDateTimeLocal(d: Date, hours: number, minutes: number): string {
  const x = new Date(d);
  x.setHours(hours, minutes, 0, 0);
  const y = x.getFullYear();
  const m = String(x.getMonth() + 1).padStart(2, '0');
  const day = String(x.getDate()).padStart(2, '0');
  const h = String(x.getHours()).padStart(2, '0');
  const min = String(x.getMinutes()).padStart(2, '0');
  return `${y}-${m}-${day}T${h}:${min}`;
}

async function load(): Promise<void> {
  loading.value = true;
  const d = destino.value.trim();
  try {
    const res = await accommodationsSearch({
      nombre: d || undefined,
      ciudad: d || undefined,
      pageNumber: pageIndex.value + 1,
      pageSize: pageSize.value,
    });
    rows.value = res.data?.data ?? [];
    total.value = res.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function buscar(): void {
  pageIndex.value = 0;
  void load();
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

onMounted(() => {
  void load();
});
</script>

<template>
  <div class="list-page">
    <section class="hero" aria-labelledby="accom-hero-title">
      <div class="hero__inner">
        <h1 id="accom-hero-title">Encuentra tu próxima estancia</h1>
        <p class="hero__sub">
          Explora destinos por nombre o ciudad. Los datos de fechas y huéspedes acompañan tu reserva; el calendario del
          alojamiento confirma la disponibilidad.
        </p>
      </div>
    </section>

    <div class="search-sticky">
      <div class="search-pill" role="search" aria-label="Búsqueda de alojamientos">
        <div class="search-pill__segment search-pill__segment--where">
          <span class="search-pill__kicker">Dónde</span>
          <v-text-field
            v-model="destino"
            class="search-pill__field"
            label="Destino"
            variant="outlined"
            density="compact"
            hide-details
            placeholder="Explora destinos"
            @keydown.enter.prevent="buscar()"
          />
        </div>
        <span class="search-pill__divider" aria-hidden="true" />
        <div class="search-pill__segment search-pill__segment--dates">
          <span class="search-pill__kicker">Fechas</span>
          <p class="search-pill__hint">{{ fechasResumen() }}</p>
          <div class="search-pill__date-row">
            <v-text-field
              :model-value="toDateInput(checkIn)"
              class="search-pill__field search-pill__field--date"
              label="Llegada"
              type="date"
              variant="outlined"
              density="compact"
              hide-details
              :min="toDateInput(minDate)"
              @update:model-value="(v) => v && onCheckInStr(String(v))"
            />
            <v-text-field
              :model-value="toDateInput(checkOut)"
              class="search-pill__field search-pill__field--date"
              label="Salida"
              type="date"
              variant="outlined"
              density="compact"
              hide-details
              :min="toDateInput(checkIn)"
              @update:model-value="(v) => v && (checkOut = parseDateInput(String(v)))"
            />
          </div>
        </div>
        <span class="search-pill__divider" aria-hidden="true" />
        <div class="search-pill__segment search-pill__segment--who">
          <span class="search-pill__kicker">Quién</span>
          <p class="search-pill__hint">{{ huespedesResumen() }}</p>
          <div class="search-pill__guest-row" aria-label="Ocupación">
            <v-select
              v-model="adultos"
              class="search-pill__field search-pill__mini"
              :items="adultosOptions"
              label="Adultos"
              variant="outlined"
              density="compact"
              hide-details
            />
            <v-select
              v-model="ninos"
              class="search-pill__field search-pill__mini"
              :items="ninosOptions"
              label="Niños"
              variant="outlined"
              density="compact"
              hide-details
            />
            <v-select
              v-model="habitaciones"
              class="search-pill__field search-pill__mini"
              :items="habitacionOptions"
              label="Habit."
              variant="outlined"
              density="compact"
              hide-details
            />
          </div>
        </div>
        <button class="search-pill__search-btn" type="button" aria-label="Buscar alojamientos" @click="buscar()">
          <v-icon icon="mdi-magnify" />
        </button>
      </div>
    </div>

    <section class="results" aria-live="polite">
      <div class="results__head">
        <h2>Resultados</h2>
        <span v-if="total > 0" class="results__count">{{ total }} alojamientos</span>
      </div>

      <div v-if="loading" class="center">
        <v-progress-circular indeterminate />
      </div>
      <v-card v-else-if="rows.length === 0" class="empty-card pa-4">
        <p>No hay alojamientos con esos criterios. Prueba con otro destino o amplía la búsqueda.</p>
      </v-card>
      <template v-else>
        <div class="card-grid">
          <v-card v-for="r in rows" :key="r.sucursalGuid" class="property-card" elevation="2">
            <div
              class="property-card__media"
              role="img"
              :aria-label="'Imagen de ' + (r.nombreSucursal ?? 'alojamiento')"
            >
              <span class="property-card__media-fallback" aria-hidden="true">
                <v-icon icon="mdi-city" size="large" />
              </span>
            </div>
            <div class="property-card__body">
              <div class="property-card__title-row">
                <h3 class="property-card__name">{{ r.nombreSucursal ?? '—' }}</h3>
                <span v-if="r.estrellas" class="property-card__stars" :aria-label="'Estrellas: ' + r.estrellas">
                  {{ estrellas(r.estrellas) }}
                </span>
              </div>
              <p class="property-card__location">
                <v-icon class="inline-icon" icon="mdi-map-marker" size="small" aria-hidden="true" />
                {{ r.ciudad ?? '—' }}{{ r.pais ? ', ' + r.pais : '' }}
              </p>
              <p v-if="r.tipoAlojamiento" class="property-card__meta">{{ r.tipoAlojamiento }}</p>
              <p v-if="r.descripcionSucursal" class="property-card__desc">{{ resumenTexto(r) }}</p>
              <div class="property-card__actions">
                <v-btn variant="outlined" color="primary" :to="'/alojamientos/' + r.sucursalGuid">Ver detalles</v-btn>
                <v-btn
                  color="primary"
                  class="property-card__book"
                  :to="{ path: '/reservar/' + r.sucursalGuid, query: reservaQueryParams() }"
                >
                  Reservar
                </v-btn>
              </div>
            </div>
          </v-card>
        </div>

        <v-pagination
          class="results__paginator mt-4"
          :length="Math.max(1, Math.ceil(total / pageSize))"
          :model-value="pageIndex + 1"
          :total-visible="7"
          @update:model-value="onPage"
        />
      </template>
    </section>
  </div>
</template>

<style scoped src="./accommodation-list-page.scss"></style>

// src/app/features/accommodations/accommodation-list-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDatepickerModule } from '@angular/material/datepicker';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { AccommodationsService } from '../../core/services/accommodations.service';
import type { SucursalPublicDto } from '../../shared/models';

@Component({
  selector: 'app-accommodation-list-page',
  standalone: true,
  imports: [
    FormsModule,
    RouterLink,
    MatPaginatorModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCardModule,
    MatProgressSpinnerModule,
    MatDatepickerModule,
    MatIconModule,
    MatSelectModule,
  ],
  templateUrl: './accommodation-list-page.component.html',
  styleUrl: './accommodation-list-page.component.scss',
})
export class AccommodationListPageComponent implements OnInit {
  private readonly api = inject(AccommodationsService);

  rows: SucursalPublicDto[] = [];
  total = 0;
  pageSize = 10;
  pageIndex = 0;
  loading = false;

  /** Un solo campo “destino” en la UI; se envía como `ciudad` a la búsqueda pública. */
  destino = '';

  minDate = new Date();
  checkIn: Date;
  checkOut: Date;
  adultos = 2;
  ninos = 0;
  habitaciones = 1;

  /** Opciones reutilizables (solo UI, no se envían al API de búsqueda). */
  readonly adultosOptions = [1, 2, 3, 4, 5, 6, 7, 8];
  readonly ninosOptions = [0, 1, 2, 3, 4, 5, 6];
  readonly habitacionOptions = [1, 2, 3, 4, 5];

  constructor() {
    const hoy = new Date();
    hoy.setHours(0, 0, 0, 0);
    const manana = new Date(hoy);
    manana.setDate(manana.getDate() + 1);
    this.checkIn = hoy;
    this.checkOut = manana;
  }

  ngOnInit(): void {
    this.load();
  }

  /** Query params para `datetime-local` en la pantalla de reserva. */
  reservaQueryParams(): Record<string, string> {
    if (!this.checkIn || !this.checkOut) {
      return {};
    }
    if (this.checkOut.getTime() <= this.checkIn.getTime()) {
      return {};
    }
    return {
      fechaInicio: this.toDateTimeLocal(this.checkIn, 15, 0),
      fechaFin: this.toDateTimeLocal(this.checkOut, 11, 0),
    };
  }

  onCheckInChange(): void {
    if (this.checkOut.getTime() <= this.checkIn.getTime()) {
      const next = new Date(this.checkIn);
      next.setDate(next.getDate() + 1);
      this.checkOut = next;
    }
  }

  /** Texto resumido para el segmento “Fechas” (estilo marketplace tipo Airbnb). */
  fechasResumen(): string {
    if (!this.checkIn || !this.checkOut) {
      return 'Agrega fechas';
    }
    if (this.checkOut.getTime() <= this.checkIn.getTime()) {
      return 'Agrega fechas';
    }
    return `${this.formatFechaCorta(this.checkIn)} – ${this.formatFechaCorta(this.checkOut)}`;
  }

  /** Texto resumido para huéspedes / habitaciones. */
  huespedesResumen(): string {
    const n = this.adultos + this.ninos;
    const p = n === 1 ? 'huésped' : 'huéspedes';
    const h = this.habitaciones === 1 ? '1 hab.' : `${this.habitaciones} hab.`;
    return `${n} ${p} · ${h}`;
  }

  private formatFechaCorta(d: Date): string {
    return d.toLocaleDateString('es', { day: 'numeric', month: 'short' });
  }

  estrellas(n: number | null | undefined): string {
    if (n == null || n <= 0) {
      return '';
    }
    return '★'.repeat(Math.min(5, Math.round(n)));
  }

  resumenTexto(r: SucursalPublicDto, max = 120): string {
    const t = (r.descripcionSucursal ?? '').trim();
    if (t.length <= max) {
      return t;
    }
    return t.slice(0, max).trimEnd() + '…';
  }

  load(): void {
    this.loading = true;
    const d = this.destino.trim();
    this.api
      .search({
        nombre: d || undefined,
        ciudad: d || undefined,
        pageNumber: this.pageIndex + 1,
        pageSize: this.pageSize,
      })
      .subscribe({
        next: (res) => {
          this.rows = res.data?.data ?? [];
          this.total = res.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  buscar(): void {
    this.pageIndex = 0;
    this.load();
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  private toDateTimeLocal(d: Date, hours: number, minutes: number): string {
    const x = new Date(d);
    x.setHours(hours, minutes, 0, 0);
    const y = x.getFullYear();
    const m = String(x.getMonth() + 1).padStart(2, '0');
    const day = String(x.getDate()).padStart(2, '0');
    const h = String(x.getHours()).padStart(2, '0');
    const min = String(x.getMinutes()).padStart(2, '0');
    return `${y}-${m}-${day}T${h}:${min}`;
  }
}

<div class="list-page">
  <section class="hero" aria-labelledby="accom-hero-title">
    <div class="hero__inner">
      <h1 id="accom-hero-title">Encuentra tu próxima estancia</h1>
      <p class="hero__sub">
        Explora destinos por nombre o ciudad. Los datos de fechas y huéspedes acompañan tu reserva;
        el calendario del alojamiento confirma la disponibilidad.
      </p>
    </div>
  </section>

  <div class="search-sticky">
    <div class="search-pill" role="search" aria-label="Búsqueda de alojamientos">
      <div class="search-pill__segment search-pill__segment--where">
        <span class="search-pill__kicker">Dónde</span>
        <mat-form-field class="search-pill__field" appearance="outline" subscriptSizing="dynamic">
          <mat-label>Destino</mat-label>
          <input
            matInput
            name="destino"
            [(ngModel)]="destino"
            (keydown.enter)="$event.preventDefault(); buscar()"
            placeholder="Explora destinos"
            autocomplete="off"
          />
        </mat-form-field>
      </div>

      <span class="search-pill__divider" aria-hidden="true"></span>

      <div class="search-pill__segment search-pill__segment--dates">
        <span class="search-pill__kicker">Fechas</span>
        <p class="search-pill__hint">{{ fechasResumen() }}</p>
        <div class="search-pill__date-row">
          <mat-form-field class="search-pill__field search-pill__field--date" appearance="outline" subscriptSizing="dynamic">
            <mat-label>Llegada</mat-label>
            <input
              matInput
              [matDatepicker]="dpIn"
              [(ngModel)]="checkIn"
              [min]="minDate"
              (ngModelChange)="onCheckInChange()"
              name="checkIn"
            />
            <mat-datepicker-toggle matIconSuffix [for]="dpIn" />
            <mat-datepicker #dpIn />
          </mat-form-field>
          <mat-form-field class="search-pill__field search-pill__field--date" appearance="outline" subscriptSizing="dynamic">
            <mat-label>Salida</mat-label>
            <input
              matInput
              [matDatepicker]="dpOut"
              [(ngModel)]="checkOut"
              [min]="checkIn"
              name="checkOut"
            />
            <mat-datepicker-toggle matIconSuffix [for]="dpOut" />
            <mat-datepicker #dpOut />
          </mat-form-field>
        </div>
      </div>

      <span class="search-pill__divider" aria-hidden="true"></span>

      <div class="search-pill__segment search-pill__segment--who">
        <span class="search-pill__kicker">Quién</span>
        <p class="search-pill__hint">{{ huespedesResumen() }}</p>
        <div class="search-pill__guest-row" aria-label="Ocupación">
          <mat-form-field class="search-pill__field search-pill__mini" appearance="outline" subscriptSizing="dynamic">
            <mat-label>Adultos</mat-label>
            <mat-select [(ngModel)]="adultos" name="adultos">
              @for (a of adultosOptions; track a) {
                <mat-option [value]="a">{{ a }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
          <mat-form-field class="search-pill__field search-pill__mini" appearance="outline" subscriptSizing="dynamic">
            <mat-label>Niños</mat-label>
            <mat-select [(ngModel)]="ninos" name="ninos">
              @for (n of ninosOptions; track n) {
                <mat-option [value]="n">{{ n }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
          <mat-form-field class="search-pill__field search-pill__mini" appearance="outline" subscriptSizing="dynamic">
            <mat-label>Habit.</mat-label>
            <mat-select [(ngModel)]="habitaciones" name="habitaciones">
              @for (h of habitacionOptions; track h) {
                <mat-option [value]="h">{{ h }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>
      </div>

      <button
        class="search-pill__search-btn"
        type="button"
        (click)="buscar()"
        aria-label="Buscar alojamientos"
      >
        <mat-icon>search</mat-icon>
      </button>
    </div>
  </div>

  <section class="results" aria-live="polite">
    <div class="results__head">
      <h2>Resultados</h2>
      @if (total > 0) {
        <span class="results__count">{{ total }} alojamientos</span>
      }
    </div>

    @if (loading) {
      <div class="center">
        <mat-spinner diameter="40" />
      </div>
    } @else if (rows.length === 0) {
      <mat-card class="empty-card">
        <p>No hay alojamientos con esos criterios. Prueba con otro destino o amplía la búsqueda.</p>
      </mat-card>
    } @else {
      <div class="card-grid">
        @for (r of rows; track r.sucursalGuid) {
          <mat-card class="property-card mat-elevation-z2">
            <div class="property-card__media" role="img" [attr.aria-label]="'Imagen de ' + (r.nombreSucursal ?? 'alojamiento')">
              <span class="property-card__media-fallback" aria-hidden="true">
                <mat-icon>apartment</mat-icon>
              </span>
            </div>
            <div class="property-card__body">
              <div class="property-card__title-row">
                <h3 class="property-card__name">{{ r.nombreSucursal ?? '—' }}</h3>
                @if (r.estrellas) {
                  <span class="property-card__stars" [attr.aria-label]="'Estrellas: ' + r.estrellas">
                    {{ estrellas(r.estrellas) }}
                  </span>
                }
              </div>
              <p class="property-card__location">
                <mat-icon class="inline-icon" aria-hidden="true">place</mat-icon>
                {{ r.ciudad ?? '—' }}{{ r.pais ? ', ' + r.pais : '' }}
              </p>
              @if (r.tipoAlojamiento) {
                <p class="property-card__meta">{{ r.tipoAlojamiento }}</p>
              }
              @if (r.descripcionSucursal) {
                <p class="property-card__desc">{{ resumenTexto(r) }}</p>
              }
              <div class="property-card__actions">
                <a mat-stroked-button color="primary" [routerLink]="['/alojamientos', r.sucursalGuid]">
                  Ver detalles
                </a>
                <a
                  mat-raised-button
                  class="property-card__book"
                  color="primary"
                  [routerLink]="['/reservar', r.sucursalGuid]"
                  [queryParams]="reservaQueryParams()"
                >
                  Reservar
                </a>
              </div>
            </div>
          </mat-card>
        }
      </div>

      <mat-paginator
        class="results__paginator"
        [length]="total"
        [pageIndex]="pageIndex"
        [pageSize]="pageSize"
        [pageSizeOptions]="[5, 10, 20]"
        (page)="onPage($event)"
      />
    }
  </section>
</div>
