// src/app/features/accommodations/accommodation-detail-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatCardModule } from '@angular/material/card';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { AccommodationsService } from '../../core/services/accommodations.service';
import { AlojamientosService } from '../../core/services/alojamientos.service';
import { isPositiveIntString, isUuidString } from '../../shared/utils/string.util';
import type { AlojamientoResponseDTO, SucursalPublicDto } from '../../shared/models';

@Component({
  selector: 'app-accommodation-detail-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatButtonModule, MatProgressSpinnerModule, MatIconModule],
  templateUrl: './accommodation-detail-page.component.html',
  styleUrl: './accommodation-detail-page.component.scss',
})
export class AccommodationDetailPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly accommodations = inject(AccommodationsService);
  private readonly alojamientos = inject(AlojamientosService);

  /** El segmento de ruta `:id` puede ser <code>uuid</code> (sucursal pública) o id numérico (entidad <code>Alojamiento</code>), según OpenAPI. */
  loading = true;
  error?: string;
  sucursal?: SucursalPublicDto;
  alojamiento?: AlojamientoResponseDTO;
  /** Solo aplica cuando el detalle es `Sucursal` pública (UUID). */
  reservarLink: string[] = [];

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id') ?? '';
    if (isUuidString(id)) {
      this.accommodations.getBySucursalGuid(id).subscribe({
        next: (res) => {
          if (res.success && res.data) {
            this.sucursal = res.data;
            this.reservarLink = ['/reservar', id];
          } else {
            this.error = res.message || 'No se pudo cargar el alojamiento.';
          }
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
      return;
    }
    if (isPositiveIntString(id)) {
      this.alojamientos.getById(Number(id)).subscribe({
        next: (res) => {
          if (res.success && res.data) {
            this.alojamiento = res.data;
            // TODO(Backend): `Reservar` público consume `Sucursal` (`sucursalGuid`); no hay en OpenAPI
            // mapeo explícito `Alojamiento` → `Sucursal`. Oculte el flujo de reserva hasta exista contrato.
          } else {
            this.error = res.message || 'No se pudo cargar el alojamiento.';
          }
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
      return;
    }
    this.error = 'Formato de id no reconocido: use un UUID de sucursal o un id numérico de Alojamiento.';
    this.loading = false;
  }
}

@if (loading) {
  <div class="detail-state detail-state--center">
    <mat-spinner diameter="44" aria-label="Cargando" />
  </div>
} @else if (error) {
  <div class="detail-page hl-page">
    <mat-card class="detail-card detail-card--error">
      <mat-card-content>
        <mat-icon class="detail-card__icon" aria-hidden="true">error_outline</mat-icon>
        <h2 class="detail-card__title">No pudimos cargar el alojamiento</h2>
        <p class="detail-card__text">{{ error }}</p>
        <a mat-stroked-button routerLink="/alojamientos" color="primary">Volver al listado</a>
      </mat-card-content>
    </mat-card>
  </div>
} @else if (sucursal) {
  <article class="detail-page hl-page">
    <header class="detail-header">
        <nav class="detail-breadcrumb">
          <a routerLink="/alojamientos" class="detail-breadcrumb__link">
            <mat-icon inline>arrow_back</mat-icon>
            Alojamientos
          </a>
        </nav>
        <h1 class="detail-header__title">{{ sucursal.nombreSucursal }}</h1>
        <p class="detail-header__meta">
          {{ sucursal.ciudad }} · {{ sucursal.provincia }} · {{ sucursal.pais }}
        </p>
    </header>

    <div class="detail-grid">
      <div class="detail-media" role="img" [attr.aria-label]="'Imagen principal de ' + (sucursal.nombreSucursal ?? 'alojamiento')">
        <mat-icon class="detail-media__icon" aria-hidden="true">apartment</mat-icon>
      </div>
      <div class="detail-body mat-elevation-z0">
        <section class="detail-section">
          <h2>Sobre este alojamiento</h2>
          <p class="detail-copy">{{ sucursal.descripcionSucursal }}</p>
        </section>
        <section class="detail-section detail-section--horarios">
          <h2>Horarios</h2>
          <dl class="detail-dl">
            <div>
              <dt>Check-in</dt>
              <dd>{{ sucursal.horaCheckin }}</dd>
            </div>
            <div>
              <dt>Check-out</dt>
              <dd>{{ sucursal.horaCheckout }}</dd>
            </div>
          </dl>
        </section>
        <div class="detail-actions">
          <a mat-flat-button color="primary" [routerLink]="reservarLink" class="detail-actions__primary">
            Reservar
            <mat-icon iconPositionEnd>calendar_month</mat-icon>
          </a>
          <a mat-button routerLink="/alojamientos">Seguir explorando</a>
        </div>
      </div>
    </div>
  </article>
} @else if (alojamiento) {
  <article class="detail-page hl-page">
    <header class="detail-header">
      <nav class="detail-breadcrumb">
        <a routerLink="/alojamientos" class="detail-breadcrumb__link">
          <mat-icon inline>arrow_back</mat-icon>
          Alojamientos
        </a>
      </nav>
      <h1 class="detail-header__title">{{ alojamiento.nombre }}</h1>
      <p class="detail-header__meta">
        {{ alojamiento.ciudad }} · Estado: {{ alojamiento.estadoAlojamiento }}
      </p>
    </header>
    <div class="detail-grid detail-grid--single">
      <div class="detail-body mat-elevation-z0 detail-body--wide">
        <p class="detail-copy">{{ alojamiento.descripcion }}</p>
        <p class="detail-note">
          La reserva en línea está disponible para sucursales (detalle con identificador público tipo UUID).
          Este registro corresponde a un alojamiento administrativo; vuelve al listado para elegir una sucursal
          reservable.
        </p>
        <a mat-stroked-button routerLink="/alojamientos" color="primary">Ir al listado</a>
      </div>
    </div>
  </article>
}

// src/views/accommodations/AccommodationDetailPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { RouterLink, useRoute } from 'vue-router';
import { accommodationsGetByGuid } from '@/services/accommodations';
import { alojamientosGetById } from '@/services/alojamientos';
import { isPositiveIntString, isUuidString } from '@/utils/string.util';
import type { AlojamientoResponseDTO, SucursalPublicDto } from '@/models';

const route = useRoute();
const loading = ref(true);
const error = ref<string | undefined>();
const sucursal = ref<SucursalPublicDto | undefined>();
const alojamiento = ref<AlojamientoResponseDTO | undefined>();
const reservarLink = ref('');

onMounted(async () => {
  const id = String(route.params.id ?? '');
  if (isUuidString(id)) {
    try {
      const res = await accommodationsGetByGuid(id);
      if (res.success && res.data) {
        sucursal.value = res.data;
        reservarLink.value = '/reservar/' + id;
      } else {
        error.value = res.message || 'No se pudo cargar el alojamiento.';
      }
    } finally {
      loading.value = false;
    }
    return;
  }
  if (isPositiveIntString(id)) {
    try {
      const res = await alojamientosGetById(Number(id));
      if (res.success && res.data) {
        alojamiento.value = res.data;
      } else {
        error.value = res.message || 'No se pudo cargar el alojamiento.';
      }
    } finally {
      loading.value = false;
    }
    return;
  }
  error.value = 'Formato de id no reconocido: use un UUID de sucursal o un id numérico de Alojamiento.';
  loading.value = false;
});
</script>

<template>
  <div v-if="loading" class="detail-state detail-state--center">
    <v-progress-circular indeterminate />
  </div>
  <div v-else-if="error" class="detail-page hl-page">
    <v-card class="detail-card detail-card--error pa-6">
      <v-icon class="detail-card__icon" icon="mdi-alert-circle-outline" />
      <h2 class="detail-card__title">No pudimos cargar el alojamiento</h2>
      <p class="detail-card__text">{{ error }}</p>
      <v-btn variant="outlined" color="primary" to="/alojamientos">Volver al listado</v-btn>
    </v-card>
  </div>
  <article v-else-if="sucursal" class="detail-page hl-page">
    <header class="detail-header">
      <nav class="detail-breadcrumb">
        <RouterLink to="/alojamientos" class="detail-breadcrumb__link">
          <v-icon icon="mdi-arrow-left" size="small" />
          Alojamientos
        </RouterLink>
      </nav>
      <h1 class="detail-header__title">{{ sucursal.nombreSucursal }}</h1>
      <p class="detail-header__meta">{{ sucursal.ciudad }} · {{ sucursal.provincia }} · {{ sucursal.pais }}</p>
    </header>
    <div class="detail-grid">
      <div
        class="detail-media"
        role="img"
        :aria-label="'Imagen principal de ' + (sucursal.nombreSucursal ?? 'alojamiento')"
      >
        <v-icon class="detail-media__icon" icon="mdi-city" size="64" />
      </div>
      <div class="detail-body">
        <section class="detail-section">
          <h2>Sobre este alojamiento</h2>
          <p class="detail-copy">{{ sucursal.descripcionSucursal }}</p>
        </section>
        <section class="detail-section detail-section--horarios">
          <h2>Horarios</h2>
          <dl class="detail-dl">
            <div>
              <dt>Check-in</dt>
              <dd>{{ sucursal.horaCheckin }}</dd>
            </div>
            <div>
              <dt>Check-out</dt>
              <dd>{{ sucursal.horaCheckout }}</dd>
            </div>
          </dl>
        </section>
        <div class="detail-actions">
          <v-btn color="primary" :to="reservarLink" class="detail-actions__primary">
            Reservar
            <v-icon end icon="mdi-calendar-month" />
          </v-btn>
          <v-btn variant="text" to="/alojamientos">Seguir explorando</v-btn>
        </div>
      </div>
    </div>
  </article>
  <article v-else-if="alojamiento" class="detail-page hl-page">
    <header class="detail-header">
      <nav class="detail-breadcrumb">
        <RouterLink to="/alojamientos" class="detail-breadcrumb__link">
          <v-icon icon="mdi-arrow-left" size="small" />
          Alojamientos
        </RouterLink>
      </nav>
      <h1 class="detail-header__title">{{ alojamiento.nombre }}</h1>
      <p class="detail-header__meta">{{ alojamiento.ciudad }} · Estado: {{ alojamiento.estadoAlojamiento }}</p>
    </header>
    <div class="detail-grid detail-grid--single">
      <div class="detail-body detail-body--wide">
        <p class="detail-copy">{{ alojamiento.descripcion }}</p>
        <p class="detail-note">
          La reserva en línea está disponible para sucursales (detalle con identificador público tipo UUID). Este
          registro corresponde a un alojamiento administrativo; vuelve al listado para elegir una sucursal reservable.
        </p>
        <v-btn variant="outlined" color="primary" to="/alojamientos">Ir al listado</v-btn>
      </div>
    </div>
  </article>
</template>
