// src/app/features/reservations/mis-reservas-page.component.ts
import { DatePipe, DecimalPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { habitacionDesdeObservaciones } from '../../shared/utils/reserva-display.util';
import { ReservasService } from '../../core/services/reservas.service';
import { UserContextService } from '../../core/services/user-context.service';
import type { ReservaDTO } from '../../shared/models';

@Component({
  selector: 'app-mis-reservas-page',
  standalone: true,
  imports: [
    DatePipe,
    DecimalPipe,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatTableModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './mis-reservas-page.component.html',
  styleUrl: './mis-reservas-page.component.scss',
})
export class MisReservasPageComponent implements OnInit {
  private readonly reservas = inject(ReservasService);
  readonly user = inject(UserContextService);
  private readonly fb = inject(FormBuilder);
  private readonly snack = inject(MatSnackBar);

  displayedColumns: string[] = ['codigo', 'habitacion', 'sucursal', 'inicio', 'fin', 'total', 'estado'];
  rows: ReservaDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;
  idClienteEfectivo: number | null = null;

  readonly formCliente = this.fb.nonNullable.group({
    idCliente: this.fb.control<number | null>(null, [Validators.required, Validators.min(1)]),
  });

  ngOnInit(): void {
    this.user.refreshMe().subscribe({
      next: () => {
        this.syncIdClienteYLista();
      },
    });
  }

  private syncIdClienteYLista(): void {
    this.idClienteEfectivo = this.user.getIdCliente();
    if (this.idClienteEfectivo) {
      this.formCliente.patchValue({ idCliente: this.idClienteEfectivo });
    }
    if (this.idClienteEfectivo) {
      this.load();
    } else {
      this.snack.open(
        'No pudimos vincular tu cuenta de cliente automáticamente. Indica el identificador que te dio recepción.',
        'Cerrar',
        { duration: 8000 },
      );
    }
  }

  guardarIdCliente(): void {
    if (this.formCliente.invalid) {
      this.formCliente.markAllAsTouched();
      return;
    }
    const v = this.formCliente.getRawValue().idCliente;
    this.user.setIdClienteOverride(v);
    this.idClienteEfectivo = v;
    this.load();
  }

  limpiarOverride(): void {
    this.user.setIdClienteOverride(null);
    this.user.refreshMe().subscribe({
      next: () => {
        this.idClienteEfectivo = this.user.getIdCliente();
        this.load();
      },
    });
  }

  load(): void {
    const id = this.user.getIdCliente();
    if (id == null) {
      this.rows = [];
      this.total = 0;
      return;
    }
    this.loading = true;
    this.reservas
      .list({
        IdCliente: id,
        PageNumber: this.pageIndex + 1,
        PageSize: this.pageSize,
      })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  habitacionEtiqueta(r: ReservaDTO): string {
    return habitacionDesdeObservaciones(r.observaciones) ?? '—';
  }
}

<div class="mis-reservas hl-page">
  <header class="mis-reservas__head">
    <h1>Mis reservas</h1>
    <p class="mis-reservas__lede">
      Aquí aparecen las reservas asociadas a tu perfil de cliente. Si el sistema no reconoce tu identificador, puedes
      indicar el que te entregó recepción para esta sesión.
    </p>
  </header>

  <mat-card class="mis-reservas__panel">
    <mat-card-header>
      <mat-card-title>Identificación</mat-card-title>
      <mat-card-subtitle>Vínculo con tu cuenta de huésped</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      @if (idClienteEfectivo != null) {
        <p class="mis-reservas__status">
          Cliente activo:
          <strong>{{ idClienteEfectivo }}</strong>
          @if (user.getStoredIdClienteOverride()) {
            <span class="mis-reservas__badge">Guardado en este dispositivo</span>
          }
        </p>
      }
      <form class="mis-reservas__form" [formGroup]="formCliente" (ngSubmit)="guardarIdCliente()">
        <mat-form-field appearance="outline" class="mis-reservas__field">
          <mat-label>Id cliente</mat-label>
          <input matInput type="number" formControlName="idCliente" />
        </mat-form-field>
        <div class="mis-reservas__form-actions">
          <button mat-flat-button color="primary" type="submit" [disabled]="formCliente.invalid">Aplicar</button>
          <button mat-button type="button" (click)="limpiarOverride()">Borrar id guardado</button>
        </div>
      </form>
    </mat-card-content>
  </mat-card>

  @if (user.getIdCliente() == null) {
    <mat-card class="mis-reservas__empty">
      <mat-card-content>
        <p>Indica un identificador de cliente arriba para cargar tu historial.</p>
      </mat-card-content>
    </mat-card>
  } @else if (loading) {
    <div class="mis-reservas__center"><mat-spinner diameter="44" /></div>
  } @else {
    <div class="mis-reservas__table-wrap mat-elevation-z0">
      <table mat-table [dataSource]="rows" class="mis-reservas__table">
        <ng-container matColumnDef="codigo">
          <th mat-header-cell *matHeaderCellDef>Código</th>
          <td mat-cell *matCellDef="let r">{{ r.codigoReserva }}</td>
        </ng-container>
        <ng-container matColumnDef="habitacion">
          <th mat-header-cell *matHeaderCellDef>Habitación</th>
          <td mat-cell *matCellDef="let r">{{ habitacionEtiqueta(r) }}</td>
        </ng-container>
        <ng-container matColumnDef="sucursal">
          <th mat-header-cell *matHeaderCellDef>Sucursal</th>
          <td mat-cell *matCellDef="let r">{{ r.idSucursal }}</td>
        </ng-container>
        <ng-container matColumnDef="inicio">
          <th mat-header-cell *matHeaderCellDef>Inicio</th>
          <td mat-cell *matCellDef="let r">{{ r.fechaInicio | date: 'short' }}</td>
        </ng-container>
        <ng-container matColumnDef="fin">
          <th mat-header-cell *matHeaderCellDef>Fin</th>
          <td mat-cell *matCellDef="let r">{{ r.fechaFin | date: 'short' }}</td>
        </ng-container>
        <ng-container matColumnDef="total">
          <th mat-header-cell *matHeaderCellDef>Total</th>
          <td mat-cell *matCellDef="let r">{{ r.totalReserva | number: '1.2-2' }}</td>
        </ng-container>
        <ng-container matColumnDef="estado">
          <th mat-header-cell *matHeaderCellDef>Estado</th>
          <td mat-cell *matCellDef="let r">{{ r.estadoReserva }}</td>
        </ng-container>
        <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
        <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
      </table>
    </div>
    <mat-paginator
      class="mis-reservas__paginator"
      [length]="total"
      [pageIndex]="pageIndex"
      [pageSize]="pageSize"
      [pageSizeOptions]="[5, 10, 20]"
      (page)="onPage($event)"
    />
  }
</div>

// src/views/reservations/MisReservasPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { habitacionDesdeObservaciones } from '@/utils/reserva-display.util';
import { reservasList } from '@/services/reservas';
import { useUserContextStore } from '@/stores/userContext';
import { useUiStore } from '@/stores/ui';
import type { ReservaDTO } from '@/models';

const user = useUserContextStore();
const ui = useUiStore();

const displayedColumns = ['codigo', 'habitacion', 'sucursal', 'inicio', 'fin', 'total', 'estado'];
const rows = ref<ReservaDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);
const idClienteEfectivo = ref<number | null>(null);
const formCliente = ref({ idCliente: null as number | null });

function syncIdClienteYLista(): void {
  idClienteEfectivo.value = user.getIdCliente();
  if (idClienteEfectivo.value) {
    formCliente.value.idCliente = idClienteEfectivo.value;
  }
  if (idClienteEfectivo.value) {
    void load();
  } else {
    ui.showSnack(
      'No pudimos vincular tu cuenta de cliente automáticamente. Indica el identificador que te dio recepción.',
      8000,
    );
  }
}

onMounted(() => {
  void user.refreshMe().then(() => syncIdClienteYLista());
});

function guardarIdCliente(): void {
  const v = formCliente.value.idCliente;
  if (v == null || v < 1) {
    return;
  }
  user.setIdClienteOverride(v);
  idClienteEfectivo.value = v;
  void load();
}

function limpiarOverride(): void {
  user.setIdClienteOverride(null);
  void user.refreshMe().then(() => {
    idClienteEfectivo.value = user.getIdCliente();
    void load();
  });
}

async function load(): Promise<void> {
  const id = user.getIdCliente();
  if (id == null) {
    rows.value = [];
    total.value = 0;
    return;
  }
  loading.value = true;
  try {
    const r = await reservasList({
      IdCliente: id,
      PageNumber: pageIndex.value + 1,
      PageSize: pageSize.value,
    });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

function habitacionEtiqueta(r: ReservaDTO): string {
  return habitacionDesdeObservaciones(r.observaciones) ?? '—';
}

function fmtDate(iso: string | null | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('es');
}

const pages = computed(() => Math.max(1, Math.ceil(total.value / pageSize.value)));
</script>

<template>
  <div class="mis-reservas hl-page">
    <header class="mis-reservas__head">
      <h1>Mis reservas</h1>
      <p class="mis-reservas__lede">
        Aquí aparecen las reservas asociadas a tu perfil de cliente. Si el sistema no reconoce tu identificador, puedes
        indicar el que te entregó recepción para esta sesión.
      </p>
    </header>

    <v-card class="mis-reservas__panel mb-4">
      <v-card-title>Identificación</v-card-title>
      <v-card-subtitle>Vínculo con tu cuenta de huésped</v-card-subtitle>
      <v-card-text>
        <p v-if="idClienteEfectivo != null" class="mis-reservas__status">
          Cliente activo:
          <strong>{{ idClienteEfectivo }}</strong>
          <span v-if="user.getStoredIdClienteOverride()" class="mis-reservas__badge">Guardado en este dispositivo</span>
        </p>
        <form class="mis-reservas__form" @submit.prevent="guardarIdCliente()">
          <v-text-field
            v-model.number="formCliente.idCliente"
            class="mis-reservas__field"
            label="Id cliente"
            type="number"
            variant="outlined"
          />
          <div class="mis-reservas__form-actions">
            <v-btn color="primary" type="submit" :disabled="formCliente.idCliente == null">Aplicar</v-btn>
            <v-btn variant="text" type="button" @click="limpiarOverride()">Borrar id guardado</v-btn>
          </div>
        </form>
      </v-card-text>
    </v-card>

    <v-card v-if="user.getIdCliente() == null" class="mis-reservas__empty">
      <v-card-text><p>Indica un identificador de cliente arriba para cargar tu historial.</p></v-card-text>
    </v-card>
    <div v-else-if="loading" class="mis-reservas__center">
      <v-progress-circular indeterminate />
    </div>
    <template v-else>
      <v-table class="mis-reservas__table">
        <thead>
          <tr>
            <th v-for="c in displayedColumns" :key="c">{{ c }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="r in rows" :key="r.guidReserva ?? String(r.codigoReserva)">
            <td>{{ r.codigoReserva }}</td>
            <td>{{ habitacionEtiqueta(r) }}</td>
            <td>{{ r.idSucursal }}</td>
            <td>{{ fmtDate(r.fechaInicio) }}</td>
            <td>{{ fmtDate(r.fechaFin) }}</td>
            <td>{{ (r.totalReserva ?? 0).toFixed(2) }}</td>
            <td>{{ r.estadoReserva }}</td>
          </tr>
        </tbody>
      </v-table>
      <v-pagination v-if="pages > 1" class="mt-4" :length="pages" :model-value="pageIndex + 1" @update:model-value="onPage" />
    </template>
  </div>
</template>

<style scoped src="./mis-reservas-page.scss"></style>
