// src/app/features/reservations/reservar-page.component.ts
import { DecimalPipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatRadioModule } from '@angular/material/radio';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatStepperModule, MatStepper } from '@angular/material/stepper';
import { forkJoin, of, catchError } from 'rxjs';
import type { HabitacionDTO, SucursalDTOApiResponse } from '../../shared/models';
import { ReservasService } from '../../core/services/reservas.service';
import { SucursalesService } from '../../core/services/sucursales.service';
import { UserContextService } from '../../core/services/user-context.service';
import { HabitacionesService } from '../../core/services/habitaciones.service';
import { isUuidString } from '../../shared/utils/string.util';

@Component({
  selector: 'app-reservar-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatStepperModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatRadioModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
    DecimalPipe,
  ],
  templateUrl: './reservar-page.component.html',
  styleUrl: './reservar-page.component.scss',
})
export class ReservarPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly sucursales = inject(SucursalesService);
  private readonly reservas = inject(ReservasService);
  private readonly habitaciones = inject(HabitacionesService);
  private readonly userCtx = inject(UserContextService);
  private readonly snack = inject(MatSnackBar);

  loading = true;
  sucursalGuid: string | null = null;
  sucursalNombre?: string;
  idSucursalResuelto = false;
  idClienteResuelto = false;

  habitacionesRows: HabitacionDTO[] = [];
  loadingHab = false;
  submitiendo = false;

  readonly form = this.fb.nonNullable.group({
    idCliente: this.fb.control<number | null>(null, Validators.required),
    idSucursal: this.fb.control<number | null>(null, Validators.required),
    fechaInicio: this.fb.control('', Validators.required),
    fechaFin: this.fb.control('', Validators.required),
    origenCanalReserva: this.fb.control('WEB', Validators.required),
    observaciones: this.fb.control(''),
  });

  readonly roomForm = this.fb.nonNullable.group({
    idHabitacion: this.fb.control<number | null>(null, Validators.required),
  });

  /** Pasarela simulada (no envía datos reales a ningún PSP). */
  readonly payForm = this.fb.nonNullable.group({
    titular: this.fb.control('', Validators.required),
    pan: this.fb.control('', [Validators.required, Validators.minLength(12)]),
    expira: this.fb.control('', Validators.required),
    cvv: this.fb.control('', [Validators.required, Validators.minLength(3), Validators.maxLength(4)]),
    acepto: this.fb.control(false, Validators.requiredTrue),
  });

  ngOnInit(): void {
    const guid = this.route.snapshot.paramMap.get('id') ?? '';
    if (!isUuidString(guid)) {
      this.loading = false;
      this.snack.open('Usa el sucursalGuid (UUID) en la URL.', 'Cerrar');
      return;
    }
    this.sucursalGuid = guid;
    const qp = this.route.snapshot.queryParamMap;
    const qFi = qp.get('fechaInicio');
    const qFf = qp.get('fechaFin');
    forkJoin({
      me: this.userCtx.refreshMe().pipe(catchError(() => of(null))),
      publico: this.sucursales.getPublicoBySucursalGuid(guid),
      interno: this.sucursales.getInternalByGuid(guid).pipe(catchError(() => of(null as SucursalDTOApiResponse | null))),
    }).subscribe({
      next: ({ publico, interno }) => {
        if (publico.success && publico.data) {
          this.sucursalNombre = publico.data.nombreSucursal ?? guid;
          if (publico.data.idSucursal != null) {
            this.form.patchValue({ idSucursal: publico.data.idSucursal });
            this.idSucursalResuelto = true;
          }
        }
        if (interno?.success && interno.data) {
          this.form.patchValue({ idSucursal: interno.data.idSucursal });
          this.idSucursalResuelto = true;
        }
        const idCli = this.userCtx.getIdCliente();
        if (idCli != null) {
          this.form.patchValue({ idCliente: idCli });
          this.idClienteResuelto = true;
        }
        if (qFi) {
          this.form.patchValue({ fechaInicio: qFi });
        }
        if (qFf) {
          this.form.patchValue({ fechaFin: qFf });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  /** Carga inventario de habitaciones de la sucursal y avanza el stepper si se indica. */
  loadHabitaciones(andThen?: { next: () => void }): void {
    if (!this.sucursalGuid) {
      return;
    }
    this.loadingHab = true;
    this.habitaciones.list({ SucursalGuid: this.sucursalGuid, PageSize: 100 }).subscribe({
      next: (r) => {
        this.habitacionesRows = this.filtrarHabitacionesVisibles(r.data?.data);
        this.loadingHab = false;
        andThen?.next();
      },
      error: () => {
        this.habitaciones.listPublico({ SucursalGuid: this.sucursalGuid!, PageSize: 100 }).subscribe({
          next: (r2) => {
            this.habitacionesRows = this.filtrarHabitacionesVisibles(r2.data?.data);
            this.loadingHab = false;
            andThen?.next();
          },
          error: () => {
            this.loadingHab = false;
            this.snack.open('No se pudieron cargar habitaciones para esta sucursal.', 'Cerrar');
          },
        });
      },
    });
  }

  private filtrarHabitacionesVisibles(rows: HabitacionDTO[] | null | undefined): HabitacionDTO[] {
    const list = rows ?? [];
    return list.filter(
      (h) =>
        !h.esEliminado &&
        String(h.estadoHabitacion ?? '')
          .toUpperCase()
          .indexOf('INHABI') === -1,
    );
  }

  habitacionSeleccionada(): HabitacionDTO | undefined {
    const id = this.roomForm.getRawValue().idHabitacion;
    if (id == null) {
      return undefined;
    }
    return this.habitacionesRows.find((h) => h.idHabitacion === id);
  }

  precioEstimado(): number {
    const h = this.habitacionSeleccionada();
    return h?.precioBase ?? 0;
  }

  onDatesNext(stepper: MatStepper): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.loadHabitaciones({
      next: () => stepper.next(),
    });
  }

  onRoomNext(stepper: MatStepper): void {
    if (this.roomForm.invalid || this.habitacionesRows.length === 0) {
      this.roomForm.markAllAsTouched();
      return;
    }
    stepper.next();
  }

  onPayNext(stepper: MatStepper): void {
    if (this.payForm.invalid) {
      this.payForm.markAllAsTouched();
      return;
    }
    stepper.next();
  }

  submit(): void {
    if (this.form.invalid || this.roomForm.invalid) {
      this.form.markAllAsTouched();
      this.roomForm.markAllAsTouched();
      return;
    }
    const v = this.form.getRawValue();
    const fi = v.fechaInicio;
    const ff = v.fechaFin;
    const canal = v.origenCanalReserva;
    if (fi == null || ff == null || !canal) {
      return;
    }
    const hab = this.habitacionSeleccionada();
    if (!hab) {
      this.snack.open('Selecciona una habitación.', 'Cerrar');
      return;
    }
    const num = hab.numeroHabitacion?.trim() || String(hab.idHabitacion);
    const extraLine = `[KAIROS] Habitación: ${num} (id ${hab.idHabitacion})`;
    const obsBase = v.observaciones?.trim() ?? '';
    const observaciones = [obsBase, extraLine].filter(Boolean).join('\n');

    this.submitiendo = true;
    this.reservas
      .create({
        idCliente: v.idCliente!,
        idSucursal: v.idSucursal!,
        fechaInicio: new Date(fi).toISOString(),
        fechaFin: new Date(ff).toISOString(),
        origenCanalReserva: canal,
        observaciones,
        habitaciones: [{ idHabitacion: hab.idHabitacion }],
        esWalkin: 0,
      })
      .subscribe({
        next: (res) => {
          this.submitiendo = false;
          if (res.success && res.data) {
            this.snack.open(
              `Reserva creada — habitación ${num}. Código: ${res.data.codigoReserva ?? res.data.guidReserva}`,
              'Cerrar',
              { duration: 6000 },
            );
            void this.router.navigate(['/mis-reservas']);
          } else {
            this.snack.open(res.message || 'Revisar respuesta', 'Cerrar');
          }
        },
        error: () => (this.submitiendo = false),
      });
  }
}

<div class="reserva-page hl-page">
  <header class="reserva-page__head">
    <p class="reserva-page__eyebrow">Marketplace · checkout</p>
    <h1 class="reserva-page__title">Reserva con habitación y pago simulado</h1>
    <p class="reserva-page__lede">
      Flujo en pasos: fechas → habitación en la sucursal → pasarela de demostración → confirmación. La reserva queda
      vinculada a tu <strong>id cliente</strong> y se lista en
      <a routerLink="/mis-reservas">Mis reservas</a> con el número de habitación.
    </p>
  </header>

  @if (loading) {
    <div class="reserva-center"><mat-spinner diameter="44" aria-label="Cargando" /></div>
  } @else if (!sucursalGuid) {
    <mat-card class="reserva-card">
      <mat-card-content>Ruta inválida: falta UUID de sucursal.</mat-card-content>
    </mat-card>
  } @else {
    <mat-card class="reserva-card reserva-card--wide">
      <mat-card-header>
        <mat-card-title>{{ sucursalNombre ?? 'Sucursal' }}</mat-card-title>
        <mat-card-subtitle>Identificadores internos se completan cuando el API lo permite.</mat-card-subtitle>
      </mat-card-header>
      <mat-card-content>
        <mat-stepper linear #stepper="matStepper">
          <mat-step [stepControl]="form" label="Estancia">
            <form [formGroup]="form" class="reserva-form">
              <div class="reserva-form__ids">
                <mat-form-field appearance="outline" class="reserva-form__field">
                  <mat-label>Id cliente</mat-label>
                  <input matInput type="number" formControlName="idCliente" />
                  @if (idClienteResuelto) {
                    <mat-hint>Vinculado a tu sesión</mat-hint>
                  }
                </mat-form-field>
                <mat-form-field appearance="outline" class="reserva-form__field">
                  <mat-label>Id sucursal</mat-label>
                  <input matInput type="number" formControlName="idSucursal" />
                  @if (idSucursalResuelto) {
                    <mat-hint>Resuelto desde la sucursal</mat-hint>
                  }
                </mat-form-field>
              </div>
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Fecha inicio</mat-label>
                <input matInput type="datetime-local" formControlName="fechaInicio" />
              </mat-form-field>
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Fecha fin</mat-label>
                <input matInput type="datetime-local" formControlName="fechaFin" />
              </mat-form-field>
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Canal</mat-label>
                <input matInput formControlName="origenCanalReserva" />
              </mat-form-field>
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Observaciones</mat-label>
                <textarea matInput rows="2" formControlName="observaciones"></textarea>
              </mat-form-field>
              <div class="reserva-form__actions">
                <button mat-flat-button color="primary" type="button" (click)="onDatesNext(stepper)">
                  Continuar a habitación
                </button>
              </div>
            </form>
          </mat-step>

          <mat-step [stepControl]="roomForm" label="Habitación">
            @if (loadingHab) {
              <div class="reserva-center"><mat-spinner diameter="40" /></div>
            } @else if (habitacionesRows.length === 0) {
              <p class="reserva-note">No hay habitaciones disponibles en el catálogo para esta sucursal.</p>
              <button mat-button type="button" matStepperPrevious>Volver</button>
            } @else {
              <form [formGroup]="roomForm" class="reserva-form">
                <mat-radio-group formControlName="idHabitacion" class="hab-grid">
                  @for (h of habitacionesRows; track h.habitacionGuid) {
                    <mat-radio-button class="hab-option" [value]="h.idHabitacion">
                      <span class="hab-option__title"
                        >Habitación {{ h.numeroHabitacion ?? h.idHabitacion }}</span
                      >
                      <span class="hab-option__meta"
                        >Cap. {{ h.capacidadHabitacion }} · desde {{ h.precioBase | number: '1.2-2' }}</span
                      >
                    </mat-radio-button>
                  }
                </mat-radio-group>
                <div class="reserva-form__actions">
                  <button mat-button type="button" matStepperPrevious>Volver</button>
                  <button mat-flat-button color="primary" type="button" (click)="onRoomNext(stepper)">
                    Ir a pago simulado
                  </button>
                </div>
              </form>
            }
          </mat-step>

          <mat-step [stepControl]="payForm" label="Pago (simulado)">
            <p class="reserva-note">
              Datos ficticios: no se procesa una tarjeta real. Sirve para demostrar el cierre del marketplace.
            </p>
            <form [formGroup]="payForm" class="reserva-form">
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Titular de la tarjeta</mat-label>
                <input matInput formControlName="titular" autocomplete="off" />
              </mat-form-field>
              <mat-form-field appearance="outline" class="reserva-form__field">
                <mat-label>Número de tarjeta</mat-label>
                <input matInput formControlName="pan" placeholder="0000 0000 0000 0000" autocomplete="off" />
              </mat-form-field>
              <div class="reserva-form__ids">
                <mat-form-field appearance="outline" class="reserva-form__field">
                  <mat-label>Vencimiento (MM/AA)</mat-label>
                  <input matInput formControlName="expira" placeholder="12/28" autocomplete="off" />
                </mat-form-field>
                <mat-form-field appearance="outline" class="reserva-form__field">
                  <mat-label>CVV</mat-label>
                  <input matInput type="password" formControlName="cvv" autocomplete="off" />
                </mat-form-field>
              </div>
              <p class="reserva-pay-total">
                Total estimado (precio base habitación):
                <strong>{{ precioEstimado() | number: '1.2-2' }}</strong>
              </p>
              <mat-checkbox formControlName="acepto" class="reserva-check">
                Acepto que simulo el cargo para efectos académicos / demo
              </mat-checkbox>
              <div class="reserva-form__actions">
                <button mat-button type="button" matStepperPrevious>Volver</button>
                <button mat-stroked-button color="primary" type="button" (click)="onPayNext(stepper)">
                  Marcar pago como aprobado
                </button>
              </div>
            </form>
          </mat-step>

          <mat-step label="Confirmar">
            <div class="reserva-summary">
              <p>
                <strong>Habitación:</strong>
                {{ habitacionSeleccionada()?.numeroHabitacion ?? habitacionSeleccionada()?.idHabitacion }}
              </p>
              <p>
                <strong>Cliente:</strong>
                {{ form.getRawValue().idCliente }} · <strong>Sucursal:</strong>
                {{ form.getRawValue().idSucursal }}
              </p>
              <p>
                <strong>Estancia:</strong>
                {{ form.getRawValue().fechaInicio }} → {{ form.getRawValue().fechaFin }}
              </p>
            </div>
            <div class="reserva-form__actions">
              <button mat-button type="button" matStepperPrevious>Volver</button>
              <button
                mat-flat-button
                color="primary"
                type="button"
                (click)="submit()"
                [disabled]="submitiendo || form.invalid || roomForm.invalid"
              >
                @if (submitiendo) {
                  Enviando…
                } @else {
                  Confirmar reserva en el sistema
                }
              </button>
            </div>
          </mat-step>
        </mat-stepper>
      </mat-card-content>
    </mat-card>
  }
</div>

// src/views/reservations/ReservarPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { RouterLink, useRoute, useRouter } from 'vue-router';
import { habitacionesList, habitacionesListPublico } from '@/services/habitaciones';
import { reservasCreate } from '@/services/reservas';
import { sucursalesGetInternalByGuid, sucursalesGetPublicoByGuid } from '@/services/sucursales';
import { useUiStore } from '@/stores/ui';
import { useUserContextStore } from '@/stores/userContext';
import { isUuidString } from '@/utils/string.util';
import type { HabitacionDTO } from '@/models';

const route = useRoute();
const router = useRouter();
const ui = useUiStore();
const userCtx = useUserContextStore();

const loading = ref(true);
const sucursalGuid = ref<string | null>(null);
const sucursalNombre = ref('');
const idSucursalResuelto = ref(false);
const idClienteResuelto = ref(false);
const habitacionesRows = ref<HabitacionDTO[]>([]);
const loadingHab = ref(false);
const submitiendo = ref(false);
const step = ref(1);

const form = ref({
  idCliente: null as number | null,
  idSucursal: null as number | null,
  fechaInicio: '',
  fechaFin: '',
  origenCanalReserva: 'WEB',
  observaciones: '',
});
const roomForm = ref({ idHabitacion: null as number | null });
const payForm = ref({
  titular: '',
  pan: '',
  expira: '',
  cvv: '',
  acepto: false,
});

function filtrarHabitacionesVisibles(rows: HabitacionDTO[] | null | undefined): HabitacionDTO[] {
  const list = rows ?? [];
  return list.filter(
    (h) =>
      !h.esEliminado &&
      String(h.estadoHabitacion ?? '')
        .toUpperCase()
        .indexOf('INHABI') === -1,
  );
}

const habitacionSeleccionada = computed(() => {
  const id = roomForm.value.idHabitacion;
  if (id == null) return undefined;
  return habitacionesRows.value.find((h) => h.idHabitacion === id);
});

const precioEstimado = computed(() => habitacionSeleccionada.value?.precioBase ?? 0);

async function loadHabitaciones(): Promise<void> {
  if (!sucursalGuid.value) return;
  loadingHab.value = true;
  try {
    const r = await habitacionesList({ SucursalGuid: sucursalGuid.value, PageSize: 100 });
    habitacionesRows.value = filtrarHabitacionesVisibles(r.data?.data);
  } catch {
    try {
      const r2 = await habitacionesListPublico({ SucursalGuid: sucursalGuid.value!, PageSize: 100 });
      habitacionesRows.value = filtrarHabitacionesVisibles(r2.data?.data);
    } catch {
      ui.showSnack('No se pudieron cargar habitaciones para esta sucursal.', 6000);
    }
  } finally {
    loadingHab.value = false;
  }
}

function onDatesNext(): void {
  if (!form.value.idCliente || !form.value.idSucursal || !form.value.fechaInicio || !form.value.fechaFin) {
    ui.showSnack('Completa fechas e identificadores.', 4000);
    return;
  }
  void loadHabitaciones().then(() => {
    step.value = 2;
  });
}

function onRoomNext(): void {
  if (roomForm.value.idHabitacion == null || habitacionesRows.value.length === 0) {
    ui.showSnack('Selecciona una habitación.', 4000);
    return;
  }
  step.value = 3;
}

function onPayNext(): void {
  const p = payForm.value;
  if (!p.titular || !p.pan || p.pan.length < 12 || !p.expira || !p.cvv || !p.acepto) {
    ui.showSnack('Completa los datos de pago simulado.', 4000);
    return;
  }
  step.value = 4;
}

async function submit(): Promise<void> {
  const v = form.value;
  const hab = habitacionSeleccionada.value;
  if (!hab) {
    ui.showSnack('Selecciona una habitación.', 4000);
    return;
  }
  const num = hab.numeroHabitacion?.trim() || String(hab.idHabitacion);
  const extraLine = `[KAIROS] Habitación: ${num} (id ${hab.idHabitacion})`;
  const obsBase = v.observaciones?.trim() ?? '';
  const observaciones = [obsBase, extraLine].filter(Boolean).join('\n');

  submitiendo.value = true;
  try {
    const res = await reservasCreate({
      idCliente: v.idCliente!,
      idSucursal: v.idSucursal!,
      fechaInicio: new Date(v.fechaInicio).toISOString(),
      fechaFin: new Date(v.fechaFin).toISOString(),
      origenCanalReserva: v.origenCanalReserva,
      observaciones,
      habitaciones: [{ idHabitacion: hab.idHabitacion }],
      esWalkin: 0,
    });
    if (res.success && res.data) {
      ui.showSnack(
        `Reserva creada — habitación ${num}. Código: ${res.data.codigoReserva ?? res.data.guidReserva}`,
        6000,
      );
      void router.push('/mis-reservas');
    } else {
      ui.showSnack(res.message || 'Revisar respuesta', 6000);
    }
  } finally {
    submitiendo.value = false;
  }
}

onMounted(async () => {
  const guid = String(route.params.id ?? '');
  if (!isUuidString(guid)) {
    loading.value = false;
    ui.showSnack('Usa el sucursalGuid (UUID) en la URL.', 6000);
    return;
  }
  sucursalGuid.value = guid;
  await userCtx.refreshMe();
  const qp = route.query;
  const qFi = typeof qp.fechaInicio === 'string' ? qp.fechaInicio : null;
  const qFf = typeof qp.fechaFin === 'string' ? qp.fechaFin : null;

  const [publico, interno] = await Promise.all([
    sucursalesGetPublicoByGuid(guid),
    sucursalesGetInternalByGuid(guid).catch(() => null),
  ]);

  if (publico.success && publico.data) {
    sucursalNombre.value = publico.data.nombreSucursal ?? guid;
    if (publico.data.idSucursal != null) {
      form.value.idSucursal = publico.data.idSucursal;
      idSucursalResuelto.value = true;
    }
  }
  if (interno?.success && interno.data) {
    form.value.idSucursal = interno.data.idSucursal;
    idSucursalResuelto.value = true;
  }
  const idCli = userCtx.getIdCliente();
  if (idCli != null) {
    form.value.idCliente = idCli;
    idClienteResuelto.value = true;
  }
  if (qFi) form.value.fechaInicio = qFi;
  if (qFf) form.value.fechaFin = qFf;
  loading.value = false;
});
</script>

<template>
  <div class="reserva-page hl-page">
    <header class="reserva-page__head">
      <p class="reserva-page__eyebrow">Marketplace · checkout</p>
      <h1 class="reserva-page__title">Reserva con habitación y pago simulado</h1>
      <p class="reserva-page__lede">
        Flujo en pasos: fechas → habitación en la sucursal → pasarela de demostración → confirmación. La reserva queda
        vinculada a tu <strong>id cliente</strong> y se lista en
        <RouterLink to="/mis-reservas">Mis reservas</RouterLink> con el número de habitación.
      </p>
    </header>

    <div v-if="loading" class="reserva-center">
      <v-progress-circular indeterminate />
    </div>
    <v-card v-else-if="!sucursalGuid" class="reserva-card pa-4">Ruta inválida: falta UUID de sucursal.</v-card>
    <v-card v-else class="reserva-card reserva-card--wide">
      <v-card-title>{{ sucursalNombre || 'Sucursal' }}</v-card-title>
      <v-card-subtitle>Identificadores internos se completan cuando el API lo permite.</v-card-subtitle>
      <v-card-text>
        <v-stepper v-model="step" class="bg-transparent elevation-0" flat>
          <v-stepper-header>
            <v-stepper-item :value="1" title="Estancia" />
            <v-stepper-item :value="2" title="Habitación" />
            <v-stepper-item :value="3" title="Pago (simulado)" />
            <v-stepper-item :value="4" title="Confirmar" />
          </v-stepper-header>
          <v-stepper-window>
            <v-stepper-window-item :value="1">
              <div class="reserva-form">
                <div class="reserva-form__ids">
                  <v-text-field
                    v-model.number="form.idCliente"
                    label="Id cliente"
                    type="number"
                    variant="outlined"
                    :hint="idClienteResuelto ? 'Vinculado a tu sesión' : undefined"
                    persistent-hint
                  />
                  <v-text-field
                    v-model.number="form.idSucursal"
                    label="Id sucursal"
                    type="number"
                    variant="outlined"
                    :hint="idSucursalResuelto ? 'Resuelto desde la sucursal' : undefined"
                    persistent-hint
                  />
                </div>
                <v-text-field v-model="form.fechaInicio" label="Fecha inicio" type="datetime-local" variant="outlined" />
                <v-text-field v-model="form.fechaFin" label="Fecha fin" type="datetime-local" variant="outlined" />
                <v-text-field v-model="form.origenCanalReserva" label="Canal" variant="outlined" />
                <v-textarea v-model="form.observaciones" label="Observaciones" rows="2" variant="outlined" />
                <div class="reserva-form__actions">
                  <v-btn color="primary" type="button" @click="onDatesNext">Continuar a habitación</v-btn>
                </div>
              </div>
            </v-stepper-window-item>
            <v-stepper-window-item :value="2">
              <div v-if="loadingHab" class="reserva-center">
                <v-progress-circular indeterminate />
              </div>
              <template v-else-if="habitacionesRows.length === 0">
                <p class="reserva-note">No hay habitaciones disponibles en el catálogo para esta sucursal.</p>
                <v-btn variant="text" @click="step = 1">Volver</v-btn>
              </template>
              <template v-else>
                <v-radio-group v-model="roomForm.idHabitacion" class="hab-grid">
                  <v-radio
                    v-for="h in habitacionesRows"
                    :key="h.habitacionGuid"
                    :label="`Habitación ${h.numeroHabitacion ?? h.idHabitacion} · Cap. ${h.capacidadHabitacion} · desde ${(h.precioBase ?? 0).toFixed(2)}`"
                    :value="h.idHabitacion"
                  />
                </v-radio-group>
                <div class="reserva-form__actions">
                  <v-btn variant="text" @click="step = 1">Volver</v-btn>
                  <v-btn color="primary" type="button" @click="onRoomNext">Ir a pago simulado</v-btn>
                </div>
              </template>
            </v-stepper-window-item>
            <v-stepper-window-item :value="3">
              <p class="reserva-note">
                Datos ficticios: no se procesa una tarjeta real. Sirve para demostrar el cierre del marketplace.
              </p>
              <v-text-field v-model="payForm.titular" label="Titular de la tarjeta" variant="outlined" autocomplete="off" />
              <v-text-field
                v-model="payForm.pan"
                label="Número de tarjeta"
                variant="outlined"
                placeholder="0000 0000 0000 0000"
                autocomplete="off"
              />
              <div class="reserva-form__ids">
                <v-text-field v-model="payForm.expira" label="Vencimiento (MM/AA)" variant="outlined" placeholder="12/28" />
                <v-text-field v-model="payForm.cvv" label="CVV" type="password" variant="outlined" autocomplete="off" />
              </div>
              <p class="reserva-pay-total">Total estimado (precio base habitación): <strong>{{ precioEstimado.toFixed(2) }}</strong></p>
              <v-checkbox v-model="payForm.acepto" label="Acepto que simulo el cargo para efectos académicos / demo" />
              <div class="reserva-form__actions">
                <v-btn variant="text" @click="step = 2">Volver</v-btn>
                <v-btn color="primary" variant="outlined" type="button" @click="onPayNext">Marcar pago como aprobado</v-btn>
              </div>
            </v-stepper-window-item>
            <v-stepper-window-item :value="4">
              <div class="reserva-summary">
                <p>
                  <strong>Habitación:</strong>
                  {{ habitacionSeleccionada?.numeroHabitacion ?? habitacionSeleccionada?.idHabitacion }}
                </p>
                <p>
                  <strong>Cliente:</strong> {{ form.idCliente }} · <strong>Sucursal:</strong> {{ form.idSucursal }}
                </p>
                <p>
                  <strong>Estancia:</strong> {{ form.fechaInicio }} → {{ form.fechaFin }}
                </p>
              </div>
              <div class="reserva-form__actions">
                <v-btn variant="text" @click="step = 3">Volver</v-btn>
                <v-btn
                  color="primary"
                  type="button"
                  :disabled="submitiendo"
                  @click="submit()"
                >
                  {{ submitiendo ? 'Enviando…' : 'Confirmar reserva en el sistema' }}
                </v-btn>
              </div>
            </v-stepper-window-item>
          </v-stepper-window>
        </v-stepper>
      </v-card-text>
    </v-card>
  </div>
</template>

<style scoped src="./reservar-page.scss"></style>
