// src/views/admin/AdminSucursalEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { sucursalesCreate, sucursalesGetInternalByGuid, sucursalesUpdate } from '@/services/sucursales';
import { useUiStore } from '@/stores/ui';
import { isUuidString } from '@/utils/string.util';
import type { SucursalDTO, SucursalUpsertRequest } from '@/models';

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const isCreate = ref(false);
const sucursalGuid = ref<string | undefined>();
const loading = ref(true);
const guardando = ref(false);

const form = reactive({
  codigoSucursal: '',
  nombreSucursal: '',
  descripcionSucursal: '',
  descripcionCorta: '',
  tipoAlojamiento: 'Hotel',
  estrellas: null as number | null,
  categoriaViaje: '',
  pais: '',
  provincia: '',
  ciudad: '',
  ubicacion: '',
  direccion: '',
  codigoPostal: '',
  telefono: '',
  correo: '',
  latitud: null as number | null,
  longitud: null as number | null,
  horaCheckin: '15:00',
  horaCheckout: '11:00',
  checkinAnticipado: 0,
  checkoutTardio: 0,
  aceptaNinos: true,
  edadMinimaHuesped: null as number | null,
  permiteMascotas: false,
  sePermiteFumar: false,
  estadoSucursal: 'ACTIVO',
});

function patchFormFromDto(s: SucursalDTO): void {
  form.codigoSucursal = s.codigoSucursal ?? '';
  form.nombreSucursal = s.nombreSucursal ?? '';
  form.descripcionSucursal = s.descripcionSucursal ?? '';
  form.descripcionCorta = s.descripcionCorta ?? '';
  form.tipoAlojamiento = s.tipoAlojamiento ?? 'Hotel';
  form.estrellas = s.estrellas ?? null;
  form.categoriaViaje = s.categoriaViaje ?? '';
  form.pais = s.pais ?? '';
  form.provincia = s.provincia ?? '';
  form.ciudad = s.ciudad ?? '';
  form.ubicacion = s.ubicacion ?? s.ciudad ?? '';
  form.direccion = s.direccion ?? '';
  form.codigoPostal = s.codigoPostal ?? '';
  form.telefono = s.telefono ?? '';
  form.correo = s.correo ?? '';
  form.latitud = s.latitud ?? null;
  form.longitud = s.longitud ?? null;
  form.horaCheckin = s.horaCheckin ?? '15:00';
  form.horaCheckout = s.horaCheckout ?? '11:00';
  form.checkinAnticipado = s.checkinAnticipado ?? 0;
  form.checkoutTardio = s.checkoutTardio ?? 0;
  form.aceptaNinos = (s.aceptaNinos ?? 1) === 1;
  form.edadMinimaHuesped = s.edadMinimaHuesped ?? null;
  form.permiteMascotas = (s.permiteMascotas ?? 0) === 1;
  form.sePermiteFumar = (s.sePermiteFumar ?? 0) === 1;
  form.estadoSucursal = s.estadoSucursal ?? 'ACTIVO';
}

function buildBody(): SucursalUpsertRequest | null {
  const v = form;
  const codigo = v.codigoSucursal.trim();
  const nombre = v.nombreSucursal.trim();
  const pais = v.pais.trim();
  const ciudad = v.ciudad.trim();
  let ubicacion = v.ubicacion.trim();
  const direccion = v.direccion.trim();
  const telefono = v.telefono.trim();
  const correo = v.correo.trim();
  if (!codigo || !nombre || !pais || !ciudad || !direccion || !telefono || !correo) {
    ui.showSnack('Obligatorios: código, nombre, país, ciudad, dirección, teléfono y correo.', 6000);
    return null;
  }
  if (!ubicacion) ubicacion = ciudad;
  return {
    codigoSucursal: codigo,
    nombreSucursal: nombre,
    descripcionSucursal: v.descripcionSucursal.trim() || null,
    descripcionCorta: v.descripcionCorta.trim() || null,
    tipoAlojamiento: v.tipoAlojamiento.trim() || null,
    estrellas: v.estrellas,
    categoriaViaje: v.categoriaViaje.trim() || null,
    pais,
    provincia: v.provincia.trim() || null,
    ciudad,
    ubicacion,
    direccion,
    codigoPostal: v.codigoPostal.trim() || null,
    telefono,
    correo,
    latitud: v.latitud,
    longitud: v.longitud,
    horaCheckin: v.horaCheckin.trim() || null,
    horaCheckout: v.horaCheckout.trim() || null,
    checkinAnticipado: Number(v.checkinAnticipado) || 0,
    checkoutTardio: Number(v.checkoutTardio) || 0,
    aceptaNinos: v.aceptaNinos ? 1 : 0,
    edadMinimaHuesped: v.edadMinimaHuesped,
    permiteMascotas: v.permiteMascotas ? 1 : 0,
    sePermiteFumar: v.sePermiteFumar ? 1 : 0,
    estadoSucursal: v.estadoSucursal.trim() || null,
  };
}

function copiarCiudadAUbicacion(): void {
  const c = form.ciudad.trim();
  if (c) form.ubicacion = c;
}

onMounted(async () => {
  if (route.path.endsWith('/nuevo')) {
    isCreate.value = true;
    loading.value = false;
    return;
  }
  const id = String(route.params.guid ?? '');
  if (!isUuidString(id)) {
    ui.showSnack('GUID de sucursal inválido', 4000);
    void router.push('/admin/sucursales');
    return;
  }
  sucursalGuid.value = id;
  try {
    const res = await sucursalesGetInternalByGuid(id);
    if (res.success && res.data) {
      patchFormFromDto(res.data);
    }
  } finally {
    loading.value = false;
  }
});

async function guardar(): Promise<void> {
  const body = buildBody();
  if (!body) return;
  guardando.value = true;
  try {
    if (isCreate.value) {
      const res = await sucursalesCreate(body);
      if (res.success && res.data) {
        ui.showSnack(`Sucursal creada (id ${res.data.idSucursal})`, 5000);
        void router.push('/admin/sucursales');
      } else {
        ui.showSnack(res.message || 'No se pudo crear', 6000);
      }
    } else if (sucursalGuid.value) {
      const res = await sucursalesUpdate(sucursalGuid.value, body);
      if (res.success) {
        ui.showSnack('Sucursal actualizada', 4000);
        void router.push('/admin/sucursales');
      } else {
        ui.showSnack(res.message || 'No se pudo actualizar', 6000);
      }
    }
  } finally {
    guardando.value = false;
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <div v-else>
    <h1 class="mb-2">{{ isCreate ? 'Nueva sucursal' : 'Editar sucursal' }}</h1>
    <p class="text-medium-emphasis mb-4">
      Obligatorios según API: código, nombre, país, ciudad, ubicación, dirección, teléfono y correo.
    </p>
    <v-card>
      <v-card-text class="d-flex flex-column gap-2">
        <v-text-field v-model="form.codigoSucursal" label="Código sucursal" variant="outlined" />
        <v-text-field v-model="form.nombreSucursal" label="Nombre" variant="outlined" />
        <v-textarea v-model="form.descripcionSucursal" label="Descripción" variant="outlined" />
        <v-text-field v-model="form.descripcionCorta" label="Descripción corta" variant="outlined" />
        <v-text-field v-model="form.tipoAlojamiento" label="Tipo alojamiento" variant="outlined" />
      <v-text-field v-model.number="form.estrellas" label="Estrellas" type="number" variant="outlined" />
        <v-text-field v-model="form.categoriaViaje" label="Categoría viaje" variant="outlined" />
        <v-divider class="my-2" />
        <v-text-field v-model="form.pais" label="País" variant="outlined" />
        <v-text-field v-model="form.provincia" label="Provincia" variant="outlined" />
        <v-text-field v-model="form.ciudad" label="Ciudad" variant="outlined" />
        <div class="d-flex gap-2 align-center flex-wrap">
          <v-text-field v-model="form.ubicacion" label="Ubicación (texto)" variant="outlined" class="flex-grow-1" />
          <v-btn variant="outlined" @click="copiarCiudadAUbicacion">Igual que ciudad</v-btn>
        </div>
        <v-text-field v-model="form.direccion" label="Dirección" variant="outlined" />
        <v-text-field v-model="form.codigoPostal" label="Código postal" variant="outlined" />
        <v-text-field v-model.number="form.latitud" label="Latitud" type="number" step="any" variant="outlined" />
        <v-text-field v-model.number="form.longitud" label="Longitud" type="number" step="any" variant="outlined" />
        <v-text-field v-model="form.telefono" label="Teléfono" variant="outlined" />
        <v-text-field v-model="form.correo" label="Correo" type="email" variant="outlined" />
        <v-text-field v-model="form.horaCheckin" label="Hora check-in" variant="outlined" />
        <v-text-field v-model="form.horaCheckout" label="Hora check-out" variant="outlined" />
        <v-text-field v-model.number="form.checkinAnticipado" label="Check-in anticipado" type="number" variant="outlined" />
        <v-text-field v-model.number="form.checkoutTardio" label="Check-out tardío" type="number" variant="outlined" />
        <v-text-field v-model.number="form.edadMinimaHuesped" label="Edad mínima huésped" type="number" variant="outlined" />
        <v-text-field v-model="form.estadoSucursal" label="Estado operativo" variant="outlined" />
        <v-checkbox v-model="form.aceptaNinos" label="Acepta niños" />
        <v-checkbox v-model="form.permiteMascotas" label="Permite mascotas" />
        <v-checkbox v-model="form.sePermiteFumar" label="Se permite fumar" />
        <v-btn color="primary" :loading="guardando" @click="guardar">Guardar</v-btn>
        <v-btn variant="text" to="/admin/sucursales">Volver</v-btn>
      </v-card-text>
    </v-card>
  </div>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
.mb-2 {
  margin-bottom: 0.5rem;
}
.mb-4 {
  margin-bottom: 1rem;
}
</style>

// src/app/features/admin/admin-sucursal-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { SucursalesService } from '../../core/services/sucursales.service';
import type { SucursalUpsertRequest, SucursalDTO } from '../../shared/models';
import { isUuidString } from '../../shared/utils/string.util';

@Component({
  selector: 'app-admin-sucursal-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatCheckboxModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-sucursal-edit-page.component.html',
  styleUrl: './admin-sucursal-edit-page.component.scss',
})
export class AdminSucursalEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly api = inject(SucursalesService);
  private readonly snack = inject(MatSnackBar);

  isCreate = false;
  sucursalGuid?: string;
  loading = true;
  guardando = false;

  readonly form = this.fb.nonNullable.group({
    codigoSucursal: this.fb.control('', Validators.required),
    nombreSucursal: this.fb.control('', Validators.required),
    descripcionSucursal: this.fb.control(''),
    descripcionCorta: this.fb.control(''),
    tipoAlojamiento: this.fb.control('Hotel'),
    estrellas: this.fb.control<number | null>(null),
    categoriaViaje: this.fb.control(''),
    pais: this.fb.control('', Validators.required),
    provincia: this.fb.control(''),
    ciudad: this.fb.control('', Validators.required),
    ubicacion: this.fb.control('', Validators.required),
    direccion: this.fb.control('', Validators.required),
    codigoPostal: this.fb.control(''),
    telefono: this.fb.control('', Validators.required),
    correo: this.fb.control('', [Validators.required, Validators.email]),
    latitud: this.fb.control<number | null>(null),
    longitud: this.fb.control<number | null>(null),
    horaCheckin: this.fb.control('15:00'),
    horaCheckout: this.fb.control('11:00'),
    checkinAnticipado: this.fb.control(0, Validators.min(0)),
    checkoutTardio: this.fb.control(0, Validators.min(0)),
    aceptaNinos: this.fb.control(true),
    edadMinimaHuesped: this.fb.control<number | null>(null),
    permiteMascotas: this.fb.control(false),
    sePermiteFumar: this.fb.control(false),
    estadoSucursal: this.fb.control('ACTIVO'),
  });

  ngOnInit(): void {
    const path = this.route.snapshot.routeConfig?.path ?? '';
    if (path === 'nuevo') {
      this.isCreate = true;
      this.loading = false;
      return;
    }
    const id = this.route.snapshot.paramMap.get('guid') ?? '';
    if (!isUuidString(id)) {
      this.snack.open('GUID de sucursal inválido', 'Cerrar');
      void this.router.navigate(['/admin/sucursales']);
      return;
    }
    this.sucursalGuid = id;
    this.api.getInternalByGuid(id).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          this.patchFormFromDto(res.data);
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  private patchFormFromDto(s: SucursalDTO): void {
    this.form.patchValue({
      codigoSucursal: s.codigoSucursal ?? '',
      nombreSucursal: s.nombreSucursal ?? '',
      descripcionSucursal: s.descripcionSucursal ?? '',
      descripcionCorta: s.descripcionCorta ?? '',
      tipoAlojamiento: s.tipoAlojamiento ?? 'Hotel',
      estrellas: s.estrellas ?? null,
      categoriaViaje: s.categoriaViaje ?? '',
      pais: s.pais ?? '',
      provincia: s.provincia ?? '',
      ciudad: s.ciudad ?? '',
      ubicacion: s.ubicacion ?? s.ciudad ?? '',
      direccion: s.direccion ?? '',
      codigoPostal: s.codigoPostal ?? '',
      telefono: s.telefono ?? '',
      correo: s.correo ?? '',
      latitud: s.latitud ?? null,
      longitud: s.longitud ?? null,
      horaCheckin: s.horaCheckin ?? '15:00',
      horaCheckout: s.horaCheckout ?? '11:00',
      checkinAnticipado: s.checkinAnticipado ?? 0,
      checkoutTardio: s.checkoutTardio ?? 0,
      aceptaNinos: (s.aceptaNinos ?? 1) === 1,
      edadMinimaHuesped: s.edadMinimaHuesped ?? null,
      permiteMascotas: (s.permiteMascotas ?? 0) === 1,
      sePermiteFumar: (s.sePermiteFumar ?? 0) === 1,
      estadoSucursal: s.estadoSucursal ?? 'ACTIVO',
    });
  }

  private buildBody(): SucursalUpsertRequest | null {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return null;
    }
    const v = this.form.getRawValue();
    const codigo = (v.codigoSucursal ?? '').trim();
    const nombre = (v.nombreSucursal ?? '').trim();
    const pais = (v.pais ?? '').trim();
    const ciudad = (v.ciudad ?? '').trim();
    let ubicacion = (v.ubicacion ?? '').trim();
    const direccion = (v.direccion ?? '').trim();
    const telefono = (v.telefono ?? '').trim();
    const correo = (v.correo ?? '').trim();
    if (!codigo || !nombre || !pais || !ciudad || !direccion || !telefono || !correo) {
      return null;
    }
    if (!ubicacion) {
      ubicacion = ciudad;
    }
    return {
      codigoSucursal: codigo,
      nombreSucursal: nombre,
      descripcionSucursal: (v.descripcionSucursal ?? '').trim() || null,
      descripcionCorta: (v.descripcionCorta ?? '').trim() || null,
      tipoAlojamiento: (v.tipoAlojamiento ?? '').trim() || null,
      estrellas: v.estrellas,
      categoriaViaje: (v.categoriaViaje ?? '').trim() || null,
      pais,
      provincia: (v.provincia ?? '').trim() || null,
      ciudad,
      ubicacion,
      direccion,
      codigoPostal: (v.codigoPostal ?? '').trim() || null,
      telefono,
      correo,
      latitud: v.latitud,
      longitud: v.longitud,
      horaCheckin: (v.horaCheckin ?? '').trim() || null,
      horaCheckout: (v.horaCheckout ?? '').trim() || null,
      checkinAnticipado: Number(v.checkinAnticipado) || 0,
      checkoutTardio: Number(v.checkoutTardio) || 0,
      aceptaNinos: v.aceptaNinos ? 1 : 0,
      edadMinimaHuesped: v.edadMinimaHuesped,
      permiteMascotas: v.permiteMascotas ? 1 : 0,
      sePermiteFumar: v.sePermiteFumar ? 1 : 0,
      estadoSucursal: (v.estadoSucursal ?? '').trim() || null,
    };
  }

  copiarCiudadAUbicacion(): void {
    const c = this.form.get('ciudad')?.value?.trim();
    if (c) {
      this.form.patchValue({ ubicacion: c });
    }
  }

  guardar(): void {
    const body = this.buildBody();
    if (!body) {
      return;
    }
    this.guardando = true;
    if (this.isCreate) {
      this.api.create(body).subscribe({
        next: (res) => {
          this.guardando = false;
          if (res.success && res.data) {
            this.snack.open(`Sucursal creada (id ${res.data.idSucursal})`, 'Cerrar', { duration: 5000 });
            void this.router.navigate(['/admin/sucursales']);
          } else {
            this.snack.open(res.message || 'No se pudo crear', 'Cerrar');
          }
        },
        error: () => (this.guardando = false),
      });
    } else if (this.sucursalGuid) {
      this.api.update(this.sucursalGuid, body).subscribe({
        next: (res) => {
          this.guardando = false;
          if (res.success) {
            this.snack.open('Sucursal actualizada', 'Cerrar', { duration: 4000 });
            void this.router.navigate(['/admin/sucursales']);
          } else {
            this.snack.open(res.message || 'No se pudo actualizar', 'Cerrar');
          }
        },
        error: () => (this.guardando = false),
      });
    }
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="44" /></div>
} @else {
  <div class="page-head">
    <h1>{{ isCreate ? 'Nueva sucursal' : 'Editar sucursal' }}</h1>
    <p class="lede">
      Campos obligatorios según el API: código, nombre, país, ciudad, ubicación, dirección, teléfono y correo. La
      sucursal podrá aparecer en el marketplace cuando el backend la publique en búsquedas.
    </p>
  </div>

  <mat-card>
    <mat-card-content>
      <form [formGroup]="form" class="grid-form" (ngSubmit)="guardar()">
        <h3 class="section-title">Identificación</h3>
        <mat-form-field appearance="outline">
          <mat-label>Código sucursal</mat-label>
          <input matInput formControlName="codigoSucursal" placeholder="ej. KRS-QTO-01" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="span-2">
          <mat-label>Nombre</mat-label>
          <input matInput formControlName="nombreSucursal" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="2" formControlName="descripcionSucursal"></textarea>
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Descripción corta</mat-label>
          <input matInput formControlName="descripcionCorta" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Tipo alojamiento</mat-label>
          <input matInput formControlName="tipoAlojamiento" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Estrellas</mat-label>
          <input matInput type="number" formControlName="estrellas" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Categoría viaje</mat-label>
          <input matInput formControlName="categoriaViaje" />
        </mat-form-field>

        <h3 class="section-title full">Ubicación</h3>
        <mat-form-field appearance="outline">
          <mat-label>País</mat-label>
          <input matInput formControlName="pais" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Provincia</mat-label>
          <input matInput formControlName="provincia" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Ciudad</mat-label>
          <input matInput formControlName="ciudad" />
        </mat-form-field>
        <div class="ubicacion-row full">
          <mat-form-field appearance="outline" class="ubicacion-row__field">
            <mat-label>Ubicación (texto)</mat-label>
            <input matInput formControlName="ubicacion" />
          </mat-form-field>
          <button mat-stroked-button type="button" (click)="copiarCiudadAUbicacion()">Igual que ciudad</button>
        </div>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Dirección</mat-label>
          <input matInput formControlName="direccion" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Código postal</mat-label>
          <input matInput formControlName="codigoPostal" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Latitud</mat-label>
          <input matInput type="number" step="any" formControlName="latitud" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Longitud</mat-label>
          <input matInput type="number" step="any" formControlName="longitud" />
        </mat-form-field>

        <h3 class="section-title full">Contacto</h3>
        <mat-form-field appearance="outline">
          <mat-label>Teléfono</mat-label>
          <input matInput formControlName="telefono" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Correo</mat-label>
          <input matInput type="email" formControlName="correo" />
        </mat-form-field>

        <h3 class="section-title full">Políticas y horarios</h3>
        <mat-form-field appearance="outline">
          <mat-label>Hora check-in</mat-label>
          <input matInput formControlName="horaCheckin" placeholder="HH:mm" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Hora check-out</mat-label>
          <input matInput formControlName="horaCheckout" placeholder="HH:mm" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Check-in anticipado (flag num.)</mat-label>
          <input matInput type="number" formControlName="checkinAnticipado" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Check-out tardío (flag num.)</mat-label>
          <input matInput type="number" formControlName="checkoutTardio" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Edad mínima huésped</mat-label>
          <input matInput type="number" formControlName="edadMinimaHuesped" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Estado operativo</mat-label>
          <input matInput formControlName="estadoSucursal" />
        </mat-form-field>

        <div class="flags full">
          <mat-checkbox formControlName="aceptaNinos">Acepta niños</mat-checkbox>
          <mat-checkbox formControlName="permiteMascotas">Permite mascotas</mat-checkbox>
          <mat-checkbox formControlName="sePermiteFumar">Se permite fumar</mat-checkbox>
        </div>

        <div class="actions full">
          <button mat-flat-button color="primary" type="submit" [disabled]="guardando || form.invalid">
            {{ guardando ? 'Guardando…' : isCreate ? 'Crear sucursal' : 'Guardar cambios' }}
          </button>
          <a mat-button routerLink="/admin/sucursales">Cancelar</a>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
}
