// src/views/admin/AdminReservasPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { clientesList } from '@/services/clientes';
import { reservasConfirmar, reservasCreate, reservasDelete, reservasList } from '@/services/reservas';
import { sucursalesGetInternalPage } from '@/services/sucursales';
import { useUiStore } from '@/stores/ui';
import type { ReservaDTO } from '@/models';

const ui = useUiStore();

const rows = ref<ReservaDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);

const catalogLoading = ref(false);
const crearEnviando = ref(false);
const clientesSelect = ref<{ id: number; label: string }[]>([]);
const sucursalesSelect = ref<{ id: number; label: string }[]>([]);

const canalesOrigen = [
  { value: 'ADMIN', title: 'Administración / recepción' },
  { value: 'WEB', title: 'Web (huésped)' },
  { value: 'TELEFONO', title: 'Teléfono' },
];

const crearForm = reactive({
  idCliente: null as number | null,
  idSucursal: null as number | null,
  fechaInicio: '',
  fechaFin: '',
  origenCanalReserva: 'ADMIN',
  observaciones: '',
});

function pad(n: number): string {
  return String(n).padStart(2, '0');
}

function toDatetimeLocalValue(d: Date): string {
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

function patchFechasPorDefecto(): void {
  const fi = new Date();
  fi.setDate(fi.getDate() + 1);
  fi.setHours(15, 0, 0, 0);
  const ff = new Date(fi);
  ff.setDate(ff.getDate() + 2);
  ff.setHours(11, 0, 0, 0);
  crearForm.fechaInicio = toDatetimeLocalValue(fi);
  crearForm.fechaFin = toDatetimeLocalValue(ff);
}

function clienteLabel(c: {
  nombres?: string | null;
  apellidos?: string | null;
  correo?: string | null;
  razonSocial?: string | null;
  idCliente: number;
}): string {
  const name = [c.nombres, c.apellidos].filter(Boolean).join(' ').trim();
  if (name) return `${name} (#${c.idCliente})`;
  if (c.razonSocial) return `${c.razonSocial} (#${c.idCliente})`;
  if (c.correo) return `${c.correo} (#${c.idCliente})`;
  return `Cliente #${c.idCliente}`;
}

async function loadCatalogos(): Promise<void> {
  catalogLoading.value = true;
  try {
    const [clientes, sucursales] = await Promise.all([
      clientesList({ PageNumber: 1, PageSize: 200 }),
      sucursalesGetInternalPage({ PageNumber: 1, PageSize: 200 }),
    ]);
    const cr = clientes.data?.data ?? [];
    clientesSelect.value = cr.map((c) => ({ id: c.idCliente, label: clienteLabel(c) }));
    const sr = sucursales.data?.data ?? [];
    sucursalesSelect.value = sr.map((s) => ({
      id: s.idSucursal,
      label: [s.nombreSucursal, s.codigoSucursal ? `(${s.codigoSucursal})` : null].filter(Boolean).join(' '),
    }));
  } catch {
    ui.showSnack('No se pudieron cargar clientes o sucursales.', 6000);
  } finally {
    catalogLoading.value = false;
  }
}

async function crearReservaHuesped(): Promise<void> {
  const v = crearForm;
  if (v.idCliente == null || v.idSucursal == null || !v.fechaInicio || !v.fechaFin) {
    ui.showSnack('Completa el formulario de reserva.', 4000);
    return;
  }
  crearEnviando.value = true;
  try {
    const res = await reservasCreate({
      idCliente: v.idCliente,
      idSucursal: v.idSucursal,
      fechaInicio: new Date(v.fechaInicio).toISOString(),
      fechaFin: new Date(v.fechaFin).toISOString(),
      origenCanalReserva: v.origenCanalReserva,
      observaciones: v.observaciones?.trim() || undefined,
      esWalkin: 0,
    });
    if (res.success && res.data) {
      ui.showSnack(
        `Reserva creada (${v.idCliente}). Código: ${res.data.codigoReserva ?? res.data.guidReserva}`,
        6000,
      );
      crearForm.observaciones = '';
      patchFechasPorDefecto();
      await load();
    } else {
      ui.showSnack(res.message || 'Respuesta sin éxito', 6000);
    }
  } finally {
    crearEnviando.value = false;
  }
}

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await reservasList({ PageNumber: pageIndex.value + 1, PageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

async function confirmar(guid: string | null | undefined): Promise<void> {
  if (!guid) return;
  await reservasConfirmar(guid);
  await load();
}

async function remove(guid: string | null | undefined): Promise<void> {
  if (!guid || !confirm('¿Eliminar reserva?')) return;
  await reservasDelete(guid);
  await load();
}

function fmt(iso: string | null | undefined): string {
  if (!iso) return '—';
  return new Date(iso).toLocaleString('es');
}

onMounted(() => {
  patchFechasPorDefecto();
  void loadCatalogos();
  void load();
});
</script>

<template>
  <div class="admin-reservas-dash">
    <v-card class="mb-4">
      <v-card-title>Registrar reserva para un huésped</v-card-title>
      <v-card-subtitle>La reserva usa el mismo modelo que el sitio público.</v-card-subtitle>
      <v-card-text>
        <div v-if="catalogLoading" class="center"><v-progress-circular indeterminate size="36" /></div>
        <template v-else>
          <div class="crear-grid">
            <v-select
              v-model="crearForm.idCliente"
              :items="clientesSelect"
              item-title="label"
              item-value="id"
              label="Cliente"
              variant="outlined"
            />
            <v-select
              v-model="crearForm.idSucursal"
              :items="sucursalesSelect"
              item-title="label"
              item-value="id"
              label="Sucursal"
              variant="outlined"
            />
            <v-text-field v-model="crearForm.fechaInicio" label="Check-in" type="datetime-local" variant="outlined" />
            <v-text-field v-model="crearForm.fechaFin" label="Check-out" type="datetime-local" variant="outlined" />
            <v-select
              v-model="crearForm.origenCanalReserva"
              :items="canalesOrigen"
              item-title="title"
              item-value="value"
              label="Origen del canal"
              variant="outlined"
            />
            <v-textarea v-model="crearForm.observaciones" class="full-width" label="Observaciones" variant="outlined" rows="2" />
          </div>
          <div class="crear-actions mt-2">
            <v-btn
              color="primary"
              :disabled="
                crearEnviando ||
                crearForm.idCliente == null ||
                crearForm.idSucursal == null ||
                clientesSelect.length === 0 ||
                sucursalesSelect.length === 0
              "
              @click="crearReservaHuesped"
            >
              {{ crearEnviando ? 'Guardando…' : 'Guardar reserva' }}
            </v-btn>
            <v-btn class="ms-2" variant="text" @click="loadCatalogos">Recargar listas</v-btn>
          </div>
        </template>
      </v-card-text>
    </v-card>
  </div>

  <v-card class="mb-4">
    <v-card-title>Reservas (panel)</v-card-title>
  </v-card>

  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Código</th>
          <th>Id cliente</th>
          <th>Id sucursal</th>
          <th>Inicio</th>
          <th>Estado</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.guidReserva ?? String(r.codigoReserva)">
          <td>{{ r.codigoReserva }}</td>
          <td>{{ r.idCliente }}</td>
          <td>{{ r.idSucursal }}</td>
          <td>{{ fmt(r.fechaInicio) }}</td>
          <td>{{ r.estadoReserva }}</td>
          <td>
            <v-btn size="small" variant="text" icon="mdi-pencil" :to="'/admin/reservas/' + r.guidReserva" />
            <v-btn size="small" variant="text" color="primary" icon="mdi-check-circle" @click="confirmar(r.guidReserva)" />
            <v-btn size="small" variant="text" color="error" icon="mdi-delete" @click="remove(r.guidReserva)" />
          </td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1rem;
}
.crear-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
  gap: 0.75rem;
}
.full-width {
  grid-column: 1 / -1;
}
</style>

// src/app/features/admin/admin-reservas-page.component.ts
import { DatePipe } from '@angular/common';
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { forkJoin } from 'rxjs';
import { ClientesService } from '../../core/services/clientes.service';
import { ReservasService } from '../../core/services/reservas.service';
import { SucursalesService } from '../../core/services/sucursales.service';
import type { ReservaDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-reservas-page',
  standalone: true,
  imports: [
    DatePipe,
    ReactiveFormsModule,
    MatCardModule,
    MatTableModule,
    MatButtonModule,
    MatPaginatorModule,
    MatProgressSpinnerModule,
    MatFormFieldModule,
    MatInputModule,
    MatSelectModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-reservas-page.component.html',
  styleUrl: './admin-reservas-page.component.scss',
})
export class AdminReservasPageComponent implements OnInit {
  private readonly reservas = inject(ReservasService);
  private readonly clientesApi = inject(ClientesService);
  private readonly sucursalesApi = inject(SucursalesService);
  private readonly fb = inject(FormBuilder);
  private readonly snack = inject(MatSnackBar);

  displayedColumns: string[] = ['codigo', 'cliente', 'sucursal', 'inicio', 'estado', 'acciones'];
  rows: ReservaDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;

  catalogLoading = false;
  crearEnviando = false;

  readonly crearForm = this.fb.nonNullable.group({
    idCliente: this.fb.control<number | null>(null, Validators.required),
    idSucursal: this.fb.control<number | null>(null, Validators.required),
    fechaInicio: this.fb.control('', Validators.required),
    fechaFin: this.fb.control('', Validators.required),
    origenCanalReserva: this.fb.control('ADMIN', Validators.required),
    observaciones: this.fb.control(''),
  });

  clientesSelect: { id: number; label: string }[] = [];
  sucursalesSelect: { id: number; label: string }[] = [];

  readonly canalesOrigen = [
    { value: 'ADMIN', label: 'Administración / recepción' },
    { value: 'WEB', label: 'Web (huésped)' },
    { value: 'TELEFONO', label: 'Teléfono' },
  ];

  ngOnInit(): void {
    this.patchFechasPorDefecto();
    this.loadCatalogos();
    this.load();
  }

  private patchFechasPorDefecto(): void {
    const fi = new Date();
    fi.setDate(fi.getDate() + 1);
    fi.setHours(15, 0, 0, 0);
    const ff = new Date(fi);
    ff.setDate(ff.getDate() + 2);
    ff.setHours(11, 0, 0, 0);
    this.crearForm.patchValue({
      fechaInicio: this.toDatetimeLocalValue(fi),
      fechaFin: this.toDatetimeLocalValue(ff),
    });
  }

  private toDatetimeLocalValue(d: Date): string {
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }

  loadCatalogos(): void {
    this.catalogLoading = true;
    forkJoin({
      clientes: this.clientesApi.list({ PageNumber: 1, PageSize: 200 }),
      sucursales: this.sucursalesApi.getInternalPage({ PageNumber: 1, PageSize: 200 }),
    }).subscribe({
      next: ({ clientes, sucursales }) => {
        const cr = clientes.data?.data ?? [];
        this.clientesSelect = cr.map((c) => ({
          id: c.idCliente,
          label: this.clienteLabel(c),
        }));
        const sr = sucursales.data?.data ?? [];
        this.sucursalesSelect = sr.map((s) => ({
          id: s.idSucursal,
          label: [s.nombreSucursal, s.codigoSucursal ? `(${s.codigoSucursal})` : null].filter(Boolean).join(' '),
        }));
        this.catalogLoading = false;
      },
      error: () => {
        this.catalogLoading = false;
        this.snack.open('No se pudieron cargar clientes o sucursales (permisos o red).', 'Cerrar', { duration: 6000 });
      },
    });
  }

  private clienteLabel(c: {
    nombres?: string | null;
    apellidos?: string | null;
    correo?: string | null;
    razonSocial?: string | null;
    idCliente: number;
  }): string {
    const name = [c.nombres, c.apellidos].filter(Boolean).join(' ').trim();
    if (name) {
      return `${name} (#${c.idCliente})`;
    }
    if (c.razonSocial) {
      return `${c.razonSocial} (#${c.idCliente})`;
    }
    if (c.correo) {
      return `${c.correo} (#${c.idCliente})`;
    }
    return `Cliente #${c.idCliente}`;
  }

  crearReservaHuesped(): void {
    if (this.crearForm.invalid) {
      this.crearForm.markAllAsTouched();
      return;
    }
    const v = this.crearForm.getRawValue();
    const fi = v.fechaInicio;
    const ff = v.fechaFin;
    const canal = v.origenCanalReserva;
    if (fi == null || ff == null || !canal) {
      return;
    }
    this.crearEnviando = true;
    this.reservas
      .create({
        idCliente: v.idCliente!,
        idSucursal: v.idSucursal!,
        fechaInicio: new Date(fi).toISOString(),
        fechaFin: new Date(ff).toISOString(),
        origenCanalReserva: canal,
        observaciones: v.observaciones?.trim() || undefined,
        esWalkin: 0,
      })
      .subscribe({
        next: (res) => {
          this.crearEnviando = false;
          if (res.success && res.data) {
            this.snack.open(
              `Reserva creada para el huésped (${v.idCliente}). Código: ${res.data.codigoReserva ?? res.data.guidReserva}`,
              'Cerrar',
              { duration: 6000 },
            );
            this.crearForm.patchValue({
              observaciones: '',
            });
            this.patchFechasPorDefecto();
            this.load();
          } else {
            this.snack.open(res.message || 'Respuesta sin éxito', 'Cerrar');
          }
        },
        error: () => (this.crearEnviando = false),
      });
  }

  load(): void {
    this.loading = true;
    this.reservas
      .list({
        PageNumber: this.pageIndex + 1,
        PageSize: this.pageSize,
      })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  confirmar(guid: string): void {
    this.reservas.confirmar(guid).subscribe({ next: () => this.load() });
  }

  remove(guid: string): void {
    if (!confirm('¿Eliminar reserva?')) {
      return;
    }
    this.reservas.delete(guid).subscribe({ next: () => this.load() });
  }
}

<div class="admin-reservas-dash">
  <mat-card class="mb dash-card">
    <mat-card-title>Registrar reserva para un huésped</mat-card-title>
    <mat-card-subtitle>
      La reserva se guarda en el mismo modelo que usa el sitio público. El cliente la verá en
      <strong>Mis reservas</strong> con su cuenta (mismo <code>idCliente</code>).
    </mat-card-subtitle>
    <mat-card-content>
      @if (catalogLoading) {
        <div class="center"><mat-spinner diameter="36" /></div>
      } @else {
        <form class="crear-grid" [formGroup]="crearForm" (ngSubmit)="crearReservaHuesped()">
          <mat-form-field appearance="outline">
            <mat-label>Cliente (huésped)</mat-label>
            <mat-select formControlName="idCliente" required>
              @for (c of clientesSelect; track c.id) {
                <mat-option [value]="c.id">{{ c.label }}</mat-option>
              }
            </mat-select>
            @if (clientesSelect.length === 0) {
              <mat-hint>No hay clientes en la primera página. Crea clientes en el API o amplía el listado.</mat-hint>
            }
          </mat-form-field>

          <mat-form-field appearance="outline">
            <mat-label>Sucursal</mat-label>
            <mat-select formControlName="idSucursal" required>
              @for (s of sucursalesSelect; track s.id) {
                <mat-option [value]="s.id">{{ s.label || '—' }} (#{{ s.id }})</mat-option>
              }
            </mat-select>
          </mat-form-field>

          <mat-form-field appearance="outline">
            <mat-label>Check-in</mat-label>
            <input matInput type="datetime-local" formControlName="fechaInicio" />
          </mat-form-field>

          <mat-form-field appearance="outline">
            <mat-label>Check-out</mat-label>
            <input matInput type="datetime-local" formControlName="fechaFin" />
          </mat-form-field>

          <mat-form-field appearance="outline">
            <mat-label>Origen del canal</mat-label>
            <mat-select formControlName="origenCanalReserva">
              @for (ch of canalesOrigen; track ch.value) {
                <mat-option [value]="ch.value">{{ ch.label }}</mat-option>
              }
            </mat-select>
          </mat-form-field>

          <mat-form-field appearance="outline" class="full-width">
            <mat-label>Observaciones (opcional)</mat-label>
            <textarea matInput rows="2" formControlName="observaciones"></textarea>
          </mat-form-field>

          <div class="crear-actions">
            <button
              mat-flat-button
              color="primary"
              type="submit"
              [disabled]="crearEnviando || crearForm.invalid || clientesSelect.length === 0 || sucursalesSelect.length === 0"
            >
              @if (crearEnviando) {
                Guardando…
              } @else {
                Guardar reserva
              }
            </button>
            <button mat-button type="button" (click)="loadCatalogos()" [disabled]="catalogLoading">Recargar listas</button>
          </div>
        </form>
      }
    </mat-card-content>
  </mat-card>

  <mat-card class="mb">
    <mat-card-title>Reservas (panel)</mat-card-title>
    <mat-card-subtitle>Listado centralizado: confirmación, eliminación y seguimiento.</mat-card-subtitle>
  </mat-card>
</div>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="codigo">
      <th mat-header-cell *matHeaderCellDef>Código</th>
      <td mat-cell *matCellDef="let r">{{ r.codigoReserva }}</td>
    </ng-container>
    <ng-container matColumnDef="cliente">
      <th mat-header-cell *matHeaderCellDef>Id cliente</th>
      <td mat-cell *matCellDef="let r">{{ r.idCliente }}</td>
    </ng-container>
    <ng-container matColumnDef="sucursal">
      <th mat-header-cell *matHeaderCellDef>Id sucursal</th>
      <td mat-cell *matCellDef="let r">{{ r.idSucursal }}</td>
    </ng-container>
    <ng-container matColumnDef="inicio">
      <th mat-header-cell *matHeaderCellDef>Inicio</th>
      <td mat-cell *matCellDef="let r">{{ r.fechaInicio | date: 'short' }}</td>
    </ng-container>
    <ng-container matColumnDef="estado">
      <th mat-header-cell *matHeaderCellDef>Estado</th>
      <td mat-cell *matCellDef="let r">{{ r.estadoReserva }}</td>
    </ng-container>
    <ng-container matColumnDef="acciones">
      <th mat-header-cell *matHeaderCellDef></th>
      <td mat-cell *matCellDef="let r">
        <button mat-button type="button" (click)="confirmar(r.guidReserva)">Confirmar</button>
        <button mat-button type="button" (click)="remove(r.guidReserva)">Eliminar</button>
      </td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[5, 10, 20]"
    (page)="onPage($event)"
  />
}
