// src/views/admin/AdminReservaEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { reservasGetByGuid, reservasUpdate } from '@/services/reservas';
import { useUiStore } from '@/stores/ui';
import { isUuidString } from '@/utils/string.util';

const ESTADOS = ['Pendiente', 'Confirmada', 'CheckIn', 'CheckOut', 'Cancelada', 'NoShow'] as const;

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const estados: string[] = [...ESTADOS];
const guid = ref('');
const codigoReserva = ref('');
const loading = ref(true);
const guardando = ref(false);

const form = reactive({
  fechaInicio: '',
  fechaFin: '',
  estadoReserva: '',
  observaciones: '',
});

function toDatetimeLocal(iso: string): string {
  if (!iso) return '';
  const d = new Date(iso);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}

onMounted(async () => {
  const id = String(route.params.guid ?? '');
  if (!isUuidString(id)) {
    ui.showSnack('GUID de reserva inválido', 4000);
    void router.push('/admin/reservas');
    return;
  }
  guid.value = id;
  try {
    const res = await reservasGetByGuid(id);
    if (res.success && res.data) {
      const r = res.data;
      codigoReserva.value = r.codigoReserva ?? r.guidReserva ?? '';
      form.fechaInicio = toDatetimeLocal(r.fechaInicio ?? '');
      form.fechaFin = toDatetimeLocal(r.fechaFin ?? '');
      form.estadoReserva = r.estadoReserva ?? '';
      form.observaciones = r.observaciones ?? '';
    }
  } finally {
    loading.value = false;
  }
});

async function save(): Promise<void> {
  if (!form.fechaInicio || !form.fechaFin) {
    ui.showSnack('Fechas obligatorias', 4000);
    return;
  }
  guardando.value = true;
  try {
    const res = await reservasUpdate(guid.value, {
      fechaInicio: new Date(form.fechaInicio).toISOString(),
      fechaFin: new Date(form.fechaFin).toISOString(),
      estadoReserva: form.estadoReserva || undefined,
      observaciones: form.observaciones || undefined,
    });
    if (res.success) {
      ui.showSnack('Reserva actualizada', 3000);
      void router.push('/admin/reservas');
    }
  } finally {
    guardando.value = false;
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <v-card v-else>
    <v-card-title>Editar reserva {{ codigoReserva }}</v-card-title>
    <v-card-text>
      <v-text-field v-model="form.fechaInicio" label="Inicio" type="datetime-local" variant="outlined" />
      <v-text-field v-model="form.fechaFin" label="Fin" type="datetime-local" variant="outlined" />
      <v-select v-model="form.estadoReserva" :items="estados" label="Estado" variant="outlined" clearable />
      <v-textarea v-model="form.observaciones" label="Observaciones" variant="outlined" />
      <v-btn color="primary" :loading="guardando" @click="save">Guardar</v-btn>
      <v-btn class="ms-2" variant="text" to="/admin/reservas">Volver</v-btn>
    </v-card-text>
  </v-card>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
</style>

// src/app/features/admin/admin-reserva-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ReservasService } from '../../core/services/reservas.service';
import { isUuidString } from '../../shared/utils/string.util';

const ESTADOS = ['Pendiente', 'Confirmada', 'CheckIn', 'CheckOut', 'Cancelada', 'NoShow'] as const;

@Component({
  selector: 'app-admin-reserva-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-reserva-edit-page.component.html',
  styleUrl: './admin-reserva-edit-page.component.scss',
})
export class AdminReservaEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly reservas = inject(ReservasService);
  private readonly snack = inject(MatSnackBar);

  readonly estados = ESTADOS;

  readonly form = this.fb.nonNullable.group({
    fechaInicio: this.fb.control('', Validators.required),
    fechaFin: this.fb.control('', Validators.required),
    estadoReserva: this.fb.control(''),
    observaciones: this.fb.control(''),
  });

  guid = '';
  codigoReserva = '';
  loading = true;
  guardando = false;

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('guid') ?? '';
    if (!isUuidString(id)) {
      this.snack.open('GUID de reserva inválido', 'Cerrar');
      void this.router.navigate(['/admin/reservas']);
      return;
    }
    this.guid = id;
    this.reservas.getByGuid(id).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          const r = res.data;
          this.codigoReserva = r.codigoReserva ?? r.guidReserva ?? '';
          this.form.patchValue({
            fechaInicio: this.toDatetimeLocal(r.fechaInicio ?? ''),
            fechaFin: this.toDatetimeLocal(r.fechaFin ?? ''),
            estadoReserva: r.estadoReserva ?? '',
            observaciones: r.observaciones ?? '',
          });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  save(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.guardando = true;
    const v = this.form.getRawValue();
    this.reservas
      .update(this.guid, {
        fechaInicio: new Date(v.fechaInicio!).toISOString(),
        fechaFin: new Date(v.fechaFin!).toISOString(),
        estadoReserva: v.estadoReserva || undefined,
        observaciones: v.observaciones || undefined,
      })
      .subscribe({
        next: (res) => {
          this.guardando = false;
          if (res.success) {
            this.snack.open('Reserva actualizada', 'Cerrar', { duration: 3000 });
            void this.router.navigate(['/admin/reservas']);
          }
        },
        error: () => (this.guardando = false),
      });
  }

  private toDatetimeLocal(iso: string): string {
    if (!iso) return '';
    const d = new Date(iso);
    const pad = (n: number) => String(n).padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <form [formGroup]="form" (ngSubmit)="save()">

    <mat-card class="section-card">
      <mat-card-header>
        <mat-icon mat-card-avatar>event_note</mat-icon>
        <mat-card-title>Editar reserva {{ codigoReserva ? '#' + codigoReserva : '' }}</mat-card-title>
        <mat-card-subtitle>Modifica fechas, estado u observaciones de la reserva.</mat-card-subtitle>
      </mat-card-header>
    </mat-card>

    <mat-card class="section-card">
      <mat-card-header>
        <mat-card-title class="section-title">
          <mat-icon>date_range</mat-icon> Fechas de estancia
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Check-in</mat-label>
            <input matInput type="datetime-local" formControlName="fechaInicio" />
            @if (form.controls.fechaInicio.hasError('required')) {
              <mat-error>Requerido</mat-error>
            }
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Check-out</mat-label>
            <input matInput type="datetime-local" formControlName="fechaFin" />
            @if (form.controls.fechaFin.hasError('required')) {
              <mat-error>Requerido</mat-error>
            }
          </mat-form-field>
        </div>
      </mat-card-content>
    </mat-card>

    <mat-card class="section-card">
      <mat-card-header>
        <mat-card-title class="section-title">
          <mat-icon>info</mat-icon> Estado y notas
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Estado de la reserva</mat-label>
          <mat-select formControlName="estadoReserva">
            <mat-option value="">— Sin cambio —</mat-option>
            @for (e of estados; track e) {
              <mat-option [value]="e">{{ e }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Observaciones</mat-label>
          <textarea matInput rows="3" formControlName="observaciones"></textarea>
        </mat-form-field>
      </mat-card-content>
    </mat-card>

    <div class="actions-bar">
      <button mat-raised-button color="primary" type="submit" [disabled]="guardando || form.invalid">
        @if (guardando) {
          <mat-spinner diameter="18" />
        } @else {
          <mat-icon>save</mat-icon>
        }
        Guardar cambios
      </button>
      <a mat-stroked-button routerLink="/admin/reservas">
        <mat-icon>arrow_back</mat-icon>
        Volver
      </a>
    </div>

  </form>
}
