// src/views/admin/AdminClientesPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { clientesDelete, clientesList } from '@/services/clientes';
import { useUiStore } from '@/stores/ui';
import type { ClienteDTO } from '@/models';

const ui = useUiStore();
const rows = ref<ClienteDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await clientesList({ PageNumber: pageIndex.value + 1, PageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

async function remove(r: ClienteDTO): Promise<void> {
  const nombre = [r.nombres, r.apellidos].filter(Boolean).join(' ') || r.correo || String(r.idCliente);
  if (!confirm(`¿Eliminar al cliente "${nombre}"?`)) return;
  const res = await clientesDelete(r.clienteGuid!);
  if (res.success) {
    ui.showSnack('Cliente eliminado', 3000);
    void load();
  }
}

onMounted(() => void load());
</script>

<template>
  <v-card class="mb-4">
    <v-card-title>Clientes</v-card-title>
    <v-card-actions>
      <v-btn color="primary" to="/admin/clientes/nuevo">Nuevo</v-btn>
    </v-card-actions>
  </v-card>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombres</th>
          <th>Correo</th>
          <th>Teléfono</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.clienteGuid ?? String(r.idCliente)">
          <td>{{ r.idCliente }}</td>
          <td>{{ [r.nombres, r.apellidos].filter(Boolean).join(' ') || '—' }}</td>
          <td>{{ r.correo }}</td>
          <td>{{ r.telefono }}</td>
          <td>
            <v-btn v-if="r.clienteGuid" size="small" variant="text" :to="'/admin/clientes/' + r.clienteGuid">Editar</v-btn>
            <v-btn v-if="r.clienteGuid" size="small" variant="text" color="error" @click="remove(r)">Eliminar</v-btn>
          </td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1.5rem;
}
</style>

// src/app/features/admin/admin-clientes-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { MatTooltipModule } from '@angular/material/tooltip';
import { ClientesService } from '../../core/services/clientes.service';
import type { ClienteDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-clientes-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatTableModule, MatButtonModule, MatIconModule, MatPaginatorModule, MatProgressSpinnerModule, MatTooltipModule, MatSnackBarModule],
  templateUrl: './admin-clientes-page.component.html',
  styleUrl: './admin-clientes-page.component.scss',
})
export class AdminClientesPageComponent implements OnInit {
  private readonly clientes = inject(ClientesService);
  private readonly snack = inject(MatSnackBar);

  displayedColumns: string[] = ['id', 'nombres', 'correo', 'telefono', 'acciones'];
  rows: ClienteDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.clientes
      .list({ PageNumber: this.pageIndex + 1, PageSize: this.pageSize })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  remove(guid: string, nombre: string): void {
    if (!confirm(`¿Eliminar al cliente "${nombre}"? Esta acción no se puede deshacer.`)) return;
    this.clientes.delete(guid).subscribe({
      next: (res) => {
        if (res.success) {
          this.snack.open('Cliente eliminado', 'Cerrar', { duration: 3000 });
          this.load();
        }
      },
    });
  }
}

<mat-card class="mb">
  <mat-card-title>Clientes (CRUD)</mat-card-title>
  <mat-card-subtitle>Huéspedes y datos de contacto vinculados a reservas y facturación.</mat-card-subtitle>
  <mat-card-actions>
    <a mat-raised-button color="primary" routerLink="/admin/clientes/nuevo">Nuevo cliente</a>
  </mat-card-actions>
</mat-card>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="id">
      <th mat-header-cell *matHeaderCellDef>Id</th>
      <td mat-cell *matCellDef="let r">{{ r.idCliente }}</td>
    </ng-container>
    <ng-container matColumnDef="nombres">
      <th mat-header-cell *matHeaderCellDef>Nombre</th>
      <td mat-cell *matCellDef="let r">{{ r.nombres }} {{ r.apellidos }}</td>
    </ng-container>
    <ng-container matColumnDef="correo">
      <th mat-header-cell *matHeaderCellDef>Correo</th>
      <td mat-cell *matCellDef="let r">{{ r.correo }}</td>
    </ng-container>
    <ng-container matColumnDef="telefono">
      <th mat-header-cell *matHeaderCellDef>Teléfono</th>
      <td mat-cell *matCellDef="let r">{{ r.telefono }}</td>
    </ng-container>
    <ng-container matColumnDef="acciones">
      <th mat-header-cell *matHeaderCellDef></th>
      <td mat-cell *matCellDef="let r" class="acciones-cell">
        <a mat-icon-button [routerLink]="['/admin/clientes', r.clienteGuid]" matTooltip="Editar">
          <mat-icon>edit</mat-icon>
        </a>
        <button mat-icon-button color="warn" type="button" matTooltip="Eliminar"
          (click)="remove(r.clienteGuid, (r.nombres || '') + ' ' + (r.apellidos || ''))">
          <mat-icon>delete</mat-icon>
        </button>
      </td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[5, 10, 20]"
    (page)="onPage($event)"
  />
}
