// src/views/admin/AdminHabitacionEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { habitacionesCreate, habitacionesGetByGuid, habitacionesUpdate } from '@/services/habitaciones';
import { tiposHabitacionList } from '@/services/tiposHabitacion';
import { useUiStore } from '@/stores/ui';
import { isUuidString } from '@/utils/string.util';
import type { HabitacionCreateRequest, HabitacionUpdateRequest, TipoHabitacionDTO } from '@/models';

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const isCreate = ref(false);
const guid = ref<string | undefined>();
const loading = ref(true);
const tiposRows = ref<TipoHabitacionDTO[]>([]);

const createForm = reactive({
  idSucursal: null as number | null,
  idTipoHabitacion: null as number | null,
  numeroHabitacion: '',
  piso: null as number | null,
  capacidadHabitacion: 1,
  precioBase: 0.01,
  descripcionHabitacion: '',
  estadoHabitacion: '',
});

const editForm = reactive({
  numeroHabitacion: '',
  piso: null as number | null,
  capacidadHabitacion: null as number | null,
  precioBase: null as number | null,
  descripcionHabitacion: '',
  estadoHabitacion: '',
});

onMounted(async () => {
  const t = await tiposHabitacionList({ PageNumber: 1, PageSize: 200 });
  tiposRows.value = t.data?.data ?? [];

  const p = String(route.params.guid ?? '');
  if (p === 'nuevo') {
    isCreate.value = true;
    loading.value = false;
    return;
  }
  if (!isUuidString(p)) {
    ui.showSnack('Guid inválido', 4000);
    void router.push('/admin/habitaciones');
    return;
  }
  guid.value = p;
  try {
    const res = await habitacionesGetByGuid(p);
    if (res.success && res.data) {
      const d = res.data;
      editForm.numeroHabitacion = d.numeroHabitacion ?? '';
      editForm.piso = d.piso ?? null;
      editForm.capacidadHabitacion = d.capacidadHabitacion;
      editForm.precioBase = d.precioBase;
      editForm.descripcionHabitacion = d.descripcionHabitacion ?? '';
      editForm.estadoHabitacion = d.estadoHabitacion ?? '';
    }
  } finally {
    loading.value = false;
  }
});

async function saveCreate(): Promise<void> {
  if (
    createForm.idSucursal == null ||
    createForm.idTipoHabitacion == null ||
    !createForm.numeroHabitacion
  ) {
    ui.showSnack('Completa sucursal, tipo y número.', 4000);
    return;
  }
  const body: HabitacionCreateRequest = {
    idSucursal: createForm.idSucursal,
    idTipoHabitacion: createForm.idTipoHabitacion,
    numeroHabitacion: createForm.numeroHabitacion,
    piso: createForm.piso,
    capacidadHabitacion: createForm.capacidadHabitacion,
    precioBase: createForm.precioBase,
    descripcionHabitacion: createForm.descripcionHabitacion || undefined,
    estadoHabitacion: createForm.estadoHabitacion || undefined,
  };
  const res = await habitacionesCreate(body);
  if (res.success) {
    ui.showSnack('Creada', 2500);
    void router.push('/admin/habitaciones');
  }
}

async function saveEdit(): Promise<void> {
  if (!guid.value) return;
  const v = editForm;
  const body: HabitacionUpdateRequest = {
    numeroHabitacion: v.numeroHabitacion || undefined,
    piso: v.piso,
    capacidadHabitacion: v.capacidadHabitacion ?? undefined,
    precioBase: v.precioBase ?? undefined,
    descripcionHabitacion: v.descripcionHabitacion || undefined,
    estadoHabitacion: v.estadoHabitacion || undefined,
  };
  const res = await habitacionesUpdate(guid.value, body);
  if (res.success) {
    ui.showSnack('Guardado', 2500);
    void router.push('/admin/habitaciones');
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <v-card v-else-if="isCreate">
    <v-card-title>Nueva habitación</v-card-title>
    <v-card-text>
      <v-text-field v-model.number="createForm.idSucursal" label="Id sucursal" type="number" variant="outlined" />
      <v-select
        v-model="createForm.idTipoHabitacion"
        :items="tiposRows"
        item-title="nombreTipoHabitacion"
        item-value="idTipoHabitacion"
        label="Tipo habitación"
        variant="outlined"
      />
      <v-text-field v-model="createForm.numeroHabitacion" label="Número" variant="outlined" />
      <v-text-field v-model.number="createForm.piso" label="Piso" type="number" variant="outlined" />
      <v-text-field v-model.number="createForm.capacidadHabitacion" label="Capacidad" type="number" variant="outlined" />
      <v-text-field v-model.number="createForm.precioBase" label="Precio base" type="number" variant="outlined" />
      <v-textarea v-model="createForm.descripcionHabitacion" label="Descripción" variant="outlined" />
      <v-text-field v-model="createForm.estadoHabitacion" label="Estado" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveCreate">Crear</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/habitaciones">Cancelar</v-btn>
    </v-card-text>
  </v-card>
  <v-card v-else>
    <v-card-title>Editar habitación</v-card-title>
    <v-card-text>
      <v-text-field v-model="editForm.numeroHabitacion" label="Número" variant="outlined" />
      <v-text-field v-model.number="editForm.piso" label="Piso" type="number" variant="outlined" />
      <v-text-field v-model.number="editForm.capacidadHabitacion" label="Capacidad" type="number" variant="outlined" />
      <v-text-field v-model.number="editForm.precioBase" label="Precio base" type="number" variant="outlined" />
      <v-textarea v-model="editForm.descripcionHabitacion" label="Descripción" variant="outlined" />
      <v-text-field v-model="editForm.estadoHabitacion" label="Estado" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveEdit">Guardar</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/habitaciones">Volver</v-btn>
    </v-card-text>
  </v-card>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
</style>

// src/app/features/admin/admin-habitacion-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { HabitacionesService } from '../../core/services/habitaciones.service';
import { TiposHabitacionService } from '../../core/services/tipos-habitacion.service';
import { isUuidString } from '../../shared/utils/string.util';
import type { HabitacionCreateRequest, HabitacionUpdateRequest, TipoHabitacionDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-habitacion-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-habitacion-edit-page.component.html',
  styleUrl: './admin-habitacion-edit-page.component.scss',
})
export class AdminHabitacionEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly habitaciones = inject(HabitacionesService);
  private readonly tipos = inject(TiposHabitacionService);
  private readonly snack = inject(MatSnackBar);

  readonly createForm = this.fb.nonNullable.group({
    idSucursal: this.fb.control<number | null>(null, Validators.required),
    idTipoHabitacion: this.fb.control<number | null>(null, Validators.required),
    numeroHabitacion: this.fb.control('', Validators.required),
    piso: this.fb.control<number | null>(null),
    capacidadHabitacion: this.fb.control(1, [Validators.required, Validators.min(1)]),
    precioBase: this.fb.control(0.01, [Validators.required, Validators.min(0.01)]),
    descripcionHabitacion: this.fb.control(''),
    estadoHabitacion: this.fb.control(''),
  });

  readonly editForm = this.fb.nonNullable.group({
    numeroHabitacion: this.fb.control(''),
    piso: this.fb.control<number | null>(null),
    capacidadHabitacion: this.fb.control<number | null>(null),
    precioBase: this.fb.control<number | null>(null),
    descripcionHabitacion: this.fb.control(''),
    estadoHabitacion: this.fb.control(''),
  });

  isCreate = false;
  guid?: string;
  loading = true;
  tiposRows: TipoHabitacionDTO[] = [];

  ngOnInit(): void {
    const p = this.route.snapshot.paramMap.get('guid') ?? '';
    this.tipos.list({ PageNumber: 1, PageSize: 200 }).subscribe((r) => {
      this.tiposRows = r.data?.data ?? [];
    });
    if (p === 'nuevo') {
      this.isCreate = true;
      this.loading = false;
      return;
    }
    if (!isUuidString(p)) {
      this.snack.open('Guid inválido', 'Cerrar');
      void this.router.navigate(['/admin/habitaciones']);
      return;
    }
    this.guid = p;
    this.habitaciones.getByGuid(p).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          const d = res.data;
          this.editForm.patchValue({
            numeroHabitacion: d.numeroHabitacion ?? '',
            piso: d.piso ?? null,
            capacidadHabitacion: d.capacidadHabitacion,
            precioBase: d.precioBase,
            descripcionHabitacion: d.descripcionHabitacion ?? '',
            estadoHabitacion: d.estadoHabitacion ?? '',
          });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  saveCreate(): void {
    if (this.createForm.invalid) {
      this.createForm.markAllAsTouched();
      return;
    }
    const v = this.createForm.getRawValue();
    const body: HabitacionCreateRequest = {
      idSucursal: v.idSucursal!,
      idTipoHabitacion: v.idTipoHabitacion!,
      numeroHabitacion: v.numeroHabitacion as string,
      piso: v.piso,
      capacidadHabitacion: v.capacidadHabitacion as number,
      precioBase: v.precioBase as number,
      descripcionHabitacion: v.descripcionHabitacion || undefined,
      estadoHabitacion: v.estadoHabitacion || undefined,
    };
    this.habitaciones.create(body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Creada', 'Cerrar', { duration: 2500 });
        void this.router.navigate(['/admin/habitaciones']);
      }
    });
  }

  saveEdit(): void {
    if (!this.guid) {
      return;
    }
    const v = this.editForm.getRawValue();
    const body: HabitacionUpdateRequest = {
      numeroHabitacion: v.numeroHabitacion || undefined,
      piso: v.piso,
      capacidadHabitacion: v.capacidadHabitacion ?? undefined,
      precioBase: v.precioBase ?? undefined,
      descripcionHabitacion: v.descripcionHabitacion || undefined,
      estadoHabitacion: v.estadoHabitacion || undefined,
    };
    this.habitaciones.update(this.guid, body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Guardado', 'Cerrar', { duration: 2500 });
        void this.router.navigate(['/admin/habitaciones']);
      }
    });
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else if (isCreate) {
  <mat-card>
    <mat-card-title>Nueva habitación</mat-card-title>
    <mat-card-content>
      <form [formGroup]="createForm" (ngSubmit)="saveCreate()">
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Id sucursal</mat-label>
            <input matInput type="number" formControlName="idSucursal" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Tipo habitación</mat-label>
            <mat-select formControlName="idTipoHabitacion">
              @for (t of tiposRows; track t.tipoHabitacionGuid) {
                <mat-option [value]="t.idTipoHabitacion">{{ t.nombreTipoHabitacion }} ({{ t.idTipoHabitacion }})</mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Número</mat-label>
            <input matInput formControlName="numeroHabitacion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Piso</mat-label>
            <input matInput type="number" formControlName="piso" />
          </mat-form-field>
        </div>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Capacidad</mat-label>
            <input matInput type="number" formControlName="capacidadHabitacion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Precio base</mat-label>
            <input matInput type="number" formControlName="precioBase" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="2" formControlName="descripcionHabitacion"></textarea>
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Estado</mat-label>
          <input matInput formControlName="estadoHabitacion" />
        </mat-form-field>
        <button mat-raised-button color="primary" type="submit" [disabled]="createForm.invalid">Crear</button>
        <a mat-button routerLink="/admin/habitaciones">Cancelar</a>
      </form>
    </mat-card-content>
  </mat-card>
} @else {
  <mat-card>
    <mat-card-title>Editar habitación</mat-card-title>
    <mat-card-subtitle>{{ guid }}</mat-card-subtitle>
    <mat-card-content>
      <form [formGroup]="editForm" (ngSubmit)="saveEdit()">
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Número</mat-label>
            <input matInput formControlName="numeroHabitacion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Piso</mat-label>
            <input matInput type="number" formControlName="piso" />
          </mat-form-field>
        </div>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Capacidad</mat-label>
            <input matInput type="number" formControlName="capacidadHabitacion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Precio base</mat-label>
            <input matInput type="number" formControlName="precioBase" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="2" formControlName="descripcionHabitacion"></textarea>
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Estado</mat-label>
          <input matInput formControlName="estadoHabitacion" />
        </mat-form-field>
        <button mat-raised-button color="primary" type="submit">Guardar</button>
        <a mat-button routerLink="/admin/habitaciones">Volver</a>
      </form>
    </mat-card-content>
  </mat-card>
}
