// src/views/admin/AdminTiposHabitacionPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { tiposHabitacionList } from '@/services/tiposHabitacion';
import type { TipoHabitacionDTO } from '@/models';

const rows = ref<TipoHabitacionDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(15);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await tiposHabitacionList({ PageNumber: pageIndex.value + 1, PageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

onMounted(() => void load());
</script>

<template>
  <v-card class="mb-4">
    <v-card-title>Tipos de habitación</v-card-title>
    <v-card-subtitle>Catálogo maestro (solo lectura en esta vista).</v-card-subtitle>
  </v-card>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Código</th>
          <th>Nombre</th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.tipoHabitacionGuid">
          <td>{{ r.idTipoHabitacion }}</td>
          <td>{{ r.codigoTipoHabitacion }}</td>
          <td>{{ r.nombreTipoHabitacion }}</td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1.5rem;
}
</style>

// src/app/features/admin/admin-tipos-habitacion-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { MatCardModule } from '@angular/material/card';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { TiposHabitacionService } from '../../core/services/tipos-habitacion.service';
import type { TipoHabitacionDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-tipos-habitacion-page',
  standalone: true,
  imports: [MatCardModule, MatTableModule, MatPaginatorModule, MatProgressSpinnerModule],
  templateUrl: './admin-tipos-habitacion-page.component.html',
  styleUrl: './admin-tipos-habitacion-page.component.scss',
})
export class AdminTiposHabitacionPageComponent implements OnInit {
  private readonly tipos = inject(TiposHabitacionService);

  displayedColumns: string[] = ['id', 'codigo', 'nombre'];
  rows: TipoHabitacionDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 15;
  loading = false;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.tipos
      .list({
        PageNumber: this.pageIndex + 1,
        PageSize: this.pageSize,
      })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }
}

<mat-card class="mb">
  <mat-card-title>Tipos de habitación</mat-card-title>
  <mat-card-subtitle>Catálogo maestro usado al crear habitaciones y tarifas.</mat-card-subtitle>
</mat-card>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="id">
      <th mat-header-cell *matHeaderCellDef>Id</th>
      <td mat-cell *matCellDef="let r">{{ r.idTipoHabitacion }}</td>
    </ng-container>
    <ng-container matColumnDef="codigo">
      <th mat-header-cell *matHeaderCellDef>Código</th>
      <td mat-cell *matCellDef="let r">{{ r.codigoTipoHabitacion ?? '—' }}</td>
    </ng-container>
    <ng-container matColumnDef="nombre">
      <th mat-header-cell *matHeaderCellDef>Nombre</th>
      <td mat-cell *matCellDef="let r">{{ r.nombreTipoHabitacion ?? '—' }}</td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[10, 15, 30]"
    (page)="onPage($event)"
  />
}
