// src/app/features/admin/admin-sucursales-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { MatTableModule } from '@angular/material/table';
import { MatTooltipModule } from '@angular/material/tooltip';
import { SucursalesService } from '../../core/services/sucursales.service';
import type { SucursalDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-sucursales-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatTableModule, MatButtonModule, MatIconModule, MatPaginatorModule, MatProgressSpinnerModule, MatTooltipModule, MatSnackBarModule],
  templateUrl: './admin-sucursales-page.component.html',
  styleUrl: './admin-sucursales-page.component.scss',
})
export class AdminSucursalesPageComponent implements OnInit {
  private readonly sucursales = inject(SucursalesService);
  private readonly snack = inject(MatSnackBar);

  displayedColumns: string[] = ['id', 'nombre', 'ciudad', 'estado', 'acciones'];
  rows: SucursalDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.sucursales
      .getInternalPage({ PageNumber: this.pageIndex + 1, PageSize: this.pageSize })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  remove(guid: string, nombre: string): void {
    if (!confirm(`¿Eliminar la sucursal "${nombre}"? Esta acción no se puede deshacer.`)) return;
    this.sucursales.delete(guid).subscribe({
      next: (res) => {
        if (res.success) {
          this.snack.open('Sucursal eliminada', 'Cerrar', { duration: 3000 });
          this.load();
        }
      },
    });
  }
}

<mat-card class="mb">
  <mat-card-title>Sucursales</mat-card-title>
  <mat-card-subtitle>Listado interno: sedes enlazadas al marketplace y a inventario de habitaciones.</mat-card-subtitle>
  <mat-card-actions>
    <a mat-raised-button color="primary" routerLink="/admin/sucursales/nuevo">Nueva sucursal</a>
  </mat-card-actions>
</mat-card>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="id">
      <th mat-header-cell *matHeaderCellDef>Id</th>
      <td mat-cell *matCellDef="let r">{{ r.idSucursal }}</td>
    </ng-container>
    <ng-container matColumnDef="nombre">
      <th mat-header-cell *matHeaderCellDef>Nombre</th>
      <td mat-cell *matCellDef="let r">{{ r.nombreSucursal ?? '—' }}</td>
    </ng-container>
    <ng-container matColumnDef="ciudad">
      <th mat-header-cell *matHeaderCellDef>Ciudad</th>
      <td mat-cell *matCellDef="let r">{{ r.ciudad ?? '—' }}</td>
    </ng-container>
    <ng-container matColumnDef="estado">
      <th mat-header-cell *matHeaderCellDef>Estado</th>
      <td mat-cell *matCellDef="let r">{{ r.estadoSucursal ?? '—' }}</td>
    </ng-container>
    <ng-container matColumnDef="acciones">
      <th mat-header-cell *matHeaderCellDef></th>
      <td mat-cell *matCellDef="let r" class="acciones-cell">
        <a mat-icon-button [routerLink]="['/admin/sucursales', r.sucursalGuid]" matTooltip="Editar">
          <mat-icon>edit</mat-icon>
        </a>
        <a mat-icon-button [routerLink]="['/alojamientos', r.sucursalGuid]" target="_blank" rel="noopener" matTooltip="Ver en marketplace">
          <mat-icon>open_in_new</mat-icon>
        </a>
        <button mat-icon-button color="warn" type="button" matTooltip="Eliminar"
          (click)="remove(r.sucursalGuid, r.nombreSucursal ?? '')">
          <mat-icon>delete</mat-icon>
        </button>
      </td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[5, 10, 20]"
    (page)="onPage($event)"
  />
}

// src/views/admin/AdminSucursalesPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { sucursalesDelete, sucursalesGetInternalPage } from '@/services/sucursales';
import { useUiStore } from '@/stores/ui';
import type { SucursalDTO } from '@/models';

const ui = useUiStore();
const rows = ref<SucursalDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await sucursalesGetInternalPage({ PageNumber: pageIndex.value + 1, PageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

async function remove(s: SucursalDTO): Promise<void> {
  const nombre = s.nombreSucursal ?? s.sucursalGuid;
  if (!confirm(`¿Eliminar la sucursal "${nombre}"?`)) return;
  const res = await sucursalesDelete(s.sucursalGuid);
  if (res.success) {
    ui.showSnack('Sucursal eliminada', 3000);
    void load();
  }
}

onMounted(() => void load());
</script>

<template>
  <v-card class="mb-4">
    <v-card-title>Sucursales</v-card-title>
    <v-card-actions>
      <v-btn color="primary" to="/admin/sucursales/nuevo">Nueva</v-btn>
    </v-card-actions>
  </v-card>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Ciudad</th>
          <th>Estado</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.sucursalGuid">
          <td>{{ r.idSucursal }}</td>
          <td>{{ r.nombreSucursal }}</td>
          <td>{{ r.ciudad }}</td>
          <td>{{ r.estadoSucursal }}</td>
          <td>
            <v-btn size="small" variant="text" :to="'/admin/sucursales/' + r.sucursalGuid">Editar</v-btn>
            <v-btn size="small" variant="text" color="error" @click="remove(r)">Eliminar</v-btn>
          </td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1.5rem;
}
</style>
