// src/app/features/admin/admin-cliente-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { ClientesService } from '../../core/services/clientes.service';
import type { ClienteCreateRequest, ClienteUpdateRequest } from '../../shared/models';
import { isUuidString } from '../../shared/utils/string.util';

@Component({
  selector: 'app-admin-cliente-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-cliente-edit-page.component.html',
  styleUrl: './admin-cliente-edit-page.component.scss',
})
export class AdminClienteEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly api = inject(ClientesService);
  private readonly snack = inject(MatSnackBar);

  isCreate = false;
  clienteGuid?: string;
  loading = true;

  readonly createForm = this.fb.nonNullable.group({
    tipoIdentificacion: this.fb.control('', Validators.required),
    numeroIdentificacion: this.fb.control('', Validators.required),
    nombres: this.fb.control('', Validators.required),
    apellidos: this.fb.control(''),
    razonSocial: this.fb.control(''),
    correo: this.fb.control('', [Validators.required, Validators.email]),
    telefono: this.fb.control('', Validators.required),
    direccion: this.fb.control('', Validators.required),
    estado: this.fb.control('ACTIVO'),
  });

  readonly editForm = this.fb.nonNullable.group({
    nombres: this.fb.control(''),
    apellidos: this.fb.control(''),
    razonSocial: this.fb.control(''),
    correo: this.fb.control('', Validators.email),
    telefono: this.fb.control(''),
    direccion: this.fb.control(''),
    estado: this.fb.control(''),
  });

  ngOnInit(): void {
    if (this.route.snapshot.routeConfig?.path === 'clientes/nuevo') {
      this.isCreate = true;
      this.loading = false;
      return;
    }
    const id = this.route.snapshot.paramMap.get('guid') ?? '';
    if (!isUuidString(id)) {
      this.snack.open('GUID inválido', 'Cerrar');
      void this.router.navigate(['/admin/clientes']);
      return;
    }
    this.clienteGuid = id;
    this.api.getByGuid(id).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          const c = res.data;
          this.editForm.patchValue({
            nombres: c.nombres ?? '',
            apellidos: c.apellidos ?? '',
            razonSocial: c.razonSocial ?? '',
            correo: c.correo ?? '',
            telefono: c.telefono ?? '',
            direccion: c.direccion ?? '',
            estado: c.estado ?? '',
          });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  saveCreate(): void {
    if (this.createForm.invalid) {
      this.createForm.markAllAsTouched();
      return;
    }
    const v = this.createForm.getRawValue();
    const tipoIdentificacion = v.tipoIdentificacion?.trim();
    const numeroIdentificacion = v.numeroIdentificacion?.trim();
    const nombres = v.nombres?.trim();
    const correo = v.correo?.trim();
    const telefono = v.telefono?.trim();
    const direccion = v.direccion?.trim();
    if (!tipoIdentificacion || !numeroIdentificacion || !nombres || !correo || !telefono || !direccion) {
      return;
    }
    const body: ClienteCreateRequest = {
      tipoIdentificacion,
      numeroIdentificacion,
      nombres,
      apellidos: v.apellidos?.trim() || undefined,
      razonSocial: v.razonSocial?.trim() || undefined,
      correo,
      telefono,
      direccion,
      estado: v.estado?.trim() || undefined,
    };
    this.api.create(body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Cliente creado', 'Cerrar', { duration: 3000 });
        void this.router.navigate(['/admin/clientes']);
      }
    });
  }

  saveEdit(): void {
    if (!this.clienteGuid || this.editForm.invalid) {
      this.editForm.markAllAsTouched();
      return;
    }
    const v = this.editForm.getRawValue();
    const body: ClienteUpdateRequest = {
      nombres: v.nombres || undefined,
      apellidos: v.apellidos || undefined,
      razonSocial: v.razonSocial || undefined,
      correo: v.correo || undefined,
      telefono: v.telefono || undefined,
      direccion: v.direccion || undefined,
      estado: v.estado || undefined,
    };
    this.api.update(this.clienteGuid, body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Cliente actualizado', 'Cerrar', { duration: 3000 });
        void this.router.navigate(['/admin/clientes']);
      }
    });
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else if (isCreate) {
  <mat-card>
    <mat-card-title>Nuevo cliente</mat-card-title>
    <mat-card-content>
      <form [formGroup]="createForm" class="grid-form" (ngSubmit)="saveCreate()">
        <mat-form-field appearance="outline">
          <mat-label>Tipo identificación</mat-label>
          <input matInput formControlName="tipoIdentificacion" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Número identificación</mat-label>
          <input matInput formControlName="numeroIdentificacion" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Nombres</mat-label>
          <input matInput formControlName="nombres" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Apellidos</mat-label>
          <input matInput formControlName="apellidos" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Razón social</mat-label>
          <input matInput formControlName="razonSocial" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Correo</mat-label>
          <input matInput type="email" formControlName="correo" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Teléfono</mat-label>
          <input matInput formControlName="telefono" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Dirección</mat-label>
          <input matInput formControlName="direccion" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Estado</mat-label>
          <input matInput formControlName="estado" />
        </mat-form-field>
        <div class="actions full">
          <button mat-flat-button color="primary" type="submit">Guardar</button>
          <a mat-button routerLink="/admin/clientes">Cancelar</a>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
} @else {
  <mat-card>
    <mat-card-title>Editar cliente</mat-card-title>
    <mat-card-content>
      <form [formGroup]="editForm" class="grid-form" (ngSubmit)="saveEdit()">
        <mat-form-field appearance="outline">
          <mat-label>Nombres</mat-label>
          <input matInput formControlName="nombres" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Apellidos</mat-label>
          <input matInput formControlName="apellidos" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Razón social</mat-label>
          <input matInput formControlName="razonSocial" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Correo</mat-label>
          <input matInput type="email" formControlName="correo" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Teléfono</mat-label>
          <input matInput formControlName="telefono" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Dirección</mat-label>
          <input matInput formControlName="direccion" />
        </mat-form-field>
        <mat-form-field appearance="outline">
          <mat-label>Estado</mat-label>
          <input matInput formControlName="estado" />
        </mat-form-field>
        <div class="actions full">
          <button mat-flat-button color="primary" type="submit">Actualizar</button>
          <a mat-button routerLink="/admin/clientes">Volver</a>
        </div>
      </form>
    </mat-card-content>
  </mat-card>
}

// src/views/admin/AdminClienteEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { clientesCreate, clientesGetByGuid, clientesUpdate } from '@/services/clientes';
import { useUiStore } from '@/stores/ui';
import { isUuidString } from '@/utils/string.util';
import type { ClienteCreateRequest, ClienteUpdateRequest } from '@/models';

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const isCreate = ref(false);
const clienteGuid = ref<string | undefined>();
const loading = ref(true);

const createForm = reactive({
  tipoIdentificacion: '',
  numeroIdentificacion: '',
  nombres: '',
  apellidos: '',
  razonSocial: '',
  correo: '',
  telefono: '',
  direccion: '',
  estado: 'ACTIVO',
});

const editForm = reactive({
  nombres: '',
  apellidos: '',
  razonSocial: '',
  correo: '',
  telefono: '',
  direccion: '',
  estado: '',
});

onMounted(async () => {
  if (route.path.endsWith('/nuevo')) {
    isCreate.value = true;
    loading.value = false;
    return;
  }
  const id = String(route.params.guid ?? '');
  if (!isUuidString(id)) {
    ui.showSnack('GUID inválido', 4000);
    void router.push('/admin/clientes');
    return;
  }
  clienteGuid.value = id;
  try {
    const res = await clientesGetByGuid(id);
    if (res.success && res.data) {
      const c = res.data;
      editForm.nombres = c.nombres ?? '';
      editForm.apellidos = c.apellidos ?? '';
      editForm.razonSocial = c.razonSocial ?? '';
      editForm.correo = c.correo ?? '';
      editForm.telefono = c.telefono ?? '';
      editForm.direccion = c.direccion ?? '';
      editForm.estado = c.estado ?? '';
    }
  } finally {
    loading.value = false;
  }
});

async function saveCreate(): Promise<void> {
  const v = createForm;
  if (!v.tipoIdentificacion || !v.numeroIdentificacion || !v.nombres || !v.correo || !v.telefono || !v.direccion) {
    ui.showSnack('Completa obligatorios.', 4000);
    return;
  }
  const body: ClienteCreateRequest = {
    tipoIdentificacion: v.tipoIdentificacion.trim(),
    numeroIdentificacion: v.numeroIdentificacion.trim(),
    nombres: v.nombres.trim(),
    apellidos: v.apellidos?.trim() || undefined,
    razonSocial: v.razonSocial?.trim() || undefined,
    correo: v.correo.trim(),
    telefono: v.telefono.trim(),
    direccion: v.direccion.trim(),
    estado: v.estado?.trim() || undefined,
  };
  const res = await clientesCreate(body);
  if (res.success) {
    ui.showSnack('Cliente creado', 3000);
    void router.push('/admin/clientes');
  }
}

async function saveEdit(): Promise<void> {
  if (!clienteGuid.value) return;
  const v = editForm;
  const body: ClienteUpdateRequest = {
    nombres: v.nombres || undefined,
    apellidos: v.apellidos || undefined,
    razonSocial: v.razonSocial || undefined,
    correo: v.correo || undefined,
    telefono: v.telefono || undefined,
    direccion: v.direccion || undefined,
    estado: v.estado || undefined,
  };
  const res = await clientesUpdate(clienteGuid.value, body);
  if (res.success) {
    ui.showSnack('Cliente actualizado', 3000);
    void router.push('/admin/clientes');
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <v-card v-else-if="isCreate">
    <v-card-title>Nuevo cliente</v-card-title>
    <v-card-text>
      <v-text-field v-model="createForm.tipoIdentificacion" label="Tipo identificación" variant="outlined" />
      <v-text-field v-model="createForm.numeroIdentificacion" label="Número identificación" variant="outlined" />
      <v-text-field v-model="createForm.nombres" label="Nombres" variant="outlined" />
      <v-text-field v-model="createForm.apellidos" label="Apellidos" variant="outlined" />
      <v-text-field v-model="createForm.razonSocial" label="Razón social" variant="outlined" />
      <v-text-field v-model="createForm.correo" label="Correo" type="email" variant="outlined" />
      <v-text-field v-model="createForm.telefono" label="Teléfono" variant="outlined" />
      <v-text-field v-model="createForm.direccion" label="Dirección" variant="outlined" />
      <v-text-field v-model="createForm.estado" label="Estado" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveCreate">Crear</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/clientes">Cancelar</v-btn>
    </v-card-text>
  </v-card>
  <v-card v-else>
    <v-card-title>Editar cliente</v-card-title>
    <v-card-text>
      <v-text-field v-model="editForm.nombres" label="Nombres" variant="outlined" />
      <v-text-field v-model="editForm.apellidos" label="Apellidos" variant="outlined" />
      <v-text-field v-model="editForm.razonSocial" label="Razón social" variant="outlined" />
      <v-text-field v-model="editForm.correo" label="Correo" variant="outlined" />
      <v-text-field v-model="editForm.telefono" label="Teléfono" variant="outlined" />
      <v-text-field v-model="editForm.direccion" label="Dirección" variant="outlined" />
      <v-text-field v-model="editForm.estado" label="Estado" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveEdit">Guardar</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/clientes">Volver</v-btn>
    </v-card-text>
  </v-card>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
</style>
