// src/app/features/admin/admin-alojamientos-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { AlojamientosService } from '../../core/services/alojamientos.service';
import type { AlojamientoResponseDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-alojamientos-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatTableModule, MatButtonModule, MatPaginatorModule, MatProgressSpinnerModule],
  templateUrl: './admin-alojamientos-page.component.html',
  styleUrl: './admin-alojamientos-page.component.scss',
})
export class AdminAlojamientosPageComponent implements OnInit {
  private readonly aloj = inject(AlojamientosService);

  displayedColumns: string[] = ['id', 'nombre', 'ciudad', 'acciones'];
  rows: AlojamientoResponseDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.aloj
      .buscar({
        pageNumber: this.pageIndex + 1,
        pageSize: this.pageSize,
      })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  remove(id: number): void {
    if (!confirm('¿Eliminar alojamiento?')) {
      return;
    }
    this.aloj.delete(id).subscribe();
  }
}

<mat-card class="mb">
  <mat-card-title>Alojamientos (admin)</mat-card-title>
  <mat-card-subtitle>Búsqueda, alta y mantenimiento del catálogo interno de propiedades.</mat-card-subtitle>
  <mat-card-actions>
    <a mat-raised-button color="primary" routerLink="/admin/alojamientos/nuevo">Nuevo</a>
  </mat-card-actions>
</mat-card>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="id">
      <th mat-header-cell *matHeaderCellDef>Id</th>
      <td mat-cell *matCellDef="let r">{{ r.alojamientoID }}</td>
    </ng-container>
    <ng-container matColumnDef="nombre">
      <th mat-header-cell *matHeaderCellDef>Nombre</th>
      <td mat-cell *matCellDef="let r">{{ r.nombre }}</td>
    </ng-container>
    <ng-container matColumnDef="ciudad">
      <th mat-header-cell *matHeaderCellDef>Ciudad</th>
      <td mat-cell *matCellDef="let r">{{ r.ciudad }}</td>
    </ng-container>
    <ng-container matColumnDef="acciones">
      <th mat-header-cell *matHeaderCellDef></th>
      <td mat-cell *matCellDef="let r">
        <a mat-button [routerLink]="['/admin/alojamientos', r.alojamientoID]">Editar</a>
        <button mat-button type="button" (click)="remove(r.alojamientoID)">Eliminar</button>
      </td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[5, 10, 20]"
    (page)="onPage($event)"
  />
}

// src/views/admin/AdminAlojamientosPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { alojamientosBuscar, alojamientosDelete } from '@/services/alojamientos';
import { useUiStore } from '@/stores/ui';
import type { AlojamientoResponseDTO } from '@/models';

const ui = useUiStore();
const rows = ref<AlojamientoResponseDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await alojamientosBuscar({ pageNumber: pageIndex.value + 1, pageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

async function remove(id: number): Promise<void> {
  if (!confirm('¿Eliminar alojamiento?')) return;
  await alojamientosDelete(id);
}

onMounted(() => void load());
</script>

<template>
  <v-card class="mb-4">
    <v-card-title>Alojamientos (admin)</v-card-title>
    <v-card-subtitle>Búsqueda, alta y mantenimiento del catálogo interno de propiedades.</v-card-subtitle>
    <v-card-actions>
      <v-btn color="primary" to="/admin/alojamientos/nuevo">Nuevo</v-btn>
    </v-card-actions>
  </v-card>
  <div v-if="loading" class="center">
    <v-progress-circular indeterminate />
  </div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Id</th>
          <th>Nombre</th>
          <th>Ciudad</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.alojamientoID">
          <td>{{ r.alojamientoID }}</td>
          <td>{{ r.nombre }}</td>
          <td>{{ r.ciudad }}</td>
          <td>
            <v-btn size="small" variant="text" :to="'/admin/alojamientos/' + r.alojamientoID">Editar</v-btn>
            <v-btn size="small" variant="text" color="error" @click="remove(r.alojamientoID)">Eliminar</v-btn>
          </td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1.5rem;
}
</style>
