// src/app/features/admin/admin-alojamiento-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AlojamientosService } from '../../core/services/alojamientos.service';
import { isPositiveIntString } from '../../shared/utils/string.util';
import type { CreateAlojamientoDTO, UpdateAlojamientoDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-alojamiento-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-alojamiento-edit-page.component.html',
  styleUrl: './admin-alojamiento-edit-page.component.scss',
})
export class AdminAlojamientoEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly aloj = inject(AlojamientosService);
  private readonly snack = inject(MatSnackBar);

  readonly createForm = this.fb.nonNullable.group({
    tipoAlojID: this.fb.control<number | null>(null, Validators.required),
    adminUsuarioID: this.fb.control<number | null>(null, Validators.required),
    nombre: this.fb.control('', Validators.required),
    descripcion: this.fb.control(''),
    direccion: this.fb.control(''),
    ciudad: this.fb.control(''),
    provincia: this.fb.control(''),
    pais: this.fb.control(''),
  });

  readonly editForm = this.fb.nonNullable.group({
    nombre: this.fb.control(''),
    descripcion: this.fb.control(''),
    direccion: this.fb.control(''),
    ciudad: this.fb.control(''),
    provincia: this.fb.control(''),
    pais: this.fb.control(''),
    estadoAlojamiento: this.fb.control(''),
  });

  isCreate = false;
  alojamientoId?: number;
  loading = true;

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id') ?? '';
    if (id === 'nuevo') {
      this.isCreate = true;
      this.loading = false;
      return;
    }
    if (!isPositiveIntString(id)) {
      this.snack.open('Id inválido', 'Cerrar');
      void this.router.navigate(['/admin/alojamientos']);
      return;
    }
    this.alojamientoId = Number(id);
    this.aloj.getById(this.alojamientoId).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          const a = res.data;
          this.editForm.patchValue({
            nombre: a.nombre ?? '',
            descripcion: a.descripcion ?? '',
            direccion: a.direccion ?? '',
            ciudad: a.ciudad ?? '',
            provincia: a.provincia ?? '',
            pais: a.pais ?? '',
            estadoAlojamiento: a.estadoAlojamiento ?? '',
          });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  saveCreate(): void {
    if (this.createForm.invalid) {
      this.createForm.markAllAsTouched();
      return;
    }
    const v = this.createForm.getRawValue();
    const body: CreateAlojamientoDTO = {
      tipoAlojID: v.tipoAlojID!,
      adminUsuarioID: v.adminUsuarioID!,
      nombre: v.nombre,
      descripcion: v.descripcion || undefined,
      direccion: v.direccion || undefined,
      ciudad: v.ciudad || undefined,
      provincia: v.provincia || undefined,
      pais: v.pais || undefined,
    };
    this.aloj.create(body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Creado', 'Cerrar', { duration: 3000 });
        void this.router.navigate(['/admin/alojamientos']);
      }
    });
  }

  saveEdit(): void {
    if (!this.alojamientoId) {
      return;
    }
    const v = this.editForm.getRawValue();
    const body: UpdateAlojamientoDTO = {
      alojamientoID: this.alojamientoId,
      nombre: v.nombre || undefined,
      descripcion: v.descripcion || undefined,
      direccion: v.direccion || undefined,
      ciudad: v.ciudad || undefined,
      provincia: v.provincia || undefined,
      pais: v.pais || undefined,
      estadoAlojamiento: v.estadoAlojamiento || undefined,
    };
    this.aloj.update(this.alojamientoId, body).subscribe((res) => {
      if (res.success) {
        this.snack.open('Guardado', 'Cerrar', { duration: 3000 });
        void this.router.navigate(['/admin/alojamientos']);
      }
    });
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else if (isCreate) {
  <mat-card>
    <mat-card-title>Nuevo alojamiento</mat-card-title>
    <mat-card-content>
      <form [formGroup]="createForm" (ngSubmit)="saveCreate()">
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>tipoAlojID</mat-label>
            <input matInput type="number" formControlName="tipoAlojID" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>adminUsuarioID</mat-label>
            <input matInput type="number" formControlName="adminUsuarioID" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Nombre</mat-label>
          <input matInput formControlName="nombre" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="2" formControlName="descripcion"></textarea>
        </mat-form-field>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Dirección</mat-label>
            <input matInput formControlName="direccion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Ciudad</mat-label>
            <input matInput formControlName="ciudad" />
          </mat-form-field>
        </div>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Provincia</mat-label>
            <input matInput formControlName="provincia" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>País</mat-label>
            <input matInput formControlName="pais" />
          </mat-form-field>
        </div>
        <button mat-raised-button color="primary" type="submit" [disabled]="createForm.invalid">Crear</button>
        <a mat-button routerLink="/admin/alojamientos">Cancelar</a>
      </form>
    </mat-card-content>
  </mat-card>
} @else {
  <mat-card>
    <mat-card-title>Editar alojamiento #{{ alojamientoId }}</mat-card-title>
    <mat-card-content>
      <form [formGroup]="editForm" (ngSubmit)="saveEdit()">
        <mat-form-field appearance="outline" class="full">
          <mat-label>Nombre</mat-label>
          <input matInput formControlName="nombre" />
        </mat-form-field>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="2" formControlName="descripcion"></textarea>
        </mat-form-field>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Dirección</mat-label>
            <input matInput formControlName="direccion" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Ciudad</mat-label>
            <input matInput formControlName="ciudad" />
          </mat-form-field>
        </div>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Provincia</mat-label>
            <input matInput formControlName="provincia" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>País</mat-label>
            <input matInput formControlName="pais" />
          </mat-form-field>
        </div>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Estado alojamiento</mat-label>
          <input matInput formControlName="estadoAlojamiento" />
        </mat-form-field>
        <button mat-raised-button color="primary" type="submit">Guardar</button>
        <a mat-button routerLink="/admin/alojamientos">Volver</a>
      </form>
    </mat-card-content>
  </mat-card>
}

// src/views/admin/AdminAlojamientoEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { alojamientosCreate, alojamientosGetById, alojamientosUpdate } from '@/services/alojamientos';
import { useUiStore } from '@/stores/ui';
import { isPositiveIntString } from '@/utils/string.util';
import type { CreateAlojamientoDTO, UpdateAlojamientoDTO } from '@/models';

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const isCreate = ref(false);
const alojamientoId = ref<number | undefined>();
const loading = ref(true);

const createForm = reactive({
  tipoAlojID: null as number | null,
  adminUsuarioID: null as number | null,
  nombre: '',
  descripcion: '',
  direccion: '',
  ciudad: '',
  provincia: '',
  pais: '',
});

const editForm = reactive({
  nombre: '',
  descripcion: '',
  direccion: '',
  ciudad: '',
  provincia: '',
  pais: '',
  estadoAlojamiento: '',
});

onMounted(async () => {
  const id = String(route.params.id ?? '');
  if (id === 'nuevo') {
    isCreate.value = true;
    loading.value = false;
    return;
  }
  if (!isPositiveIntString(id)) {
    ui.showSnack('Id inválido', 4000);
    void router.push('/admin/alojamientos');
    return;
  }
  alojamientoId.value = Number(id);
  try {
    const res = await alojamientosGetById(alojamientoId.value);
    if (res.success && res.data) {
      const a = res.data;
      editForm.nombre = a.nombre ?? '';
      editForm.descripcion = a.descripcion ?? '';
      editForm.direccion = a.direccion ?? '';
      editForm.ciudad = a.ciudad ?? '';
      editForm.provincia = a.provincia ?? '';
      editForm.pais = a.pais ?? '';
      editForm.estadoAlojamiento = a.estadoAlojamiento ?? '';
    }
  } finally {
    loading.value = false;
  }
});

async function saveCreate(): Promise<void> {
  if (
    createForm.tipoAlojID == null ||
    createForm.adminUsuarioID == null ||
    !createForm.nombre
  ) {
    ui.showSnack('Completa tipo, admin y nombre.', 4000);
    return;
  }
  const body: CreateAlojamientoDTO = {
    tipoAlojID: createForm.tipoAlojID,
    adminUsuarioID: createForm.adminUsuarioID,
    nombre: createForm.nombre,
    descripcion: createForm.descripcion || undefined,
    direccion: createForm.direccion || undefined,
    ciudad: createForm.ciudad || undefined,
    provincia: createForm.provincia || undefined,
    pais: createForm.pais || undefined,
  };
  const res = await alojamientosCreate(body);
  if (res.success) {
    ui.showSnack('Creado', 3000);
    void router.push('/admin/alojamientos');
  }
}

async function saveEdit(): Promise<void> {
  if (!alojamientoId.value) return;
  const v = editForm;
  const body: UpdateAlojamientoDTO = {
    alojamientoID: alojamientoId.value,
    nombre: v.nombre || undefined,
    descripcion: v.descripcion || undefined,
    direccion: v.direccion || undefined,
    ciudad: v.ciudad || undefined,
    provincia: v.provincia || undefined,
    pais: v.pais || undefined,
    estadoAlojamiento: v.estadoAlojamiento || undefined,
  };
  const res = await alojamientosUpdate(alojamientoId.value, body);
  if (res.success) {
    ui.showSnack('Guardado', 3000);
    void router.push('/admin/alojamientos');
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <v-card v-else-if="isCreate">
    <v-card-title>Nuevo alojamiento</v-card-title>
    <v-card-text>
      <v-text-field v-model.number="createForm.tipoAlojID" label="tipoAlojID" type="number" variant="outlined" />
      <v-text-field v-model.number="createForm.adminUsuarioID" label="adminUsuarioID" type="number" variant="outlined" />
      <v-text-field v-model="createForm.nombre" label="Nombre" variant="outlined" />
      <v-textarea v-model="createForm.descripcion" label="Descripción" variant="outlined" />
      <v-text-field v-model="createForm.direccion" label="Dirección" variant="outlined" />
      <v-text-field v-model="createForm.ciudad" label="Ciudad" variant="outlined" />
      <v-text-field v-model="createForm.provincia" label="Provincia" variant="outlined" />
      <v-text-field v-model="createForm.pais" label="País" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveCreate">Crear</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/alojamientos">Cancelar</v-btn>
    </v-card-text>
  </v-card>
  <v-card v-else>
    <v-card-title>Editar alojamiento #{{ alojamientoId }}</v-card-title>
    <v-card-text>
      <v-text-field v-model="editForm.nombre" label="Nombre" variant="outlined" />
      <v-textarea v-model="editForm.descripcion" label="Descripción" variant="outlined" />
      <v-text-field v-model="editForm.direccion" label="Dirección" variant="outlined" />
      <v-text-field v-model="editForm.ciudad" label="Ciudad" variant="outlined" />
      <v-text-field v-model="editForm.provincia" label="Provincia" variant="outlined" />
      <v-text-field v-model="editForm.pais" label="País" variant="outlined" />
      <v-text-field v-model="editForm.estadoAlojamiento" label="Estado alojamiento" variant="outlined" />
      <v-btn color="primary" class="mt-2" @click="saveEdit">Guardar</v-btn>
      <v-btn class="mt-2 ms-2" variant="text" to="/admin/alojamientos">Volver</v-btn>
    </v-card-text>
  </v-card>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
</style>
