// src/app/features/admin/admin-home-page.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-admin-home-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatButtonModule, MatIconModule],
  templateUrl: './admin-home-page.component.html',
  styleUrl: './admin-home-page.component.scss',
})
export class AdminHomePageComponent {}

<h1 class="admin-dash__title">Resumen operativo</h1>
<p class="admin-dash__lede">
  Gestiona inventario, habitaciones y reservas desde un único lugar. Cada módulo enlaza al flujo de trabajo correspondiente.
</p>

<div class="admin-dash__grid">
  <mat-card class="admin-dash__card">
    <mat-card-header>
      <div mat-card-avatar class="admin-dash__avatar admin-dash__avatar--aloj">
        <mat-icon>holiday_village</mat-icon>
      </div>
      <mat-card-title>Alojamientos</mat-card-title>
      <mat-card-subtitle>Catálogo y datos maestros</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <p>Alta, edición y consulta de propiedades publicadas hacia el marketplace.</p>
    </mat-card-content>
    <mat-card-actions align="end">
      <a mat-flat-button color="primary" routerLink="/admin/alojamientos">Abrir módulo</a>
    </mat-card-actions>
  </mat-card>

  <mat-card class="admin-dash__card">
    <mat-card-header>
      <div mat-card-avatar class="admin-dash__avatar admin-dash__avatar--room">
        <mat-icon>bed</mat-icon>
      </div>
      <mat-card-title>Habitaciones</mat-card-title>
      <mat-card-subtitle>Tipos, tarifas y disponibilidad</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <p>Mantén coherencia entre tipología de habitación y oferta mostrada al huésped.</p>
    </mat-card-content>
    <mat-card-actions align="end">
      <a mat-flat-button color="primary" routerLink="/admin/habitaciones">Abrir módulo</a>
    </mat-card-actions>
  </mat-card>

  <mat-card class="admin-dash__card">
    <mat-card-header>
      <div mat-card-avatar class="admin-dash__avatar admin-dash__avatar--book">
        <mat-icon>event_note</mat-icon>
      </div>
      <mat-card-title>Reservas</mat-card-title>
      <mat-card-subtitle>Seguimiento y documentos</mat-card-subtitle>
    </mat-card-header>
    <mat-card-content>
      <p>Consulta reservas internas, estados y totales para coordinar recepción.</p>
    </mat-card-content>
    <mat-card-actions align="end">
      <a mat-flat-button color="primary" routerLink="/admin/reservas">Abrir módulo</a>
    </mat-card-actions>
  </mat-card>
</div>

// src/views/admin/AdminHomePage.vue
<template>
  <h1 class="admin-dash__title">Centro de administración</h1>
  <p class="admin-dash__lede">
    Operación completa del negocio. La <strong>vista huésped</strong> es el sitio público donde los clientes buscan y
    reservan.
  </p>
  <div class="admin-dash__grid">
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="primary" icon="mdi-bed" /></template>
        <v-card-title>Hoteles</v-card-title>
        <v-card-subtitle>Alta y administración de hoteles</v-card-subtitle>
      </v-card-item>
      <v-card-text>Crea, edita y gestiona los hoteles registrados en la plataforma.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn variant="outlined" to="/admin/hoteles/nuevo">Nuevo hotel</v-btn>
        <v-btn color="primary" to="/admin/hoteles">Listado</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="secondary" icon="mdi-home-city" /></template>
        <v-card-title>Alojamientos</v-card-title>
        <v-card-subtitle>Catálogo y datos maestros</v-card-subtitle>
      </v-card-item>
      <v-card-text>Alta, edición y consulta de propiedades.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn color="primary" to="/admin/alojamientos">Abrir módulo</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="teal" icon="mdi-bed-king" /></template>
        <v-card-title>Habitaciones</v-card-title>
        <v-card-subtitle>Inventario y tarifas</v-card-subtitle>
      </v-card-item>
      <v-card-text>Mantenimiento del inventario mostrado al huésped.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn color="primary" to="/admin/habitaciones">Abrir módulo</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="info" icon="mdi-calendar-edit" /></template>
        <v-card-title>Reservas</v-card-title>
        <v-card-subtitle>Seguimiento</v-card-subtitle>
      </v-card-item>
      <v-card-text>Consulta y edición de reservas.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn color="primary" to="/admin/reservas">Abrir módulo</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="purple" icon="mdi-account-group" /></template>
        <v-card-title>Clientes</v-card-title>
        <v-card-subtitle>CRUD de huéspedes</v-card-subtitle>
      </v-card-item>
      <v-card-text>Alta y edición de clientes.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn color="primary" to="/admin/clientes">Abrir módulo</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="indigo" icon="mdi-domain" /></template>
        <v-card-title>Sucursales</v-card-title>
        <v-card-subtitle>Sedes y publicación</v-card-subtitle>
      </v-card-item>
      <v-card-text>Ubicaciones operativas del catálogo público.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn variant="outlined" to="/admin/sucursales/nuevo">Nueva sucursal</v-btn>
        <v-btn color="primary" to="/admin/sucursales">Listado</v-btn>
      </v-card-actions>
    </v-card>
    <v-card class="admin-dash__card">
      <v-card-item>
        <template #prepend><v-avatar color="deep-orange" icon="mdi-shape" /></template>
        <v-card-title>Tipos de habitación</v-card-title>
        <v-card-subtitle>Catálogo maestro</v-card-subtitle>
      </v-card-item>
      <v-card-text>Tipologías usadas al definir habitaciones.</v-card-text>
      <v-card-actions class="justify-end">
        <v-btn color="primary" to="/admin/tipos-habitacion">Abrir módulo</v-btn>
      </v-card-actions>
    </v-card>
  </div>
</template>

<style scoped src="./admin-home-page.scss"></style>
