// src/app/features/admin/admin-hotel-edit-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatDividerModule } from '@angular/material/divider';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSelectModule } from '@angular/material/select';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AlojamientosService } from '../../core/services/alojamientos.service';
import { isPositiveIntString } from '../../shared/utils/string.util';
import type { CreateAlojamientoDTO, UpdateAlojamientoDTO } from '../../shared/models';

const ESTADOS = ['Activo', 'Inactivo', 'Suspendido', 'EnRevision'] as const;

@Component({
  selector: 'app-admin-hotel-edit-page',
  standalone: true,
  imports: [
    RouterLink,
    ReactiveFormsModule,
    MatCardModule,
    MatFormFieldModule,
    MatInputModule,
    MatButtonModule,
    MatIconModule,
    MatSelectModule,
    MatDividerModule,
    MatProgressSpinnerModule,
    MatSnackBarModule,
  ],
  templateUrl: './admin-hotel-edit-page.component.html',
  styleUrl: './admin-hotel-edit-page.component.scss',
})
export class AdminHotelEditPageComponent implements OnInit {
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);
  private readonly fb = inject(FormBuilder);
  private readonly aloj = inject(AlojamientosService);
  private readonly snack = inject(MatSnackBar);

  readonly estados = ESTADOS;

  readonly form = this.fb.nonNullable.group({
    // Campos de creación
    tipoAlojID: this.fb.control<number | null>(null),
    adminUsuarioID: this.fb.control<number | null>(null),
    // Campos compartidos
    nombre: this.fb.control('', Validators.required),
    slug: this.fb.control(''),
    ruc: this.fb.control(''),
    numRegistroTurismo: this.fb.control(''),
    categoria: this.fb.control<number | null>(null),
    descripcion: this.fb.control(''),
    direccion: this.fb.control(''),
    ciudad: this.fb.control(''),
    provincia: this.fb.control(''),
    pais: this.fb.control(''),
    latitud: this.fb.control<number | null>(null),
    longitud: this.fb.control<number | null>(null),
    telefono: this.fb.control(''),
    email: this.fb.control('', Validators.email),
    sitioWeb: this.fb.control(''),
    horaCheckIn: this.fb.control(''),
    horaCheckOut: this.fb.control(''),
    politicaCancelacion: this.fb.control(''),
    estadoAlojamiento: this.fb.control(''),
  });

  isCreate = false;
  hotelId?: number;
  loading = true;
  guardando = false;

  ngOnInit(): void {
    const id = this.route.snapshot.paramMap.get('id') ?? '';
    if (id === 'nuevo') {
      this.isCreate = true;
      this.form.controls.tipoAlojID.addValidators(Validators.required);
      this.form.controls.adminUsuarioID.addValidators(Validators.required);
      this.loading = false;
      return;
    }
    if (!isPositiveIntString(id)) {
      this.snack.open('Id inválido', 'Cerrar');
      void this.router.navigate(['/admin/hoteles']);
      return;
    }
    this.hotelId = Number(id);
    this.aloj.getById(this.hotelId).subscribe({
      next: (res) => {
        if (res.success && res.data) {
          const h = res.data;
          this.form.patchValue({
            nombre: h.nombre ?? '',
            slug: h.slug ?? '',
            ruc: h.ruc ?? '',
            numRegistroTurismo: h.numRegistroTurismo ?? '',
            categoria: h.categoria ?? null,
            descripcion: h.descripcion ?? '',
            direccion: h.direccion ?? '',
            ciudad: h.ciudad ?? '',
            provincia: h.provincia ?? '',
            pais: h.pais ?? '',
            latitud: h.latitud ?? null,
            longitud: h.longitud ?? null,
            telefono: h.telefono ?? '',
            email: h.email ?? '',
            sitioWeb: h.sitioWeb ?? '',
            horaCheckIn: h.horaCheckIn ?? '',
            horaCheckOut: h.horaCheckOut ?? '',
            politicaCancelacion: h.politicaCancelacion ?? '',
            estadoAlojamiento: h.estadoAlojamiento ?? '',
          });
        }
        this.loading = false;
      },
      error: () => (this.loading = false),
    });
  }

  save(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.isCreate ? this.doCreate() : this.doUpdate();
  }

  private doCreate(): void {
    this.guardando = true;
    const v = this.form.getRawValue();
    const body: CreateAlojamientoDTO = {
      tipoAlojID: v.tipoAlojID ?? undefined,
      adminUsuarioID: v.adminUsuarioID ?? undefined,
      nombre: v.nombre || undefined,
      slug: v.slug || undefined,
      ruc: v.ruc || undefined,
      numRegistroTurismo: v.numRegistroTurismo || undefined,
      categoria: v.categoria ?? undefined,
      descripcion: v.descripcion || undefined,
      direccion: v.direccion || undefined,
      ciudad: v.ciudad || undefined,
      provincia: v.provincia || undefined,
      pais: v.pais || undefined,
      latitud: v.latitud ?? undefined,
      longitud: v.longitud ?? undefined,
      telefono: v.telefono || undefined,
      email: v.email || undefined,
      sitioWeb: v.sitioWeb || undefined,
      horaCheckIn: v.horaCheckIn || undefined,
      horaCheckOut: v.horaCheckOut || undefined,
      politicaCancelacion: v.politicaCancelacion || undefined,
    };
    this.aloj.create(body).subscribe({
      next: (res) => {
        this.guardando = false;
        if (res.success) {
          this.snack.open('Hotel creado correctamente', 'Cerrar', { duration: 3000 });
          void this.router.navigate(['/admin/hoteles']);
        }
      },
      error: () => (this.guardando = false),
    });
  }

  private doUpdate(): void {
    if (!this.hotelId) return;
    this.guardando = true;
    const v = this.form.getRawValue();
    const body: UpdateAlojamientoDTO = {
      alojamientoID: this.hotelId,
      nombre: v.nombre || undefined,
      descripcion: v.descripcion || undefined,
      direccion: v.direccion || undefined,
      ciudad: v.ciudad || undefined,
      provincia: v.provincia || undefined,
      pais: v.pais || undefined,
      latitud: v.latitud ?? undefined,
      longitud: v.longitud ?? undefined,
      telefono: v.telefono || undefined,
      email: v.email || undefined,
      sitioWeb: v.sitioWeb || undefined,
      horaCheckIn: v.horaCheckIn || undefined,
      horaCheckOut: v.horaCheckOut || undefined,
      politicaCancelacion: v.politicaCancelacion || undefined,
      estadoAlojamiento: v.estadoAlojamiento || undefined,
    };
    this.aloj.update(this.hotelId, body).subscribe({
      next: (res) => {
        this.guardando = false;
        if (res.success) {
          this.snack.open('Hotel actualizado correctamente', 'Cerrar', { duration: 3000 });
          void this.router.navigate(['/admin/hoteles']);
        }
      },
      error: () => (this.guardando = false),
    });
  }
}

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <form [formGroup]="form" (ngSubmit)="save()">

    <!-- Encabezado -->
    <mat-card class="section-card">
      <mat-card-header>
        <mat-icon mat-card-avatar>hotel</mat-icon>
        <mat-card-title>{{ isCreate ? 'Nuevo hotel' : 'Editar hotel #' + hotelId }}</mat-card-title>
        <mat-card-subtitle>{{ isCreate ? 'Completa los datos del nuevo hotel.' : 'Modifica los campos que deseas actualizar.' }}</mat-card-subtitle>
      </mat-card-header>
    </mat-card>

    <!-- Sección: Datos de registro -->
    @if (isCreate) {
      <mat-card class="section-card">
        <mat-card-header>
          <mat-card-title class="section-title">
            <mat-icon>manage_accounts</mat-icon> Datos de registro
          </mat-card-title>
        </mat-card-header>
        <mat-card-content>
          <div class="row">
            <mat-form-field appearance="outline">
              <mat-label>Tipo de alojamiento (tipoAlojID)</mat-label>
              <input matInput type="number" formControlName="tipoAlojID" />
              @if (form.controls.tipoAlojID.hasError('required')) {
                <mat-error>Campo obligatorio</mat-error>
              }
            </mat-form-field>
            <mat-form-field appearance="outline">
              <mat-label>ID administrador (adminUsuarioID)</mat-label>
              <input matInput type="number" formControlName="adminUsuarioID" />
              @if (form.controls.adminUsuarioID.hasError('required')) {
                <mat-error>Campo obligatorio</mat-error>
              }
            </mat-form-field>
          </div>
        </mat-card-content>
      </mat-card>
    }

    <!-- Sección: Información general -->
    <mat-card class="section-card">
      <mat-card-header>
        <mat-card-title class="section-title">
          <mat-icon>info</mat-icon> Información general
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Nombre del hotel</mat-label>
          <input matInput formControlName="nombre" />
          @if (form.controls.nombre.hasError('required')) {
            <mat-error>El nombre es obligatorio</mat-error>
          }
        </mat-form-field>

        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Slug (URL amigable)</mat-label>
            <input matInput formControlName="slug" placeholder="mi-gran-hotel" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Categoría (estrellas)</mat-label>
            <mat-select formControlName="categoria">
              <mat-option [value]="null">— Sin categoría —</mat-option>
              @for (n of [1,2,3,4,5]; track n) {
                <mat-option [value]="n">{{ n }} ★</mat-option>
              }
            </mat-select>
          </mat-form-field>
        </div>

        <mat-form-field appearance="outline" class="full">
          <mat-label>Descripción</mat-label>
          <textarea matInput rows="3" formControlName="descripcion"></textarea>
        </mat-form-field>

        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>RUC / NIF fiscal</mat-label>
            <input matInput formControlName="ruc" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>N.º registro turismo</mat-label>
            <input matInput formControlName="numRegistroTurismo" />
          </mat-form-field>
        </div>

        @if (!isCreate) {
          <mat-form-field appearance="outline" class="full">
            <mat-label>Estado del alojamiento</mat-label>
            <mat-select formControlName="estadoAlojamiento">
              <mat-option value="">— Sin cambio —</mat-option>
              @for (e of estados; track e) {
                <mat-option [value]="e">{{ e }}</mat-option>
              }
            </mat-select>
          </mat-form-field>
        }
      </mat-card-content>
    </mat-card>

    <!-- Sección: Contacto y ubicación -->
    <mat-card class="section-card">
      <mat-card-header>
        <mat-card-title class="section-title">
          <mat-icon>location_on</mat-icon> Ubicación y contacto
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <mat-form-field appearance="outline" class="full">
          <mat-label>Dirección</mat-label>
          <input matInput formControlName="direccion" />
        </mat-form-field>

        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Ciudad</mat-label>
            <input matInput formControlName="ciudad" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Provincia / Estado</mat-label>
            <input matInput formControlName="provincia" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>País</mat-label>
            <input matInput formControlName="pais" />
          </mat-form-field>
        </div>

        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Latitud</mat-label>
            <input matInput type="number" step="any" formControlName="latitud" placeholder="p. ej. -0.2299" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Longitud</mat-label>
            <input matInput type="number" step="any" formControlName="longitud" placeholder="p. ej. -78.5249" />
          </mat-form-field>
        </div>

        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Teléfono</mat-label>
            <mat-icon matPrefix>phone</mat-icon>
            <input matInput formControlName="telefono" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Email</mat-label>
            <mat-icon matPrefix>email</mat-icon>
            <input matInput type="email" formControlName="email" />
            @if (form.controls.email.hasError('email')) {
              <mat-error>Formato de email inválido</mat-error>
            }
          </mat-form-field>
        </div>

        <mat-form-field appearance="outline" class="full">
          <mat-label>Sitio web</mat-label>
          <mat-icon matPrefix>language</mat-icon>
          <input matInput formControlName="sitioWeb" placeholder="https://www.mihotel.com" />
        </mat-form-field>
      </mat-card-content>
    </mat-card>

    <!-- Sección: Operación -->
    <mat-card class="section-card">
      <mat-card-header>
        <mat-card-title class="section-title">
          <mat-icon>schedule</mat-icon> Horarios y políticas
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <div class="row">
          <mat-form-field appearance="outline">
            <mat-label>Hora de check-in</mat-label>
            <input matInput formControlName="horaCheckIn" placeholder="14:00" />
          </mat-form-field>
          <mat-form-field appearance="outline">
            <mat-label>Hora de check-out</mat-label>
            <input matInput formControlName="horaCheckOut" placeholder="12:00" />
          </mat-form-field>
        </div>

        <mat-form-field appearance="outline" class="full">
          <mat-label>Política de cancelación</mat-label>
          <textarea matInput rows="3" formControlName="politicaCancelacion"
            placeholder="Describe las condiciones de cancelación del hotel…"></textarea>
        </mat-form-field>
      </mat-card-content>
    </mat-card>

    <!-- Acciones -->
    <div class="actions-bar">
      <button mat-raised-button color="primary" type="submit" [disabled]="guardando || form.invalid">
        @if (guardando) {
          <mat-spinner diameter="18" />
        } @else {
          <mat-icon>save</mat-icon>
        }
        {{ isCreate ? 'Crear hotel' : 'Guardar cambios' }}
      </button>
      <a mat-stroked-button routerLink="/admin/hoteles">
        <mat-icon>arrow_back</mat-icon>
        Volver
      </a>
    </div>

  </form>
}

// src/views/admin/AdminHotelEditPage.vue
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { alojamientosCreate, alojamientosGetById, alojamientosUpdate } from '@/services/alojamientos';
import { useUiStore } from '@/stores/ui';
import { isPositiveIntString } from '@/utils/string.util';
import type { CreateAlojamientoDTO, UpdateAlojamientoDTO } from '@/models';

const ESTADOS = ['Activo', 'Inactivo', 'Suspendido', 'EnRevision'] as const;

const route = useRoute();
const router = useRouter();
const ui = useUiStore();

const estados: string[] = [...ESTADOS];
const isCreate = ref(false);
const hotelId = ref<number | undefined>();
const loading = ref(true);
const guardando = ref(false);

const form = reactive({
  tipoAlojID: null as number | null,
  adminUsuarioID: null as number | null,
  nombre: '',
  slug: '',
  ruc: '',
  numRegistroTurismo: '',
  categoria: null as number | null,
  descripcion: '',
  direccion: '',
  ciudad: '',
  provincia: '',
  pais: '',
  latitud: null as number | null,
  longitud: null as number | null,
  telefono: '',
  email: '',
  sitioWeb: '',
  horaCheckIn: '',
  horaCheckOut: '',
  politicaCancelacion: '',
  estadoAlojamiento: '',
});

onMounted(async () => {
  const id = String(route.params.id ?? '');
  if (id === 'nuevo') {
    isCreate.value = true;
    loading.value = false;
    return;
  }
  if (!isPositiveIntString(id)) {
    ui.showSnack('Id inválido', 4000);
    void router.push('/admin/hoteles');
    return;
  }
  hotelId.value = Number(id);
  try {
    const res = await alojamientosGetById(hotelId.value);
    if (res.success && res.data) {
      const h = res.data;
      form.nombre = h.nombre ?? '';
      form.slug = h.slug ?? '';
      form.ruc = h.ruc ?? '';
      form.numRegistroTurismo = h.numRegistroTurismo ?? '';
      form.categoria = h.categoria ?? null;
      form.descripcion = h.descripcion ?? '';
      form.direccion = h.direccion ?? '';
      form.ciudad = h.ciudad ?? '';
      form.provincia = h.provincia ?? '';
      form.pais = h.pais ?? '';
      form.latitud = h.latitud ?? null;
      form.longitud = h.longitud ?? null;
      form.telefono = h.telefono ?? '';
      form.email = h.email ?? '';
      form.sitioWeb = h.sitioWeb ?? '';
      form.horaCheckIn = h.horaCheckIn ?? '';
      form.horaCheckOut = h.horaCheckOut ?? '';
      form.politicaCancelacion = h.politicaCancelacion ?? '';
      form.estadoAlojamiento = h.estadoAlojamiento ?? '';
    }
  } finally {
    loading.value = false;
  }
});

async function save(): Promise<void> {
  if (!form.nombre) {
    ui.showSnack('El nombre es obligatorio.', 4000);
    return;
  }
  if (isCreate.value && (form.tipoAlojID == null || form.adminUsuarioID == null)) {
    ui.showSnack('tipoAlojID y adminUsuarioID son obligatorios al crear.', 4000);
    return;
  }
  guardando.value = true;
  try {
    if (isCreate.value) {
      const v = form;
      const body: CreateAlojamientoDTO = {
        tipoAlojID: v.tipoAlojID ?? undefined,
        adminUsuarioID: v.adminUsuarioID ?? undefined,
        nombre: v.nombre || undefined,
        slug: v.slug || undefined,
        ruc: v.ruc || undefined,
        numRegistroTurismo: v.numRegistroTurismo || undefined,
        categoria: v.categoria ?? undefined,
        descripcion: v.descripcion || undefined,
        direccion: v.direccion || undefined,
        ciudad: v.ciudad || undefined,
        provincia: v.provincia || undefined,
        pais: v.pais || undefined,
        latitud: v.latitud ?? undefined,
        longitud: v.longitud ?? undefined,
        telefono: v.telefono || undefined,
        email: v.email || undefined,
        sitioWeb: v.sitioWeb || undefined,
        horaCheckIn: v.horaCheckIn || undefined,
        horaCheckOut: v.horaCheckOut || undefined,
        politicaCancelacion: v.politicaCancelacion || undefined,
      };
      const res = await alojamientosCreate(body);
      if (res.success) {
        ui.showSnack('Hotel creado correctamente', 3000);
        void router.push('/admin/hoteles');
      }
    } else if (hotelId.value != null) {
      const v = form;
      const body: UpdateAlojamientoDTO = {
        alojamientoID: hotelId.value,
        nombre: v.nombre || undefined,
        descripcion: v.descripcion || undefined,
        direccion: v.direccion || undefined,
        ciudad: v.ciudad || undefined,
        provincia: v.provincia || undefined,
        pais: v.pais || undefined,
        latitud: v.latitud ?? undefined,
        longitud: v.longitud ?? undefined,
        telefono: v.telefono || undefined,
        email: v.email || undefined,
        sitioWeb: v.sitioWeb || undefined,
        horaCheckIn: v.horaCheckIn || undefined,
        horaCheckOut: v.horaCheckOut || undefined,
        politicaCancelacion: v.politicaCancelacion || undefined,
        estadoAlojamiento: v.estadoAlojamiento || undefined,
      };
      const res = await alojamientosUpdate(hotelId.value, body);
      if (res.success) {
        ui.showSnack('Hotel actualizado correctamente', 3000);
        void router.push('/admin/hoteles');
      }
    }
  } finally {
    guardando.value = false;
  }
}
</script>

<template>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <div v-else>
    <h2 class="mb-4">{{ isCreate ? 'Nuevo hotel' : 'Editar hotel #' + hotelId }}</h2>
    <v-card>
      <v-card-text class="d-flex flex-column gap-2">
        <template v-if="isCreate">
          <v-text-field v-model.number="form.tipoAlojID" label="tipoAlojID" type="number" variant="outlined" />
          <v-text-field v-model.number="form.adminUsuarioID" label="adminUsuarioID" type="number" variant="outlined" />
        </template>
        <v-text-field v-model="form.nombre" label="Nombre" variant="outlined" />
        <v-text-field v-model="form.slug" label="Slug" variant="outlined" />
        <v-select
          v-model="form.categoria"
          :items="[null, 1, 2, 3, 4, 5]"
          label="Categoría (estrellas)"
          variant="outlined"
          clearable
        />
        <v-text-field v-model="form.ruc" label="RUC" variant="outlined" />
        <v-text-field v-model="form.numRegistroTurismo" label="Registro turismo" variant="outlined" />
        <v-textarea v-model="form.descripcion" label="Descripción" variant="outlined" />
        <v-text-field v-model="form.direccion" label="Dirección" variant="outlined" />
        <v-text-field v-model="form.ciudad" label="Ciudad" variant="outlined" />
        <v-text-field v-model="form.provincia" label="Provincia" variant="outlined" />
        <v-text-field v-model="form.pais" label="País" variant="outlined" />
        <v-text-field v-model.number="form.latitud" label="Latitud" type="number" step="any" variant="outlined" />
        <v-text-field v-model.number="form.longitud" label="Longitud" type="number" step="any" variant="outlined" />
        <v-text-field v-model="form.telefono" label="Teléfono" variant="outlined" />
        <v-text-field v-model="form.email" label="Email" type="email" variant="outlined" />
        <v-text-field v-model="form.sitioWeb" label="Sitio web" variant="outlined" />
        <v-text-field v-model="form.horaCheckIn" label="Check-in" variant="outlined" />
        <v-text-field v-model="form.horaCheckOut" label="Check-out" variant="outlined" />
        <v-textarea v-model="form.politicaCancelacion" label="Política cancelación" variant="outlined" />
        <v-select
          v-if="!isCreate"
          v-model="form.estadoAlojamiento"
          :items="estados"
          label="Estado"
          variant="outlined"
          clearable
        />
        <v-btn color="primary" :loading="guardando" @click="save">{{ isCreate ? 'Crear hotel' : 'Guardar' }}</v-btn>
        <v-btn variant="text" to="/admin/hoteles">Volver</v-btn>
      </v-card-text>
    </v-card>
  </div>
</template>

<style scoped>
.center {
  display: flex;
  justify-content: center;
  padding: 2rem;
}
.mb-4 {
  margin-bottom: 1rem;
}
</style>
