// src/app/features/admin/admin-habitaciones-page.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { RouterLink } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatCardModule } from '@angular/material/card';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatTableModule } from '@angular/material/table';
import { HabitacionesService } from '../../core/services/habitaciones.service';
import type { HabitacionDTO } from '../../shared/models';

@Component({
  selector: 'app-admin-habitaciones-page',
  standalone: true,
  imports: [RouterLink, MatCardModule, MatTableModule, MatButtonModule, MatPaginatorModule, MatProgressSpinnerModule],
  templateUrl: './admin-habitaciones-page.component.html',
  styleUrl: './admin-habitaciones-page.component.scss',
})
export class AdminHabitacionesPageComponent implements OnInit {
  private readonly habitaciones = inject(HabitacionesService);

  displayedColumns: string[] = ['numero', 'sucursal', 'tipo', 'estado', 'acciones'];
  rows: HabitacionDTO[] = [];
  total = 0;
  pageIndex = 0;
  pageSize = 10;
  loading = false;

  ngOnInit(): void {
    this.load();
  }

  load(): void {
    this.loading = true;
    this.habitaciones
      .list({
        PageNumber: this.pageIndex + 1,
        PageSize: this.pageSize,
      })
      .subscribe({
        next: (r) => {
          this.rows = r.data?.data ?? [];
          this.total = r.data?.totalRecords ?? 0;
          this.loading = false;
        },
        error: () => (this.loading = false),
      });
  }

  onPage(e: PageEvent): void {
    this.pageIndex = e.pageIndex;
    this.pageSize = e.pageSize;
    this.load();
  }

  remove(guid: string): void {
    if (!confirm('¿Eliminar habitación?')) {
      return;
    }
    this.habitaciones.delete(guid).subscribe({ next: () => this.load() });
  }
}

<mat-card class="mb">
  <mat-card-title>Habitaciones (admin)</mat-card-title>
  <mat-card-subtitle>Inventario por sucursal: números, tipos y estado operativo.</mat-card-subtitle>
  <mat-card-actions>
    <a mat-raised-button color="primary" routerLink="/admin/habitaciones/nuevo">Nueva</a>
  </mat-card-actions>
</mat-card>

@if (loading) {
  <div class="center"><mat-spinner diameter="40" /></div>
} @else {
  <table mat-table [dataSource]="rows" class="mat-elevation-z1">
    <ng-container matColumnDef="numero">
      <th mat-header-cell *matHeaderCellDef>Número</th>
      <td mat-cell *matCellDef="let r">{{ r.numeroHabitacion }}</td>
    </ng-container>
    <ng-container matColumnDef="sucursal">
      <th mat-header-cell *matHeaderCellDef>Id sucursal</th>
      <td mat-cell *matCellDef="let r">{{ r.idSucursal }}</td>
    </ng-container>
    <ng-container matColumnDef="tipo">
      <th mat-header-cell *matHeaderCellDef>Id tipo</th>
      <td mat-cell *matCellDef="let r">{{ r.idTipoHabitacion }}</td>
    </ng-container>
    <ng-container matColumnDef="estado">
      <th mat-header-cell *matHeaderCellDef>Estado</th>
      <td mat-cell *matCellDef="let r">{{ r.estadoHabitacion }}</td>
    </ng-container>
    <ng-container matColumnDef="acciones">
      <th mat-header-cell *matHeaderCellDef></th>
      <td mat-cell *matCellDef="let r">
        <a mat-button [routerLink]="['/admin/habitaciones', r.habitacionGuid]">Editar</a>
        <button mat-button type="button" (click)="remove(r.habitacionGuid)">Eliminar</button>
      </td>
    </ng-container>
    <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
    <tr mat-row *matRowDef="let row; columns: displayedColumns"></tr>
  </table>
  <mat-paginator
    [length]="total"
    [pageIndex]="pageIndex"
    [pageSize]="pageSize"
    [pageSizeOptions]="[5, 10, 20]"
    (page)="onPage($event)"
  />
}

// src/views/admin/AdminHabitacionesPage.vue
<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { habitacionesDelete, habitacionesList } from '@/services/habitaciones';
import type { HabitacionDTO } from '@/models';

const rows = ref<HabitacionDTO[]>([]);
const total = ref(0);
const pageIndex = ref(0);
const pageSize = ref(10);
const loading = ref(false);

async function load(): Promise<void> {
  loading.value = true;
  try {
    const r = await habitacionesList({ PageNumber: pageIndex.value + 1, PageSize: pageSize.value });
    rows.value = r.data?.data ?? [];
    total.value = r.data?.totalRecords ?? 0;
  } finally {
    loading.value = false;
  }
}

function onPage(p: number): void {
  pageIndex.value = p - 1;
  void load();
}

async function remove(guid: string): Promise<void> {
  if (!confirm('¿Eliminar habitación?')) return;
  await habitacionesDelete(guid);
  void load();
}

onMounted(() => void load());
</script>

<template>
  <v-card class="mb-4">
    <v-card-title>Habitaciones</v-card-title>
    <v-card-actions>
      <v-btn color="primary" to="/admin/habitaciones/nuevo">Nueva</v-btn>
    </v-card-actions>
  </v-card>
  <div v-if="loading" class="center"><v-progress-circular indeterminate /></div>
  <template v-else>
    <v-table>
      <thead>
        <tr>
          <th>Número</th>
          <th>Sucursal</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th />
        </tr>
      </thead>
      <tbody>
        <tr v-for="r in rows" :key="r.habitacionGuid">
          <td>{{ r.numeroHabitacion }}</td>
          <td>{{ r.idSucursal }}</td>
          <td>{{ r.idTipoHabitacion }}</td>
          <td>{{ r.estadoHabitacion }}</td>
          <td>
            <v-btn size="small" variant="text" :to="'/admin/habitaciones/' + r.habitacionGuid">Editar</v-btn>
            <v-btn size="small" variant="text" color="error" @click="remove(r.habitacionGuid)">Eliminar</v-btn>
          </td>
        </tr>
      </tbody>
    </v-table>
    <v-pagination
      v-if="Math.ceil(total / pageSize) > 1"
      class="mt-4"
      :length="Math.max(1, Math.ceil(total / pageSize))"
      :model-value="pageIndex + 1"
      @update:model-value="onPage"
    />
  </template>
</template>

<style scoped>
.mb-4 {
  margin-bottom: 1rem;
}
.center {
  display: flex;
  justify-content: center;
  padding: 1.5rem;
}
</style>
