// src/layouts/AdminLayout.vue
<script setup lang="ts">
import { RouterView, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';

const auth = useAuthStore();
const router = useRouter();

function logout(): void {
  void auth.logout().then(() => router.push('/login'));
}
</script>

<template>
  <v-layout class="admin-shell">
    <v-navigation-drawer permanent class="admin-sidenav" width="268">
      <div class="admin-sidenav__brand">
        <span class="admin-sidenav__logo" aria-hidden="true" />
        <div>
          <span class="admin-sidenav__title">KAIROS</span>
          <span class="admin-sidenav__role">Administración</span>
        </div>
      </div>
      <v-list nav density="comfortable" class="admin-nav">
        <v-list-item to="/admin" exact title="Inicio" prepend-icon="mdi-view-dashboard" rounded="xl" />
        <v-list-item to="/admin/hoteles" title="Hoteles" prepend-icon="mdi-bed" rounded="xl" />
        <v-list-item to="/admin/alojamientos" title="Alojamientos" prepend-icon="mdi-home-city" rounded="xl" />
        <v-list-item to="/admin/habitaciones" title="Habitaciones" prepend-icon="mdi-bed-king" rounded="xl" />
        <v-list-item to="/admin/reservas" title="Reservas" prepend-icon="mdi-calendar-edit" rounded="xl" />
        <v-list-item to="/admin/clientes" title="Clientes (CRUD)" prepend-icon="mdi-account-group" rounded="xl" />
        <v-list-item to="/admin/sucursales" exact title="Sucursales" prepend-icon="mdi-domain" rounded="xl" />
        <v-list-item to="/admin/sucursales/nuevo" title="Nueva sucursal" prepend-icon="mdi-store-plus" rounded="xl" />
        <v-list-item to="/admin/tipos-habitacion" title="Tipos de habitación" prepend-icon="mdi-shape" rounded="xl" />
      </v-list>
    </v-navigation-drawer>

    <v-main class="admin-main">
      <header class="admin-topbar">
        <div class="admin-topbar__inner">
          <v-btn variant="outlined" :to="{ path: '/' }" class="admin-topbar__guest">
            <v-icon start>mdi-storefront</v-icon>
            Vista huésped
          </v-btn>
          <div class="admin-topbar__spacer" />
          <div v-if="auth.getLoginSnapshot()" class="admin-topbar__user">
            <v-icon class="text-primary" size="small">mdi-account-circle</v-icon>
            <span class="admin-topbar__name">
              {{ auth.getLoginSnapshot()?.nombreCompleto || auth.getLoginSnapshot()?.userName }}
            </span>
          </div>
          <v-btn variant="outlined" @click="logout">
            <v-icon start>mdi-logout</v-icon>
            Salir
          </v-btn>
        </div>
      </header>
      <div class="admin-content">
        <RouterView />
      </div>
    </v-main>
  </v-layout>
</template>

<style scoped src="./admin-layout.scss"></style>

// src/app/shared/components/admin-layout/admin-layout.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatListModule } from '@angular/material/list';
import { MatSidenavModule } from '@angular/material/sidenav';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-admin-layout',
  standalone: true,
  imports: [
    RouterOutlet,
    RouterLink,
    RouterLinkActive,
    MatSidenavModule,
    MatListModule,
    MatButtonModule,
    MatIconModule,
  ],
  templateUrl: './admin-layout.component.html',
  styleUrl: './admin-layout.component.scss',
})
export class AdminLayoutComponent {
  readonly auth = inject(AuthService);
}

<mat-sidenav-container class="admin-shell">
  <mat-sidenav mode="side" opened class="admin-sidenav">
    <div class="admin-sidenav__brand">
      <span class="admin-sidenav__logo" aria-hidden="true"></span>
      <div>
        <span class="admin-sidenav__title">Luxemburgo</span>
        <span class="admin-sidenav__role">Panel interno</span>
      </div>
    </div>
    <mat-nav-list class="admin-nav">
      <a mat-list-item routerLink="/admin" routerLinkActive="admin-nav__active" [routerLinkActiveOptions]="{ exact: true }">
        <mat-icon matListItemIcon>dashboard</mat-icon>
        <span matListItemTitle>Inicio</span>
      </a>
      <a mat-list-item routerLink="/admin/alojamientos" routerLinkActive="admin-nav__active">
        <mat-icon matListItemIcon>holiday_village</mat-icon>
        <span matListItemTitle>Alojamientos</span>
      </a>
      <a mat-list-item routerLink="/admin/habitaciones" routerLinkActive="admin-nav__active">
        <mat-icon matListItemIcon>bed</mat-icon>
        <span matListItemTitle>Habitaciones</span>
      </a>
      <a mat-list-item routerLink="/admin/reservas" routerLinkActive="admin-nav__active">
        <mat-icon matListItemIcon>event_note</mat-icon>
        <span matListItemTitle>Reservas</span>
      </a>
    </mat-nav-list>
  </mat-sidenav>
  <mat-sidenav-content class="admin-main">
    <header class="admin-topbar mat-elevation-z0">
      <div class="admin-topbar__inner">
        <div class="admin-topbar__spacer"></div>
        @if (auth.getLoginSnapshot(); as u) {
          <div class="admin-topbar__user">
            <mat-icon class="admin-topbar__user-icon" aria-hidden="true">account_circle</mat-icon>
            <span class="admin-topbar__name">{{ u.nombreCompleto || u.userName }}</span>
          </div>
        }
        <button mat-stroked-button type="button" class="admin-topbar__logout" (click)="auth.logout().subscribe()">
          <mat-icon>logout</mat-icon>
          Salir
        </button>
      </div>
    </header>
    <div class="admin-content">
      <router-outlet />
    </div>
  </mat-sidenav-content>
</mat-sidenav-container>
