// src/app/shared/components/public-layout/public-layout.component.ts
import { Component, inject } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatToolbarModule } from '@angular/material/toolbar';
import { AppRole } from '../../../core/constants/roles';
import { AuthService } from '../../../core/services/auth.service';

@Component({
  selector: 'app-public-layout',
  standalone: true,
  imports: [RouterOutlet, RouterLink, RouterLinkActive, MatToolbarModule, MatButtonModule, MatIconModule],
  templateUrl: './public-layout.component.html',
  styleUrl: './public-layout.component.scss',
})
export class PublicLayoutComponent {
  readonly auth = inject(AuthService);

  /** Enlace al panel de administración (roles staff). */
  showAdminPanel(): boolean {
    return this.auth.hasAnyRole([AppRole.Admin, AppRole.Vendedor]);
  }
}

<header class="site-header">
  <div class="site-header__inner">
    <a routerLink="/" class="site-header__brand" aria-label="KAIROS — inicio, vista huésped">
      <span class="site-header__mark" aria-hidden="true"></span>
      <span class="site-header__wordmark">
        <span class="site-header__name">KAIROS</span>
        <span class="site-header__tagline">Vista huésped — catálogo y reservas</span>
      </span>
    </a>

    <nav class="site-header__nav" aria-label="Navegación pública">
      <a routerLink="/alojamientos" routerLinkActive="is-active">Alojamientos</a>
      @if (auth.isAuthenticated()) {
        <a routerLink="/mis-reservas" routerLinkActive="is-active">Mis reservas</a>
        @if (showAdminPanel()) {
          <a routerLink="/admin" routerLinkActive="is-active">Administración</a>
        }
      }
    </nav>

    <div class="site-header__actions">
      @if (auth.isAuthenticated()) {
        <button mat-stroked-button type="button" class="site-header__cta" (click)="auth.logout().subscribe()">
          <mat-icon>logout</mat-icon>
          Cerrar sesión
        </button>
      } @else {
        <a mat-flat-button color="primary" routerLink="/login" class="site-header__cta site-header__cta--primary">
          Entrar
        </a>
      }
    </div>
  </div>
</header>

<main class="site-main">
  <router-outlet />
</main>

// src/layouts/PublicLayout.vue
<script setup lang="ts">
import { computed } from 'vue';
import { RouterLink, RouterView, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { AppRole } from '@/constants/roles';

const auth = useAuthStore();
const router = useRouter();

const showAdminPanel = computed(() => auth.hasAnyRole([AppRole.Admin, AppRole.Vendedor]));

function logout(): void {
  void auth.logout().then(() => router.push('/login'));
}
</script>

<template>
  <header class="site-header">
    <div class="site-header__inner">
      <RouterLink to="/" class="site-header__brand" aria-label="KAIROS — inicio">
        <span class="site-header__mark" aria-hidden="true" />
        <span class="site-header__wordmark">
          <span class="site-header__name">KAIROS</span>
          <span class="site-header__tagline">Vista huésped — catálogo y reservas</span>
        </span>
      </RouterLink>

      <nav class="site-header__nav" aria-label="Navegación pública">
        <RouterLink to="/alojamientos" custom v-slot="{ href, navigate, isActive }">
          <a :href="href" :class="{ 'is-active': isActive }" @click="navigate">Alojamientos</a>
        </RouterLink>
        <template v-if="auth.isAuthenticated()">
          <RouterLink to="/mis-reservas" custom v-slot="{ href, navigate, isActive }">
            <a :href="href" :class="{ 'is-active': isActive }" @click="navigate">Mis reservas</a>
          </RouterLink>
          <RouterLink v-if="showAdminPanel" to="/admin" custom v-slot="{ href, navigate, isActive }">
            <a :href="href" :class="{ 'is-active': isActive }" @click="navigate">Administración</a>
          </RouterLink>
        </template>
      </nav>

      <div class="site-header__actions">
        <v-btn v-if="auth.isAuthenticated()" variant="outlined" class="site-header__cta" @click="logout">
          <v-icon start>mdi-logout</v-icon>
          Cerrar sesión
        </v-btn>
        <v-btn v-else color="primary" to="/login" class="site-header__cta site-header__cta--primary">Entrar</v-btn>
      </div>
    </div>
  </header>

  <main class="site-main">
    <RouterView />
  </main>
</template>

<style scoped src="./public-layout.scss"></style>
