// src/app/features/auth/login-page.component.ts
import { Component, inject } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatIconModule } from '@angular/material/icon';
import { MatInputModule } from '@angular/material/input';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { AppRole } from '../../core/constants/roles';
import { AuthService } from '../../core/services/auth.service';
import { UserContextService } from '../../core/services/user-context.service';

@Component({
  selector: 'app-login-page',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    MatFormFieldModule,
    MatInputModule,
    MatIconModule,
    MatButtonModule,
    MatSnackBarModule,
  ],
  templateUrl: './login-page.component.html',
  styleUrl: './login-page.component.scss',
})
export class LoginPageComponent {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly userCtx = inject(UserContextService);
  private readonly router = inject(Router);
  private readonly route = inject(ActivatedRoute);
  private readonly snack = inject(MatSnackBar);

  readonly form = this.fb.nonNullable.group({
    userName: this.fb.control('', Validators.required),
    password: this.fb.control('', Validators.required),
  });
  busy = false;

  submit(): void {
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }
    this.busy = true;
    this.auth.login(this.form.getRawValue()).subscribe({
      next: (res) => {
        this.busy = false;
        if (res.success) {
          const returnUrl = this.route.snapshot.queryParamMap.get('returnUrl');
          if (returnUrl) {
            void this.router.navigateByUrl(returnUrl);
          } else if (this.auth.hasAnyRole([AppRole.Admin, AppRole.Vendedor])) {
            void this.router.navigate(['/admin']);
          } else {
            void this.router.navigate(['/']);
          }
          this.userCtx.refreshMe().subscribe();
        } else {
          this.snack.open(res.message || 'No se pudo iniciar sesión', 'Cerrar');
        }
      },
      error: () => (this.busy = false),
    });
  }
}

<div class="login-shell">
  <aside class="login-hero" aria-hidden="true">
    <div class="login-hero__glow"></div>
    <blockquote class="login-hero__quote">
      <p>«Un buen hotel no es solo un techo: es el tono correcto, la luz y la tranquilidad.»</p>
    </blockquote>
    <p class="login-hero__credit">Hospitalidad europea · Desde 1924</p>
  </aside>

  <section class="login-panel" aria-labelledby="login-title">
    <div class="login-panel__card">
      <p class="login-panel__eyebrow">Acceso para huéspedes y personal</p>
      <h1 id="login-title" class="login-panel__title">Bienvenido de nuevo</h1>
      <p class="login-panel__sub">Introduce tus credenciales para gestionar reservas y tu perfil.</p>

      <form class="login-form" [formGroup]="form" (ngSubmit)="submit()">
        <mat-form-field appearance="outline" class="login-form__field">
          <mat-label>Usuario</mat-label>
          <input matInput formControlName="userName" autocomplete="username" />
          <mat-icon matPrefix class="login-form__prefix">person</mat-icon>
        </mat-form-field>
        <mat-form-field appearance="outline" class="login-form__field">
          <mat-label>Contraseña</mat-label>
          <input matInput type="password" formControlName="password" autocomplete="current-password" />
          <mat-icon matPrefix class="login-form__prefix">lock</mat-icon>
        </mat-form-field>
        <button
          mat-flat-button
          color="primary"
          class="login-form__submit"
          type="submit"
          [disabled]="busy || form.invalid"
        >
          @if (busy) {
            Accediendo…
          } @else {
            Continuar
          }
        </button>
      </form>
    </div>
  </section>
</div>

// src/views/auth/LoginPage.vue
<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useAuthStore } from '@/stores/auth';
import { useUiStore } from '@/stores/ui';
import { useUserContextStore } from '@/stores/userContext';
import { AppRole } from '@/constants/roles';

const auth = useAuthStore();
const userCtx = useUserContextStore();
const ui = useUiStore();
const router = useRouter();
const route = useRoute();

const form = reactive({ userName: '', password: '' });
const busy = ref(false);

function submit(): void {
  if (!form.userName || !form.password) {
    return;
  }
  busy.value = true;
  void auth
    .login({ userName: form.userName, password: form.password })
    .then((res) => {
      busy.value = false;
      if (res.success) {
        const ru = route.query.returnUrl;
        const returnUrl = typeof ru === 'string' ? ru : null;
        void userCtx.refreshMe();
        if (returnUrl) {
          void router.push(returnUrl);
        } else if (auth.hasAnyRole([AppRole.Admin, AppRole.Vendedor])) {
          void router.push('/admin');
        } else {
          void router.push('/');
        }
      } else {
        ui.showSnack(res.message || 'No se pudo iniciar sesión', 6000);
      }
    })
    .catch(() => {
      busy.value = false;
    });
}
</script>

<template>
  <div class="login-shell">
    <aside class="login-hero" aria-hidden="true">
      <div class="login-hero__glow" />
      <blockquote class="login-hero__quote">
        <p>«Un buen hotel no es solo un techo: es el tono correcto, la luz y la tranquilidad.»</p>
      </blockquote>
      <p class="login-hero__credit">Hospitalidad europea · Desde 1924</p>
    </aside>

    <section class="login-panel" aria-labelledby="login-title">
      <div class="login-panel__card">
        <p class="login-panel__eyebrow">Acceso para huéspedes y personal</p>
        <h1 id="login-title" class="login-panel__title">Bienvenido de nuevo</h1>
        <p class="login-panel__sub">Introduce tus credenciales para gestionar reservas y tu perfil.</p>

        <form class="login-form" @submit.prevent="submit()">
          <v-text-field
            v-model="form.userName"
            class="login-form__field"
            label="Usuario"
            variant="outlined"
            autocomplete="username"
            prepend-inner-icon="mdi-account"
          />
          <v-text-field
            v-model="form.password"
            class="login-form__field"
            label="Contraseña"
            type="password"
            variant="outlined"
            autocomplete="current-password"
            prepend-inner-icon="mdi-lock"
          />
          <v-btn color="primary" block class="login-form__submit" type="submit" :disabled="busy">
            {{ busy ? 'Accediendo…' : 'Continuar' }}
          </v-btn>
        </form>
      </div>
    </section>
  </div>
</template>

<style scoped src="./login-page.scss"></style>
